/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesWebAppDevelopmentRouteImport } from './routes/services/web-app-development'
import { Route as ServicesUxUiDesignRouteImport } from './routes/services/ux-ui-design'
import { Route as ServicesQaTestAutomationRouteImport } from './routes/services/qa-test-automation'
import { Route as ServicesMvpRouteImport } from './routes/services/mvp'
import { Route as ServicesMobileAppDevelopmentRouteImport } from './routes/services/mobile-app-development'
import { Route as ServicesDataEngineeringRouteImport } from './routes/services/data-engineering'
import { Route as ServicesCloudEngineeringDevopsRouteImport } from './routes/services/cloud-engineering-devops'
import { Route as ServicesAwsRouteImport } from './routes/services/aws'
import { Route as ServicesAiAgentsRouteImport } from './routes/services/ai-agents'
import { Route as ServicesAgenticAiRouteImport } from './routes/services/agentic-ai'
import { Route as OurBpoServicesSolutionTechnicalSupportRouteImport } from './routes/Our-Bpo-Services/solution/technical-support'
import { Route as OurBpoServicesSolutionPaymentProcessingRouteImport } from './routes/Our-Bpo-Services/solution/payment-processing'
import { Route as OurBpoServicesSolutionOutboundServicesRouteImport } from './routes/Our-Bpo-Services/solution/outbound-services'
import { Route as OurBpoServicesSolutionLeadGenerationRouteImport } from './routes/Our-Bpo-Services/solution/lead-generation'
import { Route as OurBpoServicesSolutionInboundServicesRouteImport } from './routes/Our-Bpo-Services/solution/inbound-services'
import { Route as OurBpoServicesSolutionInboundSalesRouteImport } from './routes/Our-Bpo-Services/solution/inbound-sales'
import { Route as OurBpoServicesSolutionFacilityAndProcurementRouteImport } from './routes/Our-Bpo-Services/solution/facility-and-procurement'
import { Route as OurBpoServicesSolutionDirectResponseMarketingRouteImport } from './routes/Our-Bpo-Services/solution/direct-response-marketing'
import { Route as OurBpoServicesSolutionCustomerRetentionRouteImport } from './routes/Our-Bpo-Services/solution/customer-retention'
import { Route as OurBpoServicesSolutionClaimsProcessingRouteImport } from './routes/Our-Bpo-Services/solution/claims-processing'
import { Route as OurBpoServicesSolutionBackOfficeProcessingRouteImport } from './routes/Our-Bpo-Services/solution/back-office-processing'
import { Route as OurBpoServicesSolutionAccountingAndCollectionsRouteImport } from './routes/Our-Bpo-Services/solution/accounting-and-collections'
import { Route as OurBpoServicesIndustriesTelecommunicationsRouteImport } from './routes/Our-Bpo-Services/industries/telecommunications.tsx'
import { Route as OurBpoServicesIndustriesTechnologyRouteImport } from './routes/Our-Bpo-Services/industries/technology.tsx'
import { Route as OurBpoServicesIndustriesRetailRouteImport } from './routes/Our-Bpo-Services/industries/retail.tsx'
import { Route as OurBpoServicesIndustriesRealEstateRouteImport } from './routes/Our-Bpo-Services/industries/real-estate.tsx'
import { Route as OurBpoServicesIndustriesLogisticsSupplyChainRouteImport } from './routes/Our-Bpo-Services/industries/logistics-supply-chain.tsx'
import { Route as OurBpoServicesIndustriesInsuranceRouteImport } from './routes/Our-Bpo-Services/industries/insurance.tsx'
import { Route as OurBpoServicesIndustriesHealthcareRouteImport } from './routes/Our-Bpo-Services/industries/healthcare.tsx'
import { Route as OurBpoServicesIndustriesFinancialRouteImport } from './routes/Our-Bpo-Services/industries/financial.tsx'
import { Route as OurBpoServicesIndustriesEntertainmentRouteImport } from './routes/Our-Bpo-Services/industries/entertainment.tsx'

const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebAppDevelopmentRoute =
  ServicesWebAppDevelopmentRouteImport.update({
    id: '/services/web-app-development',
    path: '/services/web-app-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesUxUiDesignRoute = ServicesUxUiDesignRouteImport.update({
  id: '/services/ux-ui-design',
  path: '/services/ux-ui-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesQaTestAutomationRoute =
  ServicesQaTestAutomationRouteImport.update({
    id: '/services/qa-test-automation',
    path: '/services/qa-test-automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesMvpRoute = ServicesMvpRouteImport.update({
  id: '/services/mvp',
  path: '/services/mvp',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMobileAppDevelopmentRoute =
  ServicesMobileAppDevelopmentRouteImport.update({
    id: '/services/mobile-app-development',
    path: '/services/mobile-app-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesDataEngineeringRoute = ServicesDataEngineeringRouteImport.update({
  id: '/services/data-engineering',
  path: '/services/data-engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCloudEngineeringDevopsRoute =
  ServicesCloudEngineeringDevopsRouteImport.update({
    id: '/services/cloud-engineering-devops',
    path: '/services/cloud-engineering-devops',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAwsRoute = ServicesAwsRouteImport.update({
  id: '/services/aws',
  path: '/services/aws',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiAgentsRoute = ServicesAiAgentsRouteImport.update({
  id: '/services/ai-agents',
  path: '/services/ai-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAgenticAiRoute = ServicesAgenticAiRouteImport.update({
  id: '/services/agentic-ai',
  path: '/services/agentic-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const OurBpoServicesSolutionTechnicalSupportRoute =
  OurBpoServicesSolutionTechnicalSupportRouteImport.update({
    id: '/Our-Bpo-Services/solution/technical-support',
    path: '/Our-Bpo-Services/solution/technical-support',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesSolutionPaymentProcessingRoute =
  OurBpoServicesSolutionPaymentProcessingRouteImport.update({
    id: '/Our-Bpo-Services/solution/payment-processing',
    path: '/Our-Bpo-Services/solution/payment-processing',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesSolutionOutboundServicesRoute =
  OurBpoServicesSolutionOutboundServicesRouteImport.update({
    id: '/Our-Bpo-Services/solution/outbound-services',
    path: '/Our-Bpo-Services/solution/outbound-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesSolutionLeadGenerationRoute =
  OurBpoServicesSolutionLeadGenerationRouteImport.update({
    id: '/Our-Bpo-Services/solution/lead-generation',
    path: '/Our-Bpo-Services/solution/lead-generation',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesSolutionInboundServicesRoute =
  OurBpoServicesSolutionInboundServicesRouteImport.update({
    id: '/Our-Bpo-Services/solution/inbound-services',
    path: '/Our-Bpo-Services/solution/inbound-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesSolutionInboundSalesRoute =
  OurBpoServicesSolutionInboundSalesRouteImport.update({
    id: '/Our-Bpo-Services/solution/inbound-sales',
    path: '/Our-Bpo-Services/solution/inbound-sales',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesSolutionFacilityAndProcurementRoute =
  OurBpoServicesSolutionFacilityAndProcurementRouteImport.update({
    id: '/Our-Bpo-Services/solution/facility-and-procurement',
    path: '/Our-Bpo-Services/solution/facility-and-procurement',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesSolutionDirectResponseMarketingRoute =
  OurBpoServicesSolutionDirectResponseMarketingRouteImport.update({
    id: '/Our-Bpo-Services/solution/direct-response-marketing',
    path: '/Our-Bpo-Services/solution/direct-response-marketing',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesSolutionCustomerRetentionRoute =
  OurBpoServicesSolutionCustomerRetentionRouteImport.update({
    id: '/Our-Bpo-Services/solution/customer-retention',
    path: '/Our-Bpo-Services/solution/customer-retention',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesSolutionClaimsProcessingRoute =
  OurBpoServicesSolutionClaimsProcessingRouteImport.update({
    id: '/Our-Bpo-Services/solution/claims-processing',
    path: '/Our-Bpo-Services/solution/claims-processing',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesSolutionBackOfficeProcessingRoute =
  OurBpoServicesSolutionBackOfficeProcessingRouteImport.update({
    id: '/Our-Bpo-Services/solution/back-office-processing',
    path: '/Our-Bpo-Services/solution/back-office-processing',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesSolutionAccountingAndCollectionsRoute =
  OurBpoServicesSolutionAccountingAndCollectionsRouteImport.update({
    id: '/Our-Bpo-Services/solution/accounting-and-collections',
    path: '/Our-Bpo-Services/solution/accounting-and-collections',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesIndustriesTelecommunicationsRoute =
  OurBpoServicesIndustriesTelecommunicationsRouteImport.update({
    id: '/Our-Bpo-Services/Industries/telecommunications',
    path: '/Our-Bpo-Services/Industries/telecommunications',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesIndustriesTechnologyRoute =
  OurBpoServicesIndustriesTechnologyRouteImport.update({
    id: '/Our-Bpo-Services/Industries/technology',
    path: '/Our-Bpo-Services/Industries/technology',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesIndustriesRetailRoute =
  OurBpoServicesIndustriesRetailRouteImport.update({
    id: '/Our-Bpo-Services/Industries/retail',
    path: '/Our-Bpo-Services/Industries/retail',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesIndustriesRealEstateRoute =
  OurBpoServicesIndustriesRealEstateRouteImport.update({
    id: '/Our-Bpo-Services/Industries/real-estate',
    path: '/Our-Bpo-Services/Industries/real-estate',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesIndustriesLogisticsSupplyChainRoute =
  OurBpoServicesIndustriesLogisticsSupplyChainRouteImport.update({
    id: '/Our-Bpo-Services/Industries/logistics-supply-chain',
    path: '/Our-Bpo-Services/Industries/logistics-supply-chain',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesIndustriesInsuranceRoute =
  OurBpoServicesIndustriesInsuranceRouteImport.update({
    id: '/Our-Bpo-Services/Industries/insurance',
    path: '/Our-Bpo-Services/Industries/insurance',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesIndustriesHealthcareRoute =
  OurBpoServicesIndustriesHealthcareRouteImport.update({
    id: '/Our-Bpo-Services/Industries/healthcare',
    path: '/Our-Bpo-Services/Industries/healthcare',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesIndustriesFinancialRoute =
  OurBpoServicesIndustriesFinancialRouteImport.update({
    id: '/Our-Bpo-Services/Industries/financial',
    path: '/Our-Bpo-Services/Industries/financial',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesIndustriesEntertainmentRoute =
  OurBpoServicesIndustriesEntertainmentRouteImport.update({
    id: '/Our-Bpo-Services/Industries/entertainment',
    path: '/Our-Bpo-Services/Industries/entertainment',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/services/agentic-ai': typeof ServicesAgenticAiRoute
  '/services/ai-agents': typeof ServicesAiAgentsRoute
  '/services/aws': typeof ServicesAwsRoute
  '/services/cloud-engineering-devops': typeof ServicesCloudEngineeringDevopsRoute
  '/services/data-engineering': typeof ServicesDataEngineeringRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/mvp': typeof ServicesMvpRoute
  '/services/qa-test-automation': typeof ServicesQaTestAutomationRoute
  '/services/ux-ui-design': typeof ServicesUxUiDesignRoute
  '/services/web-app-development': typeof ServicesWebAppDevelopmentRoute
  '/services/': typeof ServicesIndexRoute
  '/Our-Bpo-Services/Industries/entertainment': typeof OurBpoServicesIndustriesEntertainmentRoute
  '/Our-Bpo-Services/Industries/financial': typeof OurBpoServicesIndustriesFinancialRoute
  '/Our-Bpo-Services/Industries/healthcare': typeof OurBpoServicesIndustriesHealthcareRoute
  '/Our-Bpo-Services/Industries/insurance': typeof OurBpoServicesIndustriesInsuranceRoute
  '/Our-Bpo-Services/Industries/logistics-supply-chain': typeof OurBpoServicesIndustriesLogisticsSupplyChainRoute
  '/Our-Bpo-Services/Industries/real-estate': typeof OurBpoServicesIndustriesRealEstateRoute
  '/Our-Bpo-Services/Industries/retail': typeof OurBpoServicesIndustriesRetailRoute
  '/Our-Bpo-Services/Industries/technology': typeof OurBpoServicesIndustriesTechnologyRoute
  '/Our-Bpo-Services/Industries/telecommunications': typeof OurBpoServicesIndustriesTelecommunicationsRoute
  '/Our-Bpo-Services/solution/accounting-and-collections': typeof OurBpoServicesSolutionAccountingAndCollectionsRoute
  '/Our-Bpo-Services/solution/back-office-processing': typeof OurBpoServicesSolutionBackOfficeProcessingRoute
  '/Our-Bpo-Services/solution/claims-processing': typeof OurBpoServicesSolutionClaimsProcessingRoute
  '/Our-Bpo-Services/solution/customer-retention': typeof OurBpoServicesSolutionCustomerRetentionRoute
  '/Our-Bpo-Services/solution/direct-response-marketing': typeof OurBpoServicesSolutionDirectResponseMarketingRoute
  '/Our-Bpo-Services/solution/facility-and-procurement': typeof OurBpoServicesSolutionFacilityAndProcurementRoute
  '/Our-Bpo-Services/solution/inbound-sales': typeof OurBpoServicesSolutionInboundSalesRoute
  '/Our-Bpo-Services/solution/inbound-services': typeof OurBpoServicesSolutionInboundServicesRoute
  '/Our-Bpo-Services/solution/lead-generation': typeof OurBpoServicesSolutionLeadGenerationRoute
  '/Our-Bpo-Services/solution/outbound-services': typeof OurBpoServicesSolutionOutboundServicesRoute
  '/Our-Bpo-Services/solution/payment-processing': typeof OurBpoServicesSolutionPaymentProcessingRoute
  '/Our-Bpo-Services/solution/technical-support': typeof OurBpoServicesSolutionTechnicalSupportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/services/agentic-ai': typeof ServicesAgenticAiRoute
  '/services/ai-agents': typeof ServicesAiAgentsRoute
  '/services/aws': typeof ServicesAwsRoute
  '/services/cloud-engineering-devops': typeof ServicesCloudEngineeringDevopsRoute
  '/services/data-engineering': typeof ServicesDataEngineeringRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/mvp': typeof ServicesMvpRoute
  '/services/qa-test-automation': typeof ServicesQaTestAutomationRoute
  '/services/ux-ui-design': typeof ServicesUxUiDesignRoute
  '/services/web-app-development': typeof ServicesWebAppDevelopmentRoute
  '/services': typeof ServicesIndexRoute
  '/Our-Bpo-Services/Industries/entertainment': typeof OurBpoServicesIndustriesEntertainmentRoute
  '/Our-Bpo-Services/Industries/financial': typeof OurBpoServicesIndustriesFinancialRoute
  '/Our-Bpo-Services/Industries/healthcare': typeof OurBpoServicesIndustriesHealthcareRoute
  '/Our-Bpo-Services/Industries/insurance': typeof OurBpoServicesIndustriesInsuranceRoute
  '/Our-Bpo-Services/Industries/logistics-supply-chain': typeof OurBpoServicesIndustriesLogisticsSupplyChainRoute
  '/Our-Bpo-Services/Industries/real-estate': typeof OurBpoServicesIndustriesRealEstateRoute
  '/Our-Bpo-Services/Industries/retail': typeof OurBpoServicesIndustriesRetailRoute
  '/Our-Bpo-Services/Industries/technology': typeof OurBpoServicesIndustriesTechnologyRoute
  '/Our-Bpo-Services/Industries/telecommunications': typeof OurBpoServicesIndustriesTelecommunicationsRoute
  '/Our-Bpo-Services/solution/accounting-and-collections': typeof OurBpoServicesSolutionAccountingAndCollectionsRoute
  '/Our-Bpo-Services/solution/back-office-processing': typeof OurBpoServicesSolutionBackOfficeProcessingRoute
  '/Our-Bpo-Services/solution/claims-processing': typeof OurBpoServicesSolutionClaimsProcessingRoute
  '/Our-Bpo-Services/solution/customer-retention': typeof OurBpoServicesSolutionCustomerRetentionRoute
  '/Our-Bpo-Services/solution/direct-response-marketing': typeof OurBpoServicesSolutionDirectResponseMarketingRoute
  '/Our-Bpo-Services/solution/facility-and-procurement': typeof OurBpoServicesSolutionFacilityAndProcurementRoute
  '/Our-Bpo-Services/solution/inbound-sales': typeof OurBpoServicesSolutionInboundSalesRoute
  '/Our-Bpo-Services/solution/inbound-services': typeof OurBpoServicesSolutionInboundServicesRoute
  '/Our-Bpo-Services/solution/lead-generation': typeof OurBpoServicesSolutionLeadGenerationRoute
  '/Our-Bpo-Services/solution/outbound-services': typeof OurBpoServicesSolutionOutboundServicesRoute
  '/Our-Bpo-Services/solution/payment-processing': typeof OurBpoServicesSolutionPaymentProcessingRoute
  '/Our-Bpo-Services/solution/technical-support': typeof OurBpoServicesSolutionTechnicalSupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/services/agentic-ai': typeof ServicesAgenticAiRoute
  '/services/ai-agents': typeof ServicesAiAgentsRoute
  '/services/aws': typeof ServicesAwsRoute
  '/services/cloud-engineering-devops': typeof ServicesCloudEngineeringDevopsRoute
  '/services/data-engineering': typeof ServicesDataEngineeringRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/mvp': typeof ServicesMvpRoute
  '/services/qa-test-automation': typeof ServicesQaTestAutomationRoute
  '/services/ux-ui-design': typeof ServicesUxUiDesignRoute
  '/services/web-app-development': typeof ServicesWebAppDevelopmentRoute
  '/services/': typeof ServicesIndexRoute
  '/Our-Bpo-Services/Industries/entertainment': typeof OurBpoServicesIndustriesEntertainmentRoute
  '/Our-Bpo-Services/Industries/financial': typeof OurBpoServicesIndustriesFinancialRoute
  '/Our-Bpo-Services/Industries/healthcare': typeof OurBpoServicesIndustriesHealthcareRoute
  '/Our-Bpo-Services/Industries/insurance': typeof OurBpoServicesIndustriesInsuranceRoute
  '/Our-Bpo-Services/Industries/logistics-supply-chain': typeof OurBpoServicesIndustriesLogisticsSupplyChainRoute
  '/Our-Bpo-Services/Industries/real-estate': typeof OurBpoServicesIndustriesRealEstateRoute
  '/Our-Bpo-Services/Industries/retail': typeof OurBpoServicesIndustriesRetailRoute
  '/Our-Bpo-Services/Industries/technology': typeof OurBpoServicesIndustriesTechnologyRoute
  '/Our-Bpo-Services/Industries/telecommunications': typeof OurBpoServicesIndustriesTelecommunicationsRoute
  '/Our-Bpo-Services/solution/accounting-and-collections': typeof OurBpoServicesSolutionAccountingAndCollectionsRoute
  '/Our-Bpo-Services/solution/back-office-processing': typeof OurBpoServicesSolutionBackOfficeProcessingRoute
  '/Our-Bpo-Services/solution/claims-processing': typeof OurBpoServicesSolutionClaimsProcessingRoute
  '/Our-Bpo-Services/solution/customer-retention': typeof OurBpoServicesSolutionCustomerRetentionRoute
  '/Our-Bpo-Services/solution/direct-response-marketing': typeof OurBpoServicesSolutionDirectResponseMarketingRoute
  '/Our-Bpo-Services/solution/facility-and-procurement': typeof OurBpoServicesSolutionFacilityAndProcurementRoute
  '/Our-Bpo-Services/solution/inbound-sales': typeof OurBpoServicesSolutionInboundSalesRoute
  '/Our-Bpo-Services/solution/inbound-services': typeof OurBpoServicesSolutionInboundServicesRoute
  '/Our-Bpo-Services/solution/lead-generation': typeof OurBpoServicesSolutionLeadGenerationRoute
  '/Our-Bpo-Services/solution/outbound-services': typeof OurBpoServicesSolutionOutboundServicesRoute
  '/Our-Bpo-Services/solution/payment-processing': typeof OurBpoServicesSolutionPaymentProcessingRoute
  '/Our-Bpo-Services/solution/technical-support': typeof OurBpoServicesSolutionTechnicalSupportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact-us'
    | '/services/agentic-ai'
    | '/services/ai-agents'
    | '/services/aws'
    | '/services/cloud-engineering-devops'
    | '/services/data-engineering'
    | '/services/mobile-app-development'
    | '/services/mvp'
    | '/services/qa-test-automation'
    | '/services/ux-ui-design'
    | '/services/web-app-development'
    | '/services/'
    | '/Our-Bpo-Services/Industries/entertainment'
    | '/Our-Bpo-Services/Industries/financial'
    | '/Our-Bpo-Services/Industries/healthcare'
    | '/Our-Bpo-Services/Industries/insurance'
    | '/Our-Bpo-Services/Industries/logistics-supply-chain'
    | '/Our-Bpo-Services/Industries/real-estate'
    | '/Our-Bpo-Services/Industries/retail'
    | '/Our-Bpo-Services/Industries/technology'
    | '/Our-Bpo-Services/Industries/telecommunications'
    | '/Our-Bpo-Services/solution/accounting-and-collections'
    | '/Our-Bpo-Services/solution/back-office-processing'
    | '/Our-Bpo-Services/solution/claims-processing'
    | '/Our-Bpo-Services/solution/customer-retention'
    | '/Our-Bpo-Services/solution/direct-response-marketing'
    | '/Our-Bpo-Services/solution/facility-and-procurement'
    | '/Our-Bpo-Services/solution/inbound-sales'
    | '/Our-Bpo-Services/solution/inbound-services'
    | '/Our-Bpo-Services/solution/lead-generation'
    | '/Our-Bpo-Services/solution/outbound-services'
    | '/Our-Bpo-Services/solution/payment-processing'
    | '/Our-Bpo-Services/solution/technical-support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact-us'
    | '/services/agentic-ai'
    | '/services/ai-agents'
    | '/services/aws'
    | '/services/cloud-engineering-devops'
    | '/services/data-engineering'
    | '/services/mobile-app-development'
    | '/services/mvp'
    | '/services/qa-test-automation'
    | '/services/ux-ui-design'
    | '/services/web-app-development'
    | '/services'
    | '/Our-Bpo-Services/Industries/entertainment'
    | '/Our-Bpo-Services/Industries/financial'
    | '/Our-Bpo-Services/Industries/healthcare'
    | '/Our-Bpo-Services/Industries/insurance'
    | '/Our-Bpo-Services/Industries/logistics-supply-chain'
    | '/Our-Bpo-Services/Industries/real-estate'
    | '/Our-Bpo-Services/Industries/retail'
    | '/Our-Bpo-Services/Industries/technology'
    | '/Our-Bpo-Services/Industries/telecommunications'
    | '/Our-Bpo-Services/solution/accounting-and-collections'
    | '/Our-Bpo-Services/solution/back-office-processing'
    | '/Our-Bpo-Services/solution/claims-processing'
    | '/Our-Bpo-Services/solution/customer-retention'
    | '/Our-Bpo-Services/solution/direct-response-marketing'
    | '/Our-Bpo-Services/solution/facility-and-procurement'
    | '/Our-Bpo-Services/solution/inbound-sales'
    | '/Our-Bpo-Services/solution/inbound-services'
    | '/Our-Bpo-Services/solution/lead-generation'
    | '/Our-Bpo-Services/solution/outbound-services'
    | '/Our-Bpo-Services/solution/payment-processing'
    | '/Our-Bpo-Services/solution/technical-support'
  id:
    | '__root__'
    | '/'
    | '/contact-us'
    | '/services/agentic-ai'
    | '/services/ai-agents'
    | '/services/aws'
    | '/services/cloud-engineering-devops'
    | '/services/data-engineering'
    | '/services/mobile-app-development'
    | '/services/mvp'
    | '/services/qa-test-automation'
    | '/services/ux-ui-design'
    | '/services/web-app-development'
    | '/services/'
    | '/Our-Bpo-Services/Industries/entertainment'
    | '/Our-Bpo-Services/Industries/financial'
    | '/Our-Bpo-Services/Industries/healthcare'
    | '/Our-Bpo-Services/Industries/insurance'
    | '/Our-Bpo-Services/Industries/logistics-supply-chain'
    | '/Our-Bpo-Services/Industries/real-estate'
    | '/Our-Bpo-Services/Industries/retail'
    | '/Our-Bpo-Services/Industries/technology'
    | '/Our-Bpo-Services/Industries/telecommunications'
    | '/Our-Bpo-Services/solution/accounting-and-collections'
    | '/Our-Bpo-Services/solution/back-office-processing'
    | '/Our-Bpo-Services/solution/claims-processing'
    | '/Our-Bpo-Services/solution/customer-retention'
    | '/Our-Bpo-Services/solution/direct-response-marketing'
    | '/Our-Bpo-Services/solution/facility-and-procurement'
    | '/Our-Bpo-Services/solution/inbound-sales'
    | '/Our-Bpo-Services/solution/inbound-services'
    | '/Our-Bpo-Services/solution/lead-generation'
    | '/Our-Bpo-Services/solution/outbound-services'
    | '/Our-Bpo-Services/solution/payment-processing'
    | '/Our-Bpo-Services/solution/technical-support'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactUsRoute: typeof ContactUsRoute
  ServicesAgenticAiRoute: typeof ServicesAgenticAiRoute
  ServicesAiAgentsRoute: typeof ServicesAiAgentsRoute
  ServicesAwsRoute: typeof ServicesAwsRoute
  ServicesCloudEngineeringDevopsRoute: typeof ServicesCloudEngineeringDevopsRoute
  ServicesDataEngineeringRoute: typeof ServicesDataEngineeringRoute
  ServicesMobileAppDevelopmentRoute: typeof ServicesMobileAppDevelopmentRoute
  ServicesMvpRoute: typeof ServicesMvpRoute
  ServicesQaTestAutomationRoute: typeof ServicesQaTestAutomationRoute
  ServicesUxUiDesignRoute: typeof ServicesUxUiDesignRoute
  ServicesWebAppDevelopmentRoute: typeof ServicesWebAppDevelopmentRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  OurBpoServicesIndustriesEntertainmentRoute: typeof OurBpoServicesIndustriesEntertainmentRoute
  OurBpoServicesIndustriesFinancialRoute: typeof OurBpoServicesIndustriesFinancialRoute
  OurBpoServicesIndustriesHealthcareRoute: typeof OurBpoServicesIndustriesHealthcareRoute
  OurBpoServicesIndustriesInsuranceRoute: typeof OurBpoServicesIndustriesInsuranceRoute
  OurBpoServicesIndustriesLogisticsSupplyChainRoute: typeof OurBpoServicesIndustriesLogisticsSupplyChainRoute
  OurBpoServicesIndustriesRealEstateRoute: typeof OurBpoServicesIndustriesRealEstateRoute
  OurBpoServicesIndustriesRetailRoute: typeof OurBpoServicesIndustriesRetailRoute
  OurBpoServicesIndustriesTechnologyRoute: typeof OurBpoServicesIndustriesTechnologyRoute
  OurBpoServicesIndustriesTelecommunicationsRoute: typeof OurBpoServicesIndustriesTelecommunicationsRoute
  OurBpoServicesSolutionAccountingAndCollectionsRoute: typeof OurBpoServicesSolutionAccountingAndCollectionsRoute
  OurBpoServicesSolutionBackOfficeProcessingRoute: typeof OurBpoServicesSolutionBackOfficeProcessingRoute
  OurBpoServicesSolutionClaimsProcessingRoute: typeof OurBpoServicesSolutionClaimsProcessingRoute
  OurBpoServicesSolutionCustomerRetentionRoute: typeof OurBpoServicesSolutionCustomerRetentionRoute
  OurBpoServicesSolutionDirectResponseMarketingRoute: typeof OurBpoServicesSolutionDirectResponseMarketingRoute
  OurBpoServicesSolutionFacilityAndProcurementRoute: typeof OurBpoServicesSolutionFacilityAndProcurementRoute
  OurBpoServicesSolutionInboundSalesRoute: typeof OurBpoServicesSolutionInboundSalesRoute
  OurBpoServicesSolutionInboundServicesRoute: typeof OurBpoServicesSolutionInboundServicesRoute
  OurBpoServicesSolutionLeadGenerationRoute: typeof OurBpoServicesSolutionLeadGenerationRoute
  OurBpoServicesSolutionOutboundServicesRoute: typeof OurBpoServicesSolutionOutboundServicesRoute
  OurBpoServicesSolutionPaymentProcessingRoute: typeof OurBpoServicesSolutionPaymentProcessingRoute
  OurBpoServicesSolutionTechnicalSupportRoute: typeof OurBpoServicesSolutionTechnicalSupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web-app-development': {
      id: '/services/web-app-development'
      path: '/services/web-app-development'
      fullPath: '/services/web-app-development'
      preLoaderRoute: typeof ServicesWebAppDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ux-ui-design': {
      id: '/services/ux-ui-design'
      path: '/services/ux-ui-design'
      fullPath: '/services/ux-ui-design'
      preLoaderRoute: typeof ServicesUxUiDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/qa-test-automation': {
      id: '/services/qa-test-automation'
      path: '/services/qa-test-automation'
      fullPath: '/services/qa-test-automation'
      preLoaderRoute: typeof ServicesQaTestAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/mvp': {
      id: '/services/mvp'
      path: '/services/mvp'
      fullPath: '/services/mvp'
      preLoaderRoute: typeof ServicesMvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/mobile-app-development': {
      id: '/services/mobile-app-development'
      path: '/services/mobile-app-development'
      fullPath: '/services/mobile-app-development'
      preLoaderRoute: typeof ServicesMobileAppDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/data-engineering': {
      id: '/services/data-engineering'
      path: '/services/data-engineering'
      fullPath: '/services/data-engineering'
      preLoaderRoute: typeof ServicesDataEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/cloud-engineering-devops': {
      id: '/services/cloud-engineering-devops'
      path: '/services/cloud-engineering-devops'
      fullPath: '/services/cloud-engineering-devops'
      preLoaderRoute: typeof ServicesCloudEngineeringDevopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/aws': {
      id: '/services/aws'
      path: '/services/aws'
      fullPath: '/services/aws'
      preLoaderRoute: typeof ServicesAwsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-agents': {
      id: '/services/ai-agents'
      path: '/services/ai-agents'
      fullPath: '/services/ai-agents'
      preLoaderRoute: typeof ServicesAiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/agentic-ai': {
      id: '/services/agentic-ai'
      path: '/services/agentic-ai'
      fullPath: '/services/agentic-ai'
      preLoaderRoute: typeof ServicesAgenticAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/solution/technical-support': {
      id: '/Our-Bpo-Services/solution/technical-support'
      path: '/Our-Bpo-Services/solution/technical-support'
      fullPath: '/Our-Bpo-Services/solution/technical-support'
      preLoaderRoute: typeof OurBpoServicesSolutionTechnicalSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/solution/payment-processing': {
      id: '/Our-Bpo-Services/solution/payment-processing'
      path: '/Our-Bpo-Services/solution/payment-processing'
      fullPath: '/Our-Bpo-Services/solution/payment-processing'
      preLoaderRoute: typeof OurBpoServicesSolutionPaymentProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/solution/outbound-services': {
      id: '/Our-Bpo-Services/solution/outbound-services'
      path: '/Our-Bpo-Services/solution/outbound-services'
      fullPath: '/Our-Bpo-Services/solution/outbound-services'
      preLoaderRoute: typeof OurBpoServicesSolutionOutboundServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/solution/lead-generation': {
      id: '/Our-Bpo-Services/solution/lead-generation'
      path: '/Our-Bpo-Services/solution/lead-generation'
      fullPath: '/Our-Bpo-Services/solution/lead-generation'
      preLoaderRoute: typeof OurBpoServicesSolutionLeadGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/solution/inbound-services': {
      id: '/Our-Bpo-Services/solution/inbound-services'
      path: '/Our-Bpo-Services/solution/inbound-services'
      fullPath: '/Our-Bpo-Services/solution/inbound-services'
      preLoaderRoute: typeof OurBpoServicesSolutionInboundServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/solution/inbound-sales': {
      id: '/Our-Bpo-Services/solution/inbound-sales'
      path: '/Our-Bpo-Services/solution/inbound-sales'
      fullPath: '/Our-Bpo-Services/solution/inbound-sales'
      preLoaderRoute: typeof OurBpoServicesSolutionInboundSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/solution/facility-and-procurement': {
      id: '/Our-Bpo-Services/solution/facility-and-procurement'
      path: '/Our-Bpo-Services/solution/facility-and-procurement'
      fullPath: '/Our-Bpo-Services/solution/facility-and-procurement'
      preLoaderRoute: typeof OurBpoServicesSolutionFacilityAndProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/solution/direct-response-marketing': {
      id: '/Our-Bpo-Services/solution/direct-response-marketing'
      path: '/Our-Bpo-Services/solution/direct-response-marketing'
      fullPath: '/Our-Bpo-Services/solution/direct-response-marketing'
      preLoaderRoute: typeof OurBpoServicesSolutionDirectResponseMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/solution/customer-retention': {
      id: '/Our-Bpo-Services/solution/customer-retention'
      path: '/Our-Bpo-Services/solution/customer-retention'
      fullPath: '/Our-Bpo-Services/solution/customer-retention'
      preLoaderRoute: typeof OurBpoServicesSolutionCustomerRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/solution/claims-processing': {
      id: '/Our-Bpo-Services/solution/claims-processing'
      path: '/Our-Bpo-Services/solution/claims-processing'
      fullPath: '/Our-Bpo-Services/solution/claims-processing'
      preLoaderRoute: typeof OurBpoServicesSolutionClaimsProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/solution/back-office-processing': {
      id: '/Our-Bpo-Services/solution/back-office-processing'
      path: '/Our-Bpo-Services/solution/back-office-processing'
      fullPath: '/Our-Bpo-Services/solution/back-office-processing'
      preLoaderRoute: typeof OurBpoServicesSolutionBackOfficeProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/solution/accounting-and-collections': {
      id: '/Our-Bpo-Services/solution/accounting-and-collections'
      path: '/Our-Bpo-Services/solution/accounting-and-collections'
      fullPath: '/Our-Bpo-Services/solution/accounting-and-collections'
      preLoaderRoute: typeof OurBpoServicesSolutionAccountingAndCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Industries/telecommunications': {
      id: '/Our-Bpo-Services/Industries/telecommunications'
      path: '/Our-Bpo-Services/Industries/telecommunications'
      fullPath: '/Our-Bpo-Services/Industries/telecommunications'
      preLoaderRoute: typeof OurBpoServicesIndustriesTelecommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Industries/technology': {
      id: '/Our-Bpo-Services/Industries/technology'
      path: '/Our-Bpo-Services/Industries/technology'
      fullPath: '/Our-Bpo-Services/Industries/technology'
      preLoaderRoute: typeof OurBpoServicesIndustriesTechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Industries/retail': {
      id: '/Our-Bpo-Services/Industries/retail'
      path: '/Our-Bpo-Services/Industries/retail'
      fullPath: '/Our-Bpo-Services/Industries/retail'
      preLoaderRoute: typeof OurBpoServicesIndustriesRetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Industries/real-estate': {
      id: '/Our-Bpo-Services/Industries/real-estate'
      path: '/Our-Bpo-Services/Industries/real-estate'
      fullPath: '/Our-Bpo-Services/Industries/real-estate'
      preLoaderRoute: typeof OurBpoServicesIndustriesRealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Industries/logistics-supply-chain': {
      id: '/Our-Bpo-Services/Industries/logistics-supply-chain'
      path: '/Our-Bpo-Services/Industries/logistics-supply-chain'
      fullPath: '/Our-Bpo-Services/Industries/logistics-supply-chain'
      preLoaderRoute: typeof OurBpoServicesIndustriesLogisticsSupplyChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Industries/insurance': {
      id: '/Our-Bpo-Services/Industries/insurance'
      path: '/Our-Bpo-Services/Industries/insurance'
      fullPath: '/Our-Bpo-Services/Industries/insurance'
      preLoaderRoute: typeof OurBpoServicesIndustriesInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Industries/healthcare': {
      id: '/Our-Bpo-Services/Industries/healthcare'
      path: '/Our-Bpo-Services/Industries/healthcare'
      fullPath: '/Our-Bpo-Services/Industries/healthcare'
      preLoaderRoute: typeof OurBpoServicesIndustriesHealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Industries/financial': {
      id: '/Our-Bpo-Services/Industries/financial'
      path: '/Our-Bpo-Services/Industries/financial'
      fullPath: '/Our-Bpo-Services/Industries/financial'
      preLoaderRoute: typeof OurBpoServicesIndustriesFinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Industries/entertainment': {
      id: '/Our-Bpo-Services/Industries/entertainment'
      path: '/Our-Bpo-Services/Industries/entertainment'
      fullPath: '/Our-Bpo-Services/Industries/entertainment'
      preLoaderRoute: typeof OurBpoServicesIndustriesEntertainmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactUsRoute: ContactUsRoute,
  ServicesAgenticAiRoute: ServicesAgenticAiRoute,
  ServicesAiAgentsRoute: ServicesAiAgentsRoute,
  ServicesAwsRoute: ServicesAwsRoute,
  ServicesCloudEngineeringDevopsRoute: ServicesCloudEngineeringDevopsRoute,
  ServicesDataEngineeringRoute: ServicesDataEngineeringRoute,
  ServicesMobileAppDevelopmentRoute: ServicesMobileAppDevelopmentRoute,
  ServicesMvpRoute: ServicesMvpRoute,
  ServicesQaTestAutomationRoute: ServicesQaTestAutomationRoute,
  ServicesUxUiDesignRoute: ServicesUxUiDesignRoute,
  ServicesWebAppDevelopmentRoute: ServicesWebAppDevelopmentRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  OurBpoServicesIndustriesEntertainmentRoute:
    OurBpoServicesIndustriesEntertainmentRoute,
  OurBpoServicesIndustriesFinancialRoute:
    OurBpoServicesIndustriesFinancialRoute,
  OurBpoServicesIndustriesHealthcareRoute:
    OurBpoServicesIndustriesHealthcareRoute,
  OurBpoServicesIndustriesInsuranceRoute:
    OurBpoServicesIndustriesInsuranceRoute,
  OurBpoServicesIndustriesLogisticsSupplyChainRoute:
    OurBpoServicesIndustriesLogisticsSupplyChainRoute,
  OurBpoServicesIndustriesRealEstateRoute:
    OurBpoServicesIndustriesRealEstateRoute,
  OurBpoServicesIndustriesRetailRoute: OurBpoServicesIndustriesRetailRoute,
  OurBpoServicesIndustriesTechnologyRoute:
    OurBpoServicesIndustriesTechnologyRoute,
  OurBpoServicesIndustriesTelecommunicationsRoute:
    OurBpoServicesIndustriesTelecommunicationsRoute,
  OurBpoServicesSolutionAccountingAndCollectionsRoute:
    OurBpoServicesSolutionAccountingAndCollectionsRoute,
  OurBpoServicesSolutionBackOfficeProcessingRoute:
    OurBpoServicesSolutionBackOfficeProcessingRoute,
  OurBpoServicesSolutionClaimsProcessingRoute:
    OurBpoServicesSolutionClaimsProcessingRoute,
  OurBpoServicesSolutionCustomerRetentionRoute:
    OurBpoServicesSolutionCustomerRetentionRoute,
  OurBpoServicesSolutionDirectResponseMarketingRoute:
    OurBpoServicesSolutionDirectResponseMarketingRoute,
  OurBpoServicesSolutionFacilityAndProcurementRoute:
    OurBpoServicesSolutionFacilityAndProcurementRoute,
  OurBpoServicesSolutionInboundSalesRoute:
    OurBpoServicesSolutionInboundSalesRoute,
  OurBpoServicesSolutionInboundServicesRoute:
    OurBpoServicesSolutionInboundServicesRoute,
  OurBpoServicesSolutionLeadGenerationRoute:
    OurBpoServicesSolutionLeadGenerationRoute,
  OurBpoServicesSolutionOutboundServicesRoute:
    OurBpoServicesSolutionOutboundServicesRoute,
  OurBpoServicesSolutionPaymentProcessingRoute:
    OurBpoServicesSolutionPaymentProcessingRoute,
  OurBpoServicesSolutionTechnicalSupportRoute:
    OurBpoServicesSolutionTechnicalSupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
