/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesWebAppDevelopmentRouteImport } from './routes/services/web-app-development'
import { Route as ServicesUxUiDesignRouteImport } from './routes/services/ux-ui-design'
import { Route as ServicesQaTestAutomationRouteImport } from './routes/services/qa-test-automation'
import { Route as ServicesMvpRouteImport } from './routes/services/mvp'
import { Route as ServicesMobileAppDevelopmentRouteImport } from './routes/services/mobile-app-development'
import { Route as ServicesDataEngineeringRouteImport } from './routes/services/data-engineering'
import { Route as ServicesCloudEngineeringDevopsRouteImport } from './routes/services/cloud-engineering-devops'
import { Route as ServicesAwsRouteImport } from './routes/services/aws'
import { Route as ServicesAiAgentsRouteImport } from './routes/services/ai-agents'
import { Route as ServicesAgenticAiRouteImport } from './routes/services/agentic-ai'
import { Route as OurBpoServicesSolutionsTechnical_supportRouteImport } from './routes/Our-Bpo-Services/Solutions/technical_support'
import { Route as OurBpoServicesSolutionsPayment_processingRouteImport } from './routes/Our-Bpo-Services/Solutions/payment_processing'
import { Route as OurBpoServicesSolutionsOutbound_servicesRouteImport } from './routes/Our-Bpo-Services/Solutions/outbound_services'
import { Route as OurBpoServicesSolutionsLead_generationRouteImport } from './routes/Our-Bpo-Services/Solutions/lead_generation'
import { Route as OurBpoServicesSolutionsInbound_servicesRouteImport } from './routes/Our-Bpo-Services/Solutions/inbound_services'
import { Route as OurBpoServicesSolutionsInbound_salesRouteImport } from './routes/Our-Bpo-Services/Solutions/inbound_sales'
import { Route as OurBpoServicesSolutionsFacility_and_procurementRouteImport } from './routes/Our-Bpo-Services/Solutions/facility_and_procurement'
import { Route as OurBpoServicesSolutionsDirect_response_marketingRouteImport } from './routes/Our-Bpo-Services/Solutions/direct_response_marketing'
import { Route as OurBpoServicesSolutionsCustomer_retentionRouteImport } from './routes/Our-Bpo-Services/Solutions/customer_retention'
import { Route as OurBpoServicesSolutionsClaims_processingRouteImport } from './routes/Our-Bpo-Services/Solutions/claims_processing'
import { Route as OurBpoServicesSolutionsBack_office_processingRouteImport } from './routes/Our-Bpo-Services/Solutions/back_office_processing'
import { Route as OurBpoServicesSolutionsAccounting_and_collectionsRouteImport } from './routes/Our-Bpo-Services/Solutions/accounting_and_collections'
import { Route as OurBpoServicesIndustriesTelecommunicationsRouteImport } from './routes/Our-Bpo-Services/Industries/telecommunications'
import { Route as OurBpoServicesIndustriesTechnologyRouteImport } from './routes/Our-Bpo-Services/Industries/technology'
import { Route as OurBpoServicesIndustriesRetailRouteImport } from './routes/Our-Bpo-Services/Industries/retail'
import { Route as OurBpoServicesIndustriesReal_estateRouteImport } from './routes/Our-Bpo-Services/Industries/real_estate'
import { Route as OurBpoServicesIndustriesLogistics_supply_chainRouteImport } from './routes/Our-Bpo-Services/Industries/logistics_supply_chain'
import { Route as OurBpoServicesIndustriesInsuranceRouteImport } from './routes/Our-Bpo-Services/Industries/insurance'
import { Route as OurBpoServicesIndustriesHealthcareRouteImport } from './routes/Our-Bpo-Services/Industries/healthcare'
import { Route as OurBpoServicesIndustriesFinancialRouteImport } from './routes/Our-Bpo-Services/Industries/financial'
import { Route as OurBpoServicesIndustriesEntertainmentRouteImport } from './routes/Our-Bpo-Services/Industries/entertainment'

const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebAppDevelopmentRoute =
  ServicesWebAppDevelopmentRouteImport.update({
    id: '/services/web-app-development',
    path: '/services/web-app-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesUxUiDesignRoute = ServicesUxUiDesignRouteImport.update({
  id: '/services/ux-ui-design',
  path: '/services/ux-ui-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesQaTestAutomationRoute =
  ServicesQaTestAutomationRouteImport.update({
    id: '/services/qa-test-automation',
    path: '/services/qa-test-automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesMvpRoute = ServicesMvpRouteImport.update({
  id: '/services/mvp',
  path: '/services/mvp',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMobileAppDevelopmentRoute =
  ServicesMobileAppDevelopmentRouteImport.update({
    id: '/services/mobile-app-development',
    path: '/services/mobile-app-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesDataEngineeringRoute = ServicesDataEngineeringRouteImport.update({
  id: '/services/data-engineering',
  path: '/services/data-engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCloudEngineeringDevopsRoute =
  ServicesCloudEngineeringDevopsRouteImport.update({
    id: '/services/cloud-engineering-devops',
    path: '/services/cloud-engineering-devops',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAwsRoute = ServicesAwsRouteImport.update({
  id: '/services/aws',
  path: '/services/aws',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiAgentsRoute = ServicesAiAgentsRouteImport.update({
  id: '/services/ai-agents',
  path: '/services/ai-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAgenticAiRoute = ServicesAgenticAiRouteImport.update({
  id: '/services/agentic-ai',
  path: '/services/agentic-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const OurBpoServicesSolutionsTechnical_supportRoute =
  OurBpoServicesSolutionsTechnical_supportRouteImport.update({
    id: '/Our-Bpo-Services/Solutions/technical_support',
    path: '/Our-Bpo-Services/Solutions/technical_support',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesSolutionsPayment_processingRoute =
  OurBpoServicesSolutionsPayment_processingRouteImport.update({
    id: '/Our-Bpo-Services/Solutions/payment_processing',
    path: '/Our-Bpo-Services/Solutions/payment_processing',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesSolutionsOutbound_servicesRoute =
  OurBpoServicesSolutionsOutbound_servicesRouteImport.update({
    id: '/Our-Bpo-Services/Solutions/outbound_services',
    path: '/Our-Bpo-Services/Solutions/outbound_services',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesSolutionsLead_generationRoute =
  OurBpoServicesSolutionsLead_generationRouteImport.update({
    id: '/Our-Bpo-Services/Solutions/lead_generation',
    path: '/Our-Bpo-Services/Solutions/lead_generation',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesSolutionsInbound_servicesRoute =
  OurBpoServicesSolutionsInbound_servicesRouteImport.update({
    id: '/Our-Bpo-Services/Solutions/inbound_services',
    path: '/Our-Bpo-Services/Solutions/inbound_services',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesSolutionsInbound_salesRoute =
  OurBpoServicesSolutionsInbound_salesRouteImport.update({
    id: '/Our-Bpo-Services/Solutions/inbound_sales',
    path: '/Our-Bpo-Services/Solutions/inbound_sales',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesSolutionsFacility_and_procurementRoute =
  OurBpoServicesSolutionsFacility_and_procurementRouteImport.update({
    id: '/Our-Bpo-Services/Solutions/facility_and_procurement',
    path: '/Our-Bpo-Services/Solutions/facility_and_procurement',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesSolutionsDirect_response_marketingRoute =
  OurBpoServicesSolutionsDirect_response_marketingRouteImport.update({
    id: '/Our-Bpo-Services/Solutions/direct_response_marketing',
    path: '/Our-Bpo-Services/Solutions/direct_response_marketing',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesSolutionsCustomer_retentionRoute =
  OurBpoServicesSolutionsCustomer_retentionRouteImport.update({
    id: '/Our-Bpo-Services/Solutions/customer_retention',
    path: '/Our-Bpo-Services/Solutions/customer_retention',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesSolutionsClaims_processingRoute =
  OurBpoServicesSolutionsClaims_processingRouteImport.update({
    id: '/Our-Bpo-Services/Solutions/claims_processing',
    path: '/Our-Bpo-Services/Solutions/claims_processing',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesSolutionsBack_office_processingRoute =
  OurBpoServicesSolutionsBack_office_processingRouteImport.update({
    id: '/Our-Bpo-Services/Solutions/back_office_processing',
    path: '/Our-Bpo-Services/Solutions/back_office_processing',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesSolutionsAccounting_and_collectionsRoute =
  OurBpoServicesSolutionsAccounting_and_collectionsRouteImport.update({
    id: '/Our-Bpo-Services/Solutions/accounting_and_collections',
    path: '/Our-Bpo-Services/Solutions/accounting_and_collections',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesIndustriesTelecommunicationsRoute =
  OurBpoServicesIndustriesTelecommunicationsRouteImport.update({
    id: '/Our-Bpo-Services/Industries/telecommunications',
    path: '/Our-Bpo-Services/Industries/telecommunications',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesIndustriesTechnologyRoute =
  OurBpoServicesIndustriesTechnologyRouteImport.update({
    id: '/Our-Bpo-Services/Industries/technology',
    path: '/Our-Bpo-Services/Industries/technology',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesIndustriesRetailRoute =
  OurBpoServicesIndustriesRetailRouteImport.update({
    id: '/Our-Bpo-Services/Industries/retail',
    path: '/Our-Bpo-Services/Industries/retail',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesIndustriesReal_estateRoute =
  OurBpoServicesIndustriesReal_estateRouteImport.update({
    id: '/Our-Bpo-Services/Industries/real_estate',
    path: '/Our-Bpo-Services/Industries/real_estate',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesIndustriesLogistics_supply_chainRoute =
  OurBpoServicesIndustriesLogistics_supply_chainRouteImport.update({
    id: '/Our-Bpo-Services/Industries/logistics_supply_chain',
    path: '/Our-Bpo-Services/Industries/logistics_supply_chain',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesIndustriesInsuranceRoute =
  OurBpoServicesIndustriesInsuranceRouteImport.update({
    id: '/Our-Bpo-Services/Industries/insurance',
    path: '/Our-Bpo-Services/Industries/insurance',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesIndustriesHealthcareRoute =
  OurBpoServicesIndustriesHealthcareRouteImport.update({
    id: '/Our-Bpo-Services/Industries/healthcare',
    path: '/Our-Bpo-Services/Industries/healthcare',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesIndustriesFinancialRoute =
  OurBpoServicesIndustriesFinancialRouteImport.update({
    id: '/Our-Bpo-Services/Industries/financial',
    path: '/Our-Bpo-Services/Industries/financial',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurBpoServicesIndustriesEntertainmentRoute =
  OurBpoServicesIndustriesEntertainmentRouteImport.update({
    id: '/Our-Bpo-Services/Industries/entertainment',
    path: '/Our-Bpo-Services/Industries/entertainment',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/services/agentic-ai': typeof ServicesAgenticAiRoute
  '/services/ai-agents': typeof ServicesAiAgentsRoute
  '/services/aws': typeof ServicesAwsRoute
  '/services/cloud-engineering-devops': typeof ServicesCloudEngineeringDevopsRoute
  '/services/data-engineering': typeof ServicesDataEngineeringRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/mvp': typeof ServicesMvpRoute
  '/services/qa-test-automation': typeof ServicesQaTestAutomationRoute
  '/services/ux-ui-design': typeof ServicesUxUiDesignRoute
  '/services/web-app-development': typeof ServicesWebAppDevelopmentRoute
  '/services/': typeof ServicesIndexRoute
  '/Our-Bpo-Services/Industries/entertainment': typeof OurBpoServicesIndustriesEntertainmentRoute
  '/Our-Bpo-Services/Industries/financial': typeof OurBpoServicesIndustriesFinancialRoute
  '/Our-Bpo-Services/Industries/healthcare': typeof OurBpoServicesIndustriesHealthcareRoute
  '/Our-Bpo-Services/Industries/insurance': typeof OurBpoServicesIndustriesInsuranceRoute
  '/Our-Bpo-Services/Industries/logistics_supply_chain': typeof OurBpoServicesIndustriesLogistics_supply_chainRoute
  '/Our-Bpo-Services/Industries/real_estate': typeof OurBpoServicesIndustriesReal_estateRoute
  '/Our-Bpo-Services/Industries/retail': typeof OurBpoServicesIndustriesRetailRoute
  '/Our-Bpo-Services/Industries/technology': typeof OurBpoServicesIndustriesTechnologyRoute
  '/Our-Bpo-Services/Industries/telecommunications': typeof OurBpoServicesIndustriesTelecommunicationsRoute
  '/Our-Bpo-Services/Solutions/accounting_and_collections': typeof OurBpoServicesSolutionsAccounting_and_collectionsRoute
  '/Our-Bpo-Services/Solutions/back_office_processing': typeof OurBpoServicesSolutionsBack_office_processingRoute
  '/Our-Bpo-Services/Solutions/claims_processing': typeof OurBpoServicesSolutionsClaims_processingRoute
  '/Our-Bpo-Services/Solutions/customer_retention': typeof OurBpoServicesSolutionsCustomer_retentionRoute
  '/Our-Bpo-Services/Solutions/direct_response_marketing': typeof OurBpoServicesSolutionsDirect_response_marketingRoute
  '/Our-Bpo-Services/Solutions/facility_and_procurement': typeof OurBpoServicesSolutionsFacility_and_procurementRoute
  '/Our-Bpo-Services/Solutions/inbound_sales': typeof OurBpoServicesSolutionsInbound_salesRoute
  '/Our-Bpo-Services/Solutions/inbound_services': typeof OurBpoServicesSolutionsInbound_servicesRoute
  '/Our-Bpo-Services/Solutions/lead_generation': typeof OurBpoServicesSolutionsLead_generationRoute
  '/Our-Bpo-Services/Solutions/outbound_services': typeof OurBpoServicesSolutionsOutbound_servicesRoute
  '/Our-Bpo-Services/Solutions/payment_processing': typeof OurBpoServicesSolutionsPayment_processingRoute
  '/Our-Bpo-Services/Solutions/technical_support': typeof OurBpoServicesSolutionsTechnical_supportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/services/agentic-ai': typeof ServicesAgenticAiRoute
  '/services/ai-agents': typeof ServicesAiAgentsRoute
  '/services/aws': typeof ServicesAwsRoute
  '/services/cloud-engineering-devops': typeof ServicesCloudEngineeringDevopsRoute
  '/services/data-engineering': typeof ServicesDataEngineeringRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/mvp': typeof ServicesMvpRoute
  '/services/qa-test-automation': typeof ServicesQaTestAutomationRoute
  '/services/ux-ui-design': typeof ServicesUxUiDesignRoute
  '/services/web-app-development': typeof ServicesWebAppDevelopmentRoute
  '/services': typeof ServicesIndexRoute
  '/Our-Bpo-Services/Industries/entertainment': typeof OurBpoServicesIndustriesEntertainmentRoute
  '/Our-Bpo-Services/Industries/financial': typeof OurBpoServicesIndustriesFinancialRoute
  '/Our-Bpo-Services/Industries/healthcare': typeof OurBpoServicesIndustriesHealthcareRoute
  '/Our-Bpo-Services/Industries/insurance': typeof OurBpoServicesIndustriesInsuranceRoute
  '/Our-Bpo-Services/Industries/logistics_supply_chain': typeof OurBpoServicesIndustriesLogistics_supply_chainRoute
  '/Our-Bpo-Services/Industries/real_estate': typeof OurBpoServicesIndustriesReal_estateRoute
  '/Our-Bpo-Services/Industries/retail': typeof OurBpoServicesIndustriesRetailRoute
  '/Our-Bpo-Services/Industries/technology': typeof OurBpoServicesIndustriesTechnologyRoute
  '/Our-Bpo-Services/Industries/telecommunications': typeof OurBpoServicesIndustriesTelecommunicationsRoute
  '/Our-Bpo-Services/Solutions/accounting_and_collections': typeof OurBpoServicesSolutionsAccounting_and_collectionsRoute
  '/Our-Bpo-Services/Solutions/back_office_processing': typeof OurBpoServicesSolutionsBack_office_processingRoute
  '/Our-Bpo-Services/Solutions/claims_processing': typeof OurBpoServicesSolutionsClaims_processingRoute
  '/Our-Bpo-Services/Solutions/customer_retention': typeof OurBpoServicesSolutionsCustomer_retentionRoute
  '/Our-Bpo-Services/Solutions/direct_response_marketing': typeof OurBpoServicesSolutionsDirect_response_marketingRoute
  '/Our-Bpo-Services/Solutions/facility_and_procurement': typeof OurBpoServicesSolutionsFacility_and_procurementRoute
  '/Our-Bpo-Services/Solutions/inbound_sales': typeof OurBpoServicesSolutionsInbound_salesRoute
  '/Our-Bpo-Services/Solutions/inbound_services': typeof OurBpoServicesSolutionsInbound_servicesRoute
  '/Our-Bpo-Services/Solutions/lead_generation': typeof OurBpoServicesSolutionsLead_generationRoute
  '/Our-Bpo-Services/Solutions/outbound_services': typeof OurBpoServicesSolutionsOutbound_servicesRoute
  '/Our-Bpo-Services/Solutions/payment_processing': typeof OurBpoServicesSolutionsPayment_processingRoute
  '/Our-Bpo-Services/Solutions/technical_support': typeof OurBpoServicesSolutionsTechnical_supportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/services/agentic-ai': typeof ServicesAgenticAiRoute
  '/services/ai-agents': typeof ServicesAiAgentsRoute
  '/services/aws': typeof ServicesAwsRoute
  '/services/cloud-engineering-devops': typeof ServicesCloudEngineeringDevopsRoute
  '/services/data-engineering': typeof ServicesDataEngineeringRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/mvp': typeof ServicesMvpRoute
  '/services/qa-test-automation': typeof ServicesQaTestAutomationRoute
  '/services/ux-ui-design': typeof ServicesUxUiDesignRoute
  '/services/web-app-development': typeof ServicesWebAppDevelopmentRoute
  '/services/': typeof ServicesIndexRoute
  '/Our-Bpo-Services/Industries/entertainment': typeof OurBpoServicesIndustriesEntertainmentRoute
  '/Our-Bpo-Services/Industries/financial': typeof OurBpoServicesIndustriesFinancialRoute
  '/Our-Bpo-Services/Industries/healthcare': typeof OurBpoServicesIndustriesHealthcareRoute
  '/Our-Bpo-Services/Industries/insurance': typeof OurBpoServicesIndustriesInsuranceRoute
  '/Our-Bpo-Services/Industries/logistics_supply_chain': typeof OurBpoServicesIndustriesLogistics_supply_chainRoute
  '/Our-Bpo-Services/Industries/real_estate': typeof OurBpoServicesIndustriesReal_estateRoute
  '/Our-Bpo-Services/Industries/retail': typeof OurBpoServicesIndustriesRetailRoute
  '/Our-Bpo-Services/Industries/technology': typeof OurBpoServicesIndustriesTechnologyRoute
  '/Our-Bpo-Services/Industries/telecommunications': typeof OurBpoServicesIndustriesTelecommunicationsRoute
  '/Our-Bpo-Services/Solutions/accounting_and_collections': typeof OurBpoServicesSolutionsAccounting_and_collectionsRoute
  '/Our-Bpo-Services/Solutions/back_office_processing': typeof OurBpoServicesSolutionsBack_office_processingRoute
  '/Our-Bpo-Services/Solutions/claims_processing': typeof OurBpoServicesSolutionsClaims_processingRoute
  '/Our-Bpo-Services/Solutions/customer_retention': typeof OurBpoServicesSolutionsCustomer_retentionRoute
  '/Our-Bpo-Services/Solutions/direct_response_marketing': typeof OurBpoServicesSolutionsDirect_response_marketingRoute
  '/Our-Bpo-Services/Solutions/facility_and_procurement': typeof OurBpoServicesSolutionsFacility_and_procurementRoute
  '/Our-Bpo-Services/Solutions/inbound_sales': typeof OurBpoServicesSolutionsInbound_salesRoute
  '/Our-Bpo-Services/Solutions/inbound_services': typeof OurBpoServicesSolutionsInbound_servicesRoute
  '/Our-Bpo-Services/Solutions/lead_generation': typeof OurBpoServicesSolutionsLead_generationRoute
  '/Our-Bpo-Services/Solutions/outbound_services': typeof OurBpoServicesSolutionsOutbound_servicesRoute
  '/Our-Bpo-Services/Solutions/payment_processing': typeof OurBpoServicesSolutionsPayment_processingRoute
  '/Our-Bpo-Services/Solutions/technical_support': typeof OurBpoServicesSolutionsTechnical_supportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact-us'
    | '/services/agentic-ai'
    | '/services/ai-agents'
    | '/services/aws'
    | '/services/cloud-engineering-devops'
    | '/services/data-engineering'
    | '/services/mobile-app-development'
    | '/services/mvp'
    | '/services/qa-test-automation'
    | '/services/ux-ui-design'
    | '/services/web-app-development'
    | '/services/'
    | '/Our-Bpo-Services/Industries/entertainment'
    | '/Our-Bpo-Services/Industries/financial'
    | '/Our-Bpo-Services/Industries/healthcare'
    | '/Our-Bpo-Services/Industries/insurance'
    | '/Our-Bpo-Services/Industries/logistics_supply_chain'
    | '/Our-Bpo-Services/Industries/real_estate'
    | '/Our-Bpo-Services/Industries/retail'
    | '/Our-Bpo-Services/Industries/technology'
    | '/Our-Bpo-Services/Industries/telecommunications'
    | '/Our-Bpo-Services/Solutions/accounting_and_collections'
    | '/Our-Bpo-Services/Solutions/back_office_processing'
    | '/Our-Bpo-Services/Solutions/claims_processing'
    | '/Our-Bpo-Services/Solutions/customer_retention'
    | '/Our-Bpo-Services/Solutions/direct_response_marketing'
    | '/Our-Bpo-Services/Solutions/facility_and_procurement'
    | '/Our-Bpo-Services/Solutions/inbound_sales'
    | '/Our-Bpo-Services/Solutions/inbound_services'
    | '/Our-Bpo-Services/Solutions/lead_generation'
    | '/Our-Bpo-Services/Solutions/outbound_services'
    | '/Our-Bpo-Services/Solutions/payment_processing'
    | '/Our-Bpo-Services/Solutions/technical_support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact-us'
    | '/services/agentic-ai'
    | '/services/ai-agents'
    | '/services/aws'
    | '/services/cloud-engineering-devops'
    | '/services/data-engineering'
    | '/services/mobile-app-development'
    | '/services/mvp'
    | '/services/qa-test-automation'
    | '/services/ux-ui-design'
    | '/services/web-app-development'
    | '/services'
    | '/Our-Bpo-Services/Industries/entertainment'
    | '/Our-Bpo-Services/Industries/financial'
    | '/Our-Bpo-Services/Industries/healthcare'
    | '/Our-Bpo-Services/Industries/insurance'
    | '/Our-Bpo-Services/Industries/logistics_supply_chain'
    | '/Our-Bpo-Services/Industries/real_estate'
    | '/Our-Bpo-Services/Industries/retail'
    | '/Our-Bpo-Services/Industries/technology'
    | '/Our-Bpo-Services/Industries/telecommunications'
    | '/Our-Bpo-Services/Solutions/accounting_and_collections'
    | '/Our-Bpo-Services/Solutions/back_office_processing'
    | '/Our-Bpo-Services/Solutions/claims_processing'
    | '/Our-Bpo-Services/Solutions/customer_retention'
    | '/Our-Bpo-Services/Solutions/direct_response_marketing'
    | '/Our-Bpo-Services/Solutions/facility_and_procurement'
    | '/Our-Bpo-Services/Solutions/inbound_sales'
    | '/Our-Bpo-Services/Solutions/inbound_services'
    | '/Our-Bpo-Services/Solutions/lead_generation'
    | '/Our-Bpo-Services/Solutions/outbound_services'
    | '/Our-Bpo-Services/Solutions/payment_processing'
    | '/Our-Bpo-Services/Solutions/technical_support'
  id:
    | '__root__'
    | '/'
    | '/contact-us'
    | '/services/agentic-ai'
    | '/services/ai-agents'
    | '/services/aws'
    | '/services/cloud-engineering-devops'
    | '/services/data-engineering'
    | '/services/mobile-app-development'
    | '/services/mvp'
    | '/services/qa-test-automation'
    | '/services/ux-ui-design'
    | '/services/web-app-development'
    | '/services/'
    | '/Our-Bpo-Services/Industries/entertainment'
    | '/Our-Bpo-Services/Industries/financial'
    | '/Our-Bpo-Services/Industries/healthcare'
    | '/Our-Bpo-Services/Industries/insurance'
    | '/Our-Bpo-Services/Industries/logistics_supply_chain'
    | '/Our-Bpo-Services/Industries/real_estate'
    | '/Our-Bpo-Services/Industries/retail'
    | '/Our-Bpo-Services/Industries/technology'
    | '/Our-Bpo-Services/Industries/telecommunications'
    | '/Our-Bpo-Services/Solutions/accounting_and_collections'
    | '/Our-Bpo-Services/Solutions/back_office_processing'
    | '/Our-Bpo-Services/Solutions/claims_processing'
    | '/Our-Bpo-Services/Solutions/customer_retention'
    | '/Our-Bpo-Services/Solutions/direct_response_marketing'
    | '/Our-Bpo-Services/Solutions/facility_and_procurement'
    | '/Our-Bpo-Services/Solutions/inbound_sales'
    | '/Our-Bpo-Services/Solutions/inbound_services'
    | '/Our-Bpo-Services/Solutions/lead_generation'
    | '/Our-Bpo-Services/Solutions/outbound_services'
    | '/Our-Bpo-Services/Solutions/payment_processing'
    | '/Our-Bpo-Services/Solutions/technical_support'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactUsRoute: typeof ContactUsRoute
  ServicesAgenticAiRoute: typeof ServicesAgenticAiRoute
  ServicesAiAgentsRoute: typeof ServicesAiAgentsRoute
  ServicesAwsRoute: typeof ServicesAwsRoute
  ServicesCloudEngineeringDevopsRoute: typeof ServicesCloudEngineeringDevopsRoute
  ServicesDataEngineeringRoute: typeof ServicesDataEngineeringRoute
  ServicesMobileAppDevelopmentRoute: typeof ServicesMobileAppDevelopmentRoute
  ServicesMvpRoute: typeof ServicesMvpRoute
  ServicesQaTestAutomationRoute: typeof ServicesQaTestAutomationRoute
  ServicesUxUiDesignRoute: typeof ServicesUxUiDesignRoute
  ServicesWebAppDevelopmentRoute: typeof ServicesWebAppDevelopmentRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  OurBpoServicesIndustriesEntertainmentRoute: typeof OurBpoServicesIndustriesEntertainmentRoute
  OurBpoServicesIndustriesFinancialRoute: typeof OurBpoServicesIndustriesFinancialRoute
  OurBpoServicesIndustriesHealthcareRoute: typeof OurBpoServicesIndustriesHealthcareRoute
  OurBpoServicesIndustriesInsuranceRoute: typeof OurBpoServicesIndustriesInsuranceRoute
  OurBpoServicesIndustriesLogistics_supply_chainRoute: typeof OurBpoServicesIndustriesLogistics_supply_chainRoute
  OurBpoServicesIndustriesReal_estateRoute: typeof OurBpoServicesIndustriesReal_estateRoute
  OurBpoServicesIndustriesRetailRoute: typeof OurBpoServicesIndustriesRetailRoute
  OurBpoServicesIndustriesTechnologyRoute: typeof OurBpoServicesIndustriesTechnologyRoute
  OurBpoServicesIndustriesTelecommunicationsRoute: typeof OurBpoServicesIndustriesTelecommunicationsRoute
  OurBpoServicesSolutionsAccounting_and_collectionsRoute: typeof OurBpoServicesSolutionsAccounting_and_collectionsRoute
  OurBpoServicesSolutionsBack_office_processingRoute: typeof OurBpoServicesSolutionsBack_office_processingRoute
  OurBpoServicesSolutionsClaims_processingRoute: typeof OurBpoServicesSolutionsClaims_processingRoute
  OurBpoServicesSolutionsCustomer_retentionRoute: typeof OurBpoServicesSolutionsCustomer_retentionRoute
  OurBpoServicesSolutionsDirect_response_marketingRoute: typeof OurBpoServicesSolutionsDirect_response_marketingRoute
  OurBpoServicesSolutionsFacility_and_procurementRoute: typeof OurBpoServicesSolutionsFacility_and_procurementRoute
  OurBpoServicesSolutionsInbound_salesRoute: typeof OurBpoServicesSolutionsInbound_salesRoute
  OurBpoServicesSolutionsInbound_servicesRoute: typeof OurBpoServicesSolutionsInbound_servicesRoute
  OurBpoServicesSolutionsLead_generationRoute: typeof OurBpoServicesSolutionsLead_generationRoute
  OurBpoServicesSolutionsOutbound_servicesRoute: typeof OurBpoServicesSolutionsOutbound_servicesRoute
  OurBpoServicesSolutionsPayment_processingRoute: typeof OurBpoServicesSolutionsPayment_processingRoute
  OurBpoServicesSolutionsTechnical_supportRoute: typeof OurBpoServicesSolutionsTechnical_supportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web-app-development': {
      id: '/services/web-app-development'
      path: '/services/web-app-development'
      fullPath: '/services/web-app-development'
      preLoaderRoute: typeof ServicesWebAppDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ux-ui-design': {
      id: '/services/ux-ui-design'
      path: '/services/ux-ui-design'
      fullPath: '/services/ux-ui-design'
      preLoaderRoute: typeof ServicesUxUiDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/qa-test-automation': {
      id: '/services/qa-test-automation'
      path: '/services/qa-test-automation'
      fullPath: '/services/qa-test-automation'
      preLoaderRoute: typeof ServicesQaTestAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/mvp': {
      id: '/services/mvp'
      path: '/services/mvp'
      fullPath: '/services/mvp'
      preLoaderRoute: typeof ServicesMvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/mobile-app-development': {
      id: '/services/mobile-app-development'
      path: '/services/mobile-app-development'
      fullPath: '/services/mobile-app-development'
      preLoaderRoute: typeof ServicesMobileAppDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/data-engineering': {
      id: '/services/data-engineering'
      path: '/services/data-engineering'
      fullPath: '/services/data-engineering'
      preLoaderRoute: typeof ServicesDataEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/cloud-engineering-devops': {
      id: '/services/cloud-engineering-devops'
      path: '/services/cloud-engineering-devops'
      fullPath: '/services/cloud-engineering-devops'
      preLoaderRoute: typeof ServicesCloudEngineeringDevopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/aws': {
      id: '/services/aws'
      path: '/services/aws'
      fullPath: '/services/aws'
      preLoaderRoute: typeof ServicesAwsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-agents': {
      id: '/services/ai-agents'
      path: '/services/ai-agents'
      fullPath: '/services/ai-agents'
      preLoaderRoute: typeof ServicesAiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/agentic-ai': {
      id: '/services/agentic-ai'
      path: '/services/agentic-ai'
      fullPath: '/services/agentic-ai'
      preLoaderRoute: typeof ServicesAgenticAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Solutions/technical_support': {
      id: '/Our-Bpo-Services/Solutions/technical_support'
      path: '/Our-Bpo-Services/Solutions/technical_support'
      fullPath: '/Our-Bpo-Services/Solutions/technical_support'
      preLoaderRoute: typeof OurBpoServicesSolutionsTechnical_supportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Solutions/payment_processing': {
      id: '/Our-Bpo-Services/Solutions/payment_processing'
      path: '/Our-Bpo-Services/Solutions/payment_processing'
      fullPath: '/Our-Bpo-Services/Solutions/payment_processing'
      preLoaderRoute: typeof OurBpoServicesSolutionsPayment_processingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Solutions/outbound_services': {
      id: '/Our-Bpo-Services/Solutions/outbound_services'
      path: '/Our-Bpo-Services/Solutions/outbound_services'
      fullPath: '/Our-Bpo-Services/Solutions/outbound_services'
      preLoaderRoute: typeof OurBpoServicesSolutionsOutbound_servicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Solutions/lead_generation': {
      id: '/Our-Bpo-Services/Solutions/lead_generation'
      path: '/Our-Bpo-Services/Solutions/lead_generation'
      fullPath: '/Our-Bpo-Services/Solutions/lead_generation'
      preLoaderRoute: typeof OurBpoServicesSolutionsLead_generationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Solutions/inbound_services': {
      id: '/Our-Bpo-Services/Solutions/inbound_services'
      path: '/Our-Bpo-Services/Solutions/inbound_services'
      fullPath: '/Our-Bpo-Services/Solutions/inbound_services'
      preLoaderRoute: typeof OurBpoServicesSolutionsInbound_servicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Solutions/inbound_sales': {
      id: '/Our-Bpo-Services/Solutions/inbound_sales'
      path: '/Our-Bpo-Services/Solutions/inbound_sales'
      fullPath: '/Our-Bpo-Services/Solutions/inbound_sales'
      preLoaderRoute: typeof OurBpoServicesSolutionsInbound_salesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Solutions/facility_and_procurement': {
      id: '/Our-Bpo-Services/Solutions/facility_and_procurement'
      path: '/Our-Bpo-Services/Solutions/facility_and_procurement'
      fullPath: '/Our-Bpo-Services/Solutions/facility_and_procurement'
      preLoaderRoute: typeof OurBpoServicesSolutionsFacility_and_procurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Solutions/direct_response_marketing': {
      id: '/Our-Bpo-Services/Solutions/direct_response_marketing'
      path: '/Our-Bpo-Services/Solutions/direct_response_marketing'
      fullPath: '/Our-Bpo-Services/Solutions/direct_response_marketing'
      preLoaderRoute: typeof OurBpoServicesSolutionsDirect_response_marketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Solutions/customer_retention': {
      id: '/Our-Bpo-Services/Solutions/customer_retention'
      path: '/Our-Bpo-Services/Solutions/customer_retention'
      fullPath: '/Our-Bpo-Services/Solutions/customer_retention'
      preLoaderRoute: typeof OurBpoServicesSolutionsCustomer_retentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Solutions/claims_processing': {
      id: '/Our-Bpo-Services/Solutions/claims_processing'
      path: '/Our-Bpo-Services/Solutions/claims_processing'
      fullPath: '/Our-Bpo-Services/Solutions/claims_processing'
      preLoaderRoute: typeof OurBpoServicesSolutionsClaims_processingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Solutions/back_office_processing': {
      id: '/Our-Bpo-Services/Solutions/back_office_processing'
      path: '/Our-Bpo-Services/Solutions/back_office_processing'
      fullPath: '/Our-Bpo-Services/Solutions/back_office_processing'
      preLoaderRoute: typeof OurBpoServicesSolutionsBack_office_processingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Solutions/accounting_and_collections': {
      id: '/Our-Bpo-Services/Solutions/accounting_and_collections'
      path: '/Our-Bpo-Services/Solutions/accounting_and_collections'
      fullPath: '/Our-Bpo-Services/Solutions/accounting_and_collections'
      preLoaderRoute: typeof OurBpoServicesSolutionsAccounting_and_collectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Industries/telecommunications': {
      id: '/Our-Bpo-Services/Industries/telecommunications'
      path: '/Our-Bpo-Services/Industries/telecommunications'
      fullPath: '/Our-Bpo-Services/Industries/telecommunications'
      preLoaderRoute: typeof OurBpoServicesIndustriesTelecommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Industries/technology': {
      id: '/Our-Bpo-Services/Industries/technology'
      path: '/Our-Bpo-Services/Industries/technology'
      fullPath: '/Our-Bpo-Services/Industries/technology'
      preLoaderRoute: typeof OurBpoServicesIndustriesTechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Industries/retail': {
      id: '/Our-Bpo-Services/Industries/retail'
      path: '/Our-Bpo-Services/Industries/retail'
      fullPath: '/Our-Bpo-Services/Industries/retail'
      preLoaderRoute: typeof OurBpoServicesIndustriesRetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Industries/real_estate': {
      id: '/Our-Bpo-Services/Industries/real_estate'
      path: '/Our-Bpo-Services/Industries/real_estate'
      fullPath: '/Our-Bpo-Services/Industries/real_estate'
      preLoaderRoute: typeof OurBpoServicesIndustriesReal_estateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Industries/logistics_supply_chain': {
      id: '/Our-Bpo-Services/Industries/logistics_supply_chain'
      path: '/Our-Bpo-Services/Industries/logistics_supply_chain'
      fullPath: '/Our-Bpo-Services/Industries/logistics_supply_chain'
      preLoaderRoute: typeof OurBpoServicesIndustriesLogistics_supply_chainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Industries/insurance': {
      id: '/Our-Bpo-Services/Industries/insurance'
      path: '/Our-Bpo-Services/Industries/insurance'
      fullPath: '/Our-Bpo-Services/Industries/insurance'
      preLoaderRoute: typeof OurBpoServicesIndustriesInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Industries/healthcare': {
      id: '/Our-Bpo-Services/Industries/healthcare'
      path: '/Our-Bpo-Services/Industries/healthcare'
      fullPath: '/Our-Bpo-Services/Industries/healthcare'
      preLoaderRoute: typeof OurBpoServicesIndustriesHealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Industries/financial': {
      id: '/Our-Bpo-Services/Industries/financial'
      path: '/Our-Bpo-Services/Industries/financial'
      fullPath: '/Our-Bpo-Services/Industries/financial'
      preLoaderRoute: typeof OurBpoServicesIndustriesFinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Our-Bpo-Services/Industries/entertainment': {
      id: '/Our-Bpo-Services/Industries/entertainment'
      path: '/Our-Bpo-Services/Industries/entertainment'
      fullPath: '/Our-Bpo-Services/Industries/entertainment'
      preLoaderRoute: typeof OurBpoServicesIndustriesEntertainmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactUsRoute: ContactUsRoute,
  ServicesAgenticAiRoute: ServicesAgenticAiRoute,
  ServicesAiAgentsRoute: ServicesAiAgentsRoute,
  ServicesAwsRoute: ServicesAwsRoute,
  ServicesCloudEngineeringDevopsRoute: ServicesCloudEngineeringDevopsRoute,
  ServicesDataEngineeringRoute: ServicesDataEngineeringRoute,
  ServicesMobileAppDevelopmentRoute: ServicesMobileAppDevelopmentRoute,
  ServicesMvpRoute: ServicesMvpRoute,
  ServicesQaTestAutomationRoute: ServicesQaTestAutomationRoute,
  ServicesUxUiDesignRoute: ServicesUxUiDesignRoute,
  ServicesWebAppDevelopmentRoute: ServicesWebAppDevelopmentRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  OurBpoServicesIndustriesEntertainmentRoute:
    OurBpoServicesIndustriesEntertainmentRoute,
  OurBpoServicesIndustriesFinancialRoute:
    OurBpoServicesIndustriesFinancialRoute,
  OurBpoServicesIndustriesHealthcareRoute:
    OurBpoServicesIndustriesHealthcareRoute,
  OurBpoServicesIndustriesInsuranceRoute:
    OurBpoServicesIndustriesInsuranceRoute,
  OurBpoServicesIndustriesLogistics_supply_chainRoute:
    OurBpoServicesIndustriesLogistics_supply_chainRoute,
  OurBpoServicesIndustriesReal_estateRoute:
    OurBpoServicesIndustriesReal_estateRoute,
  OurBpoServicesIndustriesRetailRoute: OurBpoServicesIndustriesRetailRoute,
  OurBpoServicesIndustriesTechnologyRoute:
    OurBpoServicesIndustriesTechnologyRoute,
  OurBpoServicesIndustriesTelecommunicationsRoute:
    OurBpoServicesIndustriesTelecommunicationsRoute,
  OurBpoServicesSolutionsAccounting_and_collectionsRoute:
    OurBpoServicesSolutionsAccounting_and_collectionsRoute,
  OurBpoServicesSolutionsBack_office_processingRoute:
    OurBpoServicesSolutionsBack_office_processingRoute,
  OurBpoServicesSolutionsClaims_processingRoute:
    OurBpoServicesSolutionsClaims_processingRoute,
  OurBpoServicesSolutionsCustomer_retentionRoute:
    OurBpoServicesSolutionsCustomer_retentionRoute,
  OurBpoServicesSolutionsDirect_response_marketingRoute:
    OurBpoServicesSolutionsDirect_response_marketingRoute,
  OurBpoServicesSolutionsFacility_and_procurementRoute:
    OurBpoServicesSolutionsFacility_and_procurementRoute,
  OurBpoServicesSolutionsInbound_salesRoute:
    OurBpoServicesSolutionsInbound_salesRoute,
  OurBpoServicesSolutionsInbound_servicesRoute:
    OurBpoServicesSolutionsInbound_servicesRoute,
  OurBpoServicesSolutionsLead_generationRoute:
    OurBpoServicesSolutionsLead_generationRoute,
  OurBpoServicesSolutionsOutbound_servicesRoute:
    OurBpoServicesSolutionsOutbound_servicesRoute,
  OurBpoServicesSolutionsPayment_processingRoute:
    OurBpoServicesSolutionsPayment_processingRoute,
  OurBpoServicesSolutionsTechnical_supportRoute:
    OurBpoServicesSolutionsTechnical_supportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
