name: "work-holo"

services:
  electric:
    image: docker.io/electricsql/electric:1.2.11
    environment:
      DATABASE_URL: postgresql://postgres:postgres@supabase_db_db:5432/postgres
      # Not suitable for production. Only use insecure mode in development or if you've otherwise secured the Electric API.
      # See https://electric-sql.com/docs/guides/security
      ELECTRIC_INSECURE: true
    ports:
      - "5003:3000"
    networks:
      - supabase_network_db

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    ports:
      - "6379:6379"
    networks:
      - supabase_network_db
    ulimits:
      memlock: -1
    volumes:
      - dragonfly_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    networks:
      - supabase_network_db
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  rustfs:
    image: "rustfs/rustfs:latest"
    container_name: rustfs
    restart: unless-stopped
    user: "0:0"
    security_opt:
      - "no-new-privileges:true"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      RUSTFS_ADDRESS: "0.0.0.0:9000"
      RUSTFS_CONSOLE_ADDRESS: "0.0.0.0:9001"
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_BROWSER_REDIRECT: "true"
      RUSTFS_VOLUMES: "/data/rustfs{0..2}"
      RUSTFS_ACCESS_KEY: "GuzpNFteD5xLQ_aoBlUvyw"
      RUSTFS_SECRET_KEY: "zmvR18mhKg3hDlKfdtfp_g"
      RUSTFS_EXTERNAL_ADDRESS: ":9000"
    volumes:
      - "~/data/volumes/storage:/data"
    healthcheck:
      test:
        - CMD
        - sh
        - "-c"
        - "curl -f http://127.0.0.1:9000/health && curl -f http://127.0.0.1:9001/rustfs/console/health"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  supabase_network_db:
    external: true

volumes:
  dragonfly_data:
  rabbitmq_data:
