server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # Never cache version.json
  location = /version.json {
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    add_header Pragma "no-cache";
    add_header Expires "0";
    try_files $uri =404;
  }

  # Serve static assets directly
  location / {
    try_files $uri /index.html;
  }

  # Cache static assets aggressively
  location ~* \.(?:ico|webp|png|jpg|jpeg|gif|svg|css|js|woff2?|ttf|eot)$ {
    expires 10M;
    access_log off;
    try_files $uri /index.html;
  }
}
