// AUTO-GENERATED FILE. DO NOT EDIT.
// Run `bun run generate:types` to refresh
import type { z } from "zod";

import type { AccountInsertSchema } from "./schemas/db-tables";
import type { AccountSchema } from "./schemas/db-tables";
import type { AccountUpdateSchema } from "./schemas/db-tables";
import type { AttachmentInsertSchema } from "./schemas/db-tables";
import type { AttachmentSchema } from "./schemas/db-tables";
import type { AttachmentUpdateSchema } from "./schemas/db-tables";
import type { AttendanceInsertSchema } from "./schemas/db-tables";
import type { AttendanceSchema } from "./schemas/db-tables";
import type { AttendanceUpdateSchema } from "./schemas/db-tables";
import type { ChannelInsertSchema } from "./schemas/db-tables";
import type { ChannelJoinRequestInsertSchema } from "./schemas/db-tables";
import type { ChannelJoinRequestSchema } from "./schemas/db-tables";
import type { ChannelJoinRequestUpdateSchema } from "./schemas/db-tables";
import type { ChannelMemberInsertSchema } from "./schemas/db-tables";
import type { ChannelMemberSchema } from "./schemas/db-tables";
import type { ChannelMemberUpdateSchema } from "./schemas/db-tables";
import type { ChannelSchema } from "./schemas/db-tables";
import type { ChannelTypeSchema } from "./schemas/db-tables";
import type { ChannelUpdateSchema } from "./schemas/db-tables";
import type { InvitationInsertSchema } from "./schemas/db-tables";
import type { InvitationSchema } from "./schemas/db-tables";
import type { InvitationUpdateSchema } from "./schemas/db-tables";
import type { MemberInsertSchema } from "./schemas/db-tables";
import type { MemberSchema } from "./schemas/db-tables";
import type { MemberUpdateSchema } from "./schemas/db-tables";
import type { MessageInsertSchema } from "./schemas/db-tables";
import type { MessageReadInsertSchema } from "./schemas/db-tables";
import type { MessageReadSchema } from "./schemas/db-tables";
import type { MessageReadUpdateSchema } from "./schemas/db-tables";
import type { MessageSchema } from "./schemas/db-tables";
import type { MessageUpdateSchema } from "./schemas/db-tables";
import type { NotificationInsertSchema } from "./schemas/db-tables";
import type { NotificationSchema } from "./schemas/db-tables";
import type { NotificationUpdateSchema } from "./schemas/db-tables";
import type { OrganizationInsertSchema } from "./schemas/db-tables";
import type { OrganizationSchema } from "./schemas/db-tables";
import type { OrganizationUpdateSchema } from "./schemas/db-tables";
import type { SessionInsertSchema } from "./schemas/db-tables";
import type { SessionSchema } from "./schemas/db-tables";
import type { SessionUpdateSchema } from "./schemas/db-tables";
import type { TeamInsertSchema } from "./schemas/db-tables";
import type { TeamMemberInsertSchema } from "./schemas/db-tables";
import type { TeamMemberSchema } from "./schemas/db-tables";
import type { TeamMemberUpdateSchema } from "./schemas/db-tables";
import type { TeamSchema } from "./schemas/db-tables";
import type { TeamUpdateSchema } from "./schemas/db-tables";
import type { UserInsertSchema } from "./schemas/db-tables";
import type { UserSchema } from "./schemas/db-tables";
import type { UserUpdateSchema } from "./schemas/db-tables";
import type { VerificationInsertSchema } from "./schemas/db-tables";
import type { VerificationSchema } from "./schemas/db-tables";
import type { VerificationUpdateSchema } from "./schemas/db-tables";
import type { WorkBlockInsertSchema } from "./schemas/db-tables";
import type { WorkBlockSchema } from "./schemas/db-tables";
import type { WorkBlockUpdateSchema } from "./schemas/db-tables";

export type AccountInsertType = z.infer<typeof AccountInsertSchema>;
export type AccountType = z.infer<typeof AccountSchema>;
export type AccountUpdateType = z.infer<typeof AccountUpdateSchema>;
export type AttachmentInsertType = z.infer<typeof AttachmentInsertSchema>;
export type AttachmentType = z.infer<typeof AttachmentSchema>;
export type AttachmentUpdateType = z.infer<typeof AttachmentUpdateSchema>;
export type AttendanceInsertType = z.infer<typeof AttendanceInsertSchema>;
export type AttendanceType = z.infer<typeof AttendanceSchema>;
export type AttendanceUpdateType = z.infer<typeof AttendanceUpdateSchema>;
export type ChannelInsertType = z.infer<typeof ChannelInsertSchema>;
export type ChannelJoinRequestInsertType = z.infer<
  typeof ChannelJoinRequestInsertSchema
>;
export type ChannelJoinRequestType = z.infer<typeof ChannelJoinRequestSchema>;
export type ChannelJoinRequestUpdateType = z.infer<
  typeof ChannelJoinRequestUpdateSchema
>;
export type ChannelMemberInsertType = z.infer<typeof ChannelMemberInsertSchema>;
export type ChannelMemberType = z.infer<typeof ChannelMemberSchema>;
export type ChannelMemberUpdateType = z.infer<typeof ChannelMemberUpdateSchema>;
export type ChannelType = z.infer<typeof ChannelSchema>;
export type ChannelTypeType = z.infer<typeof ChannelTypeSchema>;
export type ChannelUpdateType = z.infer<typeof ChannelUpdateSchema>;
export type InvitationInsertType = z.infer<typeof InvitationInsertSchema>;
export type InvitationType = z.infer<typeof InvitationSchema>;
export type InvitationUpdateType = z.infer<typeof InvitationUpdateSchema>;
export type MemberInsertType = z.infer<typeof MemberInsertSchema>;
export type MemberType = z.infer<typeof MemberSchema>;
export type MemberUpdateType = z.infer<typeof MemberUpdateSchema>;
export type MessageInsertType = z.infer<typeof MessageInsertSchema>;
export type MessageReadInsertType = z.infer<typeof MessageReadInsertSchema>;
export type MessageReadType = z.infer<typeof MessageReadSchema>;
export type MessageReadUpdateType = z.infer<typeof MessageReadUpdateSchema>;
export type MessageType = z.infer<typeof MessageSchema>;
export type MessageUpdateType = z.infer<typeof MessageUpdateSchema>;
export type NotificationInsertType = z.infer<typeof NotificationInsertSchema>;
export type NotificationType = z.infer<typeof NotificationSchema>;
export type NotificationUpdateType = z.infer<typeof NotificationUpdateSchema>;
export type OrganizationInsertType = z.infer<typeof OrganizationInsertSchema>;
export type OrganizationType = z.infer<typeof OrganizationSchema>;
export type OrganizationUpdateType = z.infer<typeof OrganizationUpdateSchema>;
export type SessionInsertType = z.infer<typeof SessionInsertSchema>;
export type SessionType = z.infer<typeof SessionSchema>;
export type SessionUpdateType = z.infer<typeof SessionUpdateSchema>;
export type TeamInsertType = z.infer<typeof TeamInsertSchema>;
export type TeamMemberInsertType = z.infer<typeof TeamMemberInsertSchema>;
export type TeamMemberType = z.infer<typeof TeamMemberSchema>;
export type TeamMemberUpdateType = z.infer<typeof TeamMemberUpdateSchema>;
export type TeamType = z.infer<typeof TeamSchema>;
export type TeamUpdateType = z.infer<typeof TeamUpdateSchema>;
export type UserInsertType = z.infer<typeof UserInsertSchema>;
export type UserType = z.infer<typeof UserSchema>;
export type UserUpdateType = z.infer<typeof UserUpdateSchema>;
export type VerificationInsertType = z.infer<typeof VerificationInsertSchema>;
export type VerificationType = z.infer<typeof VerificationSchema>;
export type VerificationUpdateType = z.infer<typeof VerificationUpdateSchema>;
export type WorkBlockInsertType = z.infer<typeof WorkBlockInsertSchema>;
export type WorkBlockType = z.infer<typeof WorkBlockSchema>;
export type WorkBlockUpdateType = z.infer<typeof WorkBlockUpdateSchema>;
