/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicPortfolioRouteImport } from './routes/(public)/portfolio'
import { Route as publicContactRouteImport } from './routes/(public)/contact'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as publicAboutRouteRouteImport } from './routes/(public)/about/route'
import { Route as authenticatedSettingsRouteRouteImport } from './routes/(authenticated)/settings/route'
import { Route as authenticatedPlatformRouteRouteImport } from './routes/(authenticated)/platform/route'
import { Route as publicServicesWebApplicationDevelopmentRouteImport } from './routes/(public)/services/web-application-development'
import { Route as publicServicesReactNativeAppDevelopmentRouteImport } from './routes/(public)/services/react-native-app-development'
import { Route as publicServicesMobileAppDevelopmentRouteImport } from './routes/(public)/services/mobile-app-development'
import { Route as publicServicesIpadAppDevelopmentRouteImport } from './routes/(public)/services/ipad-app-development'
import { Route as publicServicesIosAppDevelopmentRouteImport } from './routes/(public)/services/ios-app-development'
import { Route as publicServicesFlutterAppDevelopmentRouteImport } from './routes/(public)/services/flutter-app-development'
import { Route as publicServicesEnterpriseApplicationDevelopmentRouteImport } from './routes/(public)/services/enterprise-application-development'
import { Route as publicServicesCustomSoftwareDevelopmentRouteImport } from './routes/(public)/services/custom-software-development'
import { Route as publicServicesCustomCmsDevelopmentRouteImport } from './routes/(public)/services/custom-cms-development'
import { Route as publicServicesCrossPlatformAppDevelopmentRouteImport } from './routes/(public)/services/cross-platform-app-development'
import { Route as publicServicesAppMaintenanceSupportRouteImport } from './routes/(public)/services/app-maintenance-support'
import { Route as publicServicesAndroidAppDevelopmentRouteImport } from './routes/(public)/services/android-app-development'
import { Route as publicServices360PhotographyServicesRouteImport } from './routes/(public)/services/360-photography-services'
import { Route as publicAboutVisionMissionRouteImport } from './routes/(public)/about/vision-mission'
import { Route as publicAboutOurJourneyRouteImport } from './routes/(public)/about/our-journey'
import { Route as publicAboutNasscomMembershipRouteImport } from './routes/(public)/about/nasscom-membership'
import { Route as publicAboutLifeAtWorkholoLabsRouteImport } from './routes/(public)/about/life-at-workholo-labs'
import { Route as publicAboutLeadershipTeamRouteImport } from './routes/(public)/about/leadership-team'
import { Route as publicAboutCompanyOverviewRouteImport } from './routes/(public)/about/company-overview'
import { Route as publicAboutAwardsRecognitionRouteImport } from './routes/(public)/about/awards-recognition'
import { Route as authenticatedOrgNewRouteImport } from './routes/(authenticated)/org/new'
import { Route as authAcceptInvitationIdRouteImport } from './routes/(auth)/accept-invitation.$id'
import { Route as authenticatedPlatformDashboardRouteRouteImport } from './routes/(authenticated)/platform/dashboard/route'
import { Route as authenticatedOrgSlugRouteRouteImport } from './routes/(authenticated)/org/$slug/route'
import { Route as authenticatedPlatformDashboardIndexRouteImport } from './routes/(authenticated)/platform/dashboard/index'
import { Route as authenticatedSettingsAccountSessionsRouteImport } from './routes/(authenticated)/settings/account/sessions'
import { Route as authenticatedSettingsAccountSecurityRouteImport } from './routes/(authenticated)/settings/account/security'
import { Route as authenticatedSettingsAccountProfileRouteImport } from './routes/(authenticated)/settings/account/profile'
import { Route as authenticatedSettingsAccountPreferencesRouteImport } from './routes/(authenticated)/settings/account/preferences'
import { Route as authenticatedSettingsAccountNotificationsRouteImport } from './routes/(authenticated)/settings/account/notifications'
import { Route as authenticatedOrgSlugWorkspaceRouteRouteImport } from './routes/(authenticated)/org/$slug/workspace/route'
import { Route as authenticatedOrgSlugManageRouteRouteImport } from './routes/(authenticated)/org/$slug/manage/route'
import { Route as authenticatedOrgSlugConsoleRouteRouteImport } from './routes/(authenticated)/org/$slug/console/route'
import { Route as authenticatedPlatformDashboardUsersIndexRouteImport } from './routes/(authenticated)/platform/dashboard/users/index'
import { Route as authenticatedPlatformDashboardSupportIndexRouteImport } from './routes/(authenticated)/platform/dashboard/support/index'
import { Route as authenticatedPlatformDashboardOwnersIndexRouteImport } from './routes/(authenticated)/platform/dashboard/owners/index'
import { Route as authenticatedPlatformDashboardOrganizationsIndexRouteImport } from './routes/(authenticated)/platform/dashboard/organizations/index'
import { Route as authenticatedPlatformDashboardAdminsIndexRouteImport } from './routes/(authenticated)/platform/dashboard/admins/index'
import { Route as authenticatedOrgSlugWorkspaceIndexRouteImport } from './routes/(authenticated)/org/$slug/workspace/index'
import { Route as authenticatedOrgSlugManageIndexRouteImport } from './routes/(authenticated)/org/$slug/manage/index'
import { Route as authenticatedOrgSlugConsoleIndexRouteImport } from './routes/(authenticated)/org/$slug/console/index'
import { Route as authenticatedPlatformDashboardOwnersOwnerIdRouteImport } from './routes/(authenticated)/platform/dashboard/owners/$ownerId'
import { Route as authenticatedPlatformDashboardOrganizationsOrgIdRouteImport } from './routes/(authenticated)/platform/dashboard/organizations/$orgId'
import { Route as authenticatedOrgSlugConsoleModulesRouteRouteImport } from './routes/(authenticated)/org/$slug/console/modules/route'
import { Route as authenticatedOrgSlugWorkspaceTeamsIndexRouteImport } from './routes/(authenticated)/org/$slug/workspace/teams/index'
import { Route as authenticatedOrgSlugWorkspaceAttendanceIndexRouteImport } from './routes/(authenticated)/org/$slug/workspace/attendance/index'
import { Route as authenticatedOrgSlugConsoleTeamsIndexRouteImport } from './routes/(authenticated)/org/$slug/console/teams/index'
import { Route as authenticatedOrgSlugConsoleRolesIndexRouteImport } from './routes/(authenticated)/org/$slug/console/roles/index'
import { Route as authenticatedOrgSlugConsoleMembersIndexRouteImport } from './routes/(authenticated)/org/$slug/console/members/index'
import { Route as authenticatedOrgSlugWorkspaceAttendanceSettingsRouteImport } from './routes/(authenticated)/org/$slug/workspace/attendance/settings'
import { Route as authenticatedOrgSlugWorkspaceAttendanceAnalyticsRouteImport } from './routes/(authenticated)/org/$slug/workspace/attendance/analytics'
import { Route as authenticatedOrgSlugConsoleMembersInvitationsRouteImport } from './routes/(authenticated)/org/$slug/console/members/invitations'
import { Route as authenticatedOrgSlugConsoleMembersMemberIdRouteImport } from './routes/(authenticated)/org/$slug/console/members/$memberId'
import { Route as authenticatedOrgSlugWorkspaceCommunicationDmIndexRouteImport } from './routes/(authenticated)/org/$slug/workspace/communication/dm/index'
import { Route as authenticatedOrgSlugWorkspaceCommunicationChannelsIndexRouteImport } from './routes/(authenticated)/org/$slug/workspace/communication/channels/index'
import { Route as authenticatedOrgSlugConsoleModulesCommunicationIndexRouteImport } from './routes/(authenticated)/org/$slug/console/modules/communication/index'
import { Route as authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteImport } from './routes/(authenticated)/org/$slug/workspace/communication/dm/$conversationId/route'
import { Route as authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteImport } from './routes/(authenticated)/org/$slug/workspace/communication/channels/$channelId/route'
import { Route as authenticatedOrgSlugWorkspaceCommunicationDmConversationIdIndexRouteImport } from './routes/(authenticated)/org/$slug/workspace/communication/dm/$conversationId/index'
import { Route as authenticatedOrgSlugWorkspaceCommunicationChannelsFilesIndexRouteImport } from './routes/(authenticated)/org/$slug/workspace/communication/channels/files/index'
import { Route as authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdIndexRouteImport } from './routes/(authenticated)/org/$slug/workspace/communication/channels/$channelId/index'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicPortfolioRoute = publicPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicContactRoute = publicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => publicRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAboutRouteRoute = publicAboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => publicRouteRoute,
} as any)
const authenticatedSettingsRouteRoute =
  authenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedPlatformRouteRoute =
  authenticatedPlatformRouteRouteImport.update({
    id: '/platform',
    path: '/platform',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const publicServicesWebApplicationDevelopmentRoute =
  publicServicesWebApplicationDevelopmentRouteImport.update({
    id: '/services/web-application-development',
    path: '/services/web-application-development',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicServicesReactNativeAppDevelopmentRoute =
  publicServicesReactNativeAppDevelopmentRouteImport.update({
    id: '/services/react-native-app-development',
    path: '/services/react-native-app-development',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicServicesMobileAppDevelopmentRoute =
  publicServicesMobileAppDevelopmentRouteImport.update({
    id: '/services/mobile-app-development',
    path: '/services/mobile-app-development',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicServicesIpadAppDevelopmentRoute =
  publicServicesIpadAppDevelopmentRouteImport.update({
    id: '/services/ipad-app-development',
    path: '/services/ipad-app-development',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicServicesIosAppDevelopmentRoute =
  publicServicesIosAppDevelopmentRouteImport.update({
    id: '/services/ios-app-development',
    path: '/services/ios-app-development',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicServicesFlutterAppDevelopmentRoute =
  publicServicesFlutterAppDevelopmentRouteImport.update({
    id: '/services/flutter-app-development',
    path: '/services/flutter-app-development',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicServicesEnterpriseApplicationDevelopmentRoute =
  publicServicesEnterpriseApplicationDevelopmentRouteImport.update({
    id: '/services/enterprise-application-development',
    path: '/services/enterprise-application-development',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicServicesCustomSoftwareDevelopmentRoute =
  publicServicesCustomSoftwareDevelopmentRouteImport.update({
    id: '/services/custom-software-development',
    path: '/services/custom-software-development',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicServicesCustomCmsDevelopmentRoute =
  publicServicesCustomCmsDevelopmentRouteImport.update({
    id: '/services/custom-cms-development',
    path: '/services/custom-cms-development',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicServicesCrossPlatformAppDevelopmentRoute =
  publicServicesCrossPlatformAppDevelopmentRouteImport.update({
    id: '/services/cross-platform-app-development',
    path: '/services/cross-platform-app-development',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicServicesAppMaintenanceSupportRoute =
  publicServicesAppMaintenanceSupportRouteImport.update({
    id: '/services/app-maintenance-support',
    path: '/services/app-maintenance-support',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicServicesAndroidAppDevelopmentRoute =
  publicServicesAndroidAppDevelopmentRouteImport.update({
    id: '/services/android-app-development',
    path: '/services/android-app-development',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicServices360PhotographyServicesRoute =
  publicServices360PhotographyServicesRouteImport.update({
    id: '/services/360-photography-services',
    path: '/services/360-photography-services',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicAboutVisionMissionRoute =
  publicAboutVisionMissionRouteImport.update({
    id: '/vision-mission',
    path: '/vision-mission',
    getParentRoute: () => publicAboutRouteRoute,
  } as any)
const publicAboutOurJourneyRoute = publicAboutOurJourneyRouteImport.update({
  id: '/our-journey',
  path: '/our-journey',
  getParentRoute: () => publicAboutRouteRoute,
} as any)
const publicAboutNasscomMembershipRoute =
  publicAboutNasscomMembershipRouteImport.update({
    id: '/nasscom-membership',
    path: '/nasscom-membership',
    getParentRoute: () => publicAboutRouteRoute,
  } as any)
const publicAboutLifeAtWorkholoLabsRoute =
  publicAboutLifeAtWorkholoLabsRouteImport.update({
    id: '/life-at-workholo-labs',
    path: '/life-at-workholo-labs',
    getParentRoute: () => publicAboutRouteRoute,
  } as any)
const publicAboutLeadershipTeamRoute =
  publicAboutLeadershipTeamRouteImport.update({
    id: '/leadership-team',
    path: '/leadership-team',
    getParentRoute: () => publicAboutRouteRoute,
  } as any)
const publicAboutCompanyOverviewRoute =
  publicAboutCompanyOverviewRouteImport.update({
    id: '/company-overview',
    path: '/company-overview',
    getParentRoute: () => publicAboutRouteRoute,
  } as any)
const publicAboutAwardsRecognitionRoute =
  publicAboutAwardsRecognitionRouteImport.update({
    id: '/awards-recognition',
    path: '/awards-recognition',
    getParentRoute: () => publicAboutRouteRoute,
  } as any)
const authenticatedOrgNewRoute = authenticatedOrgNewRouteImport.update({
  id: '/org/new',
  path: '/org/new',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authAcceptInvitationIdRoute = authAcceptInvitationIdRouteImport.update({
  id: '/(auth)/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedPlatformDashboardRouteRoute =
  authenticatedPlatformDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedPlatformRouteRoute,
  } as any)
const authenticatedOrgSlugRouteRoute =
  authenticatedOrgSlugRouteRouteImport.update({
    id: '/org/$slug',
    path: '/org/$slug',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedPlatformDashboardIndexRoute =
  authenticatedPlatformDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedPlatformDashboardRouteRoute,
  } as any)
const authenticatedSettingsAccountSessionsRoute =
  authenticatedSettingsAccountSessionsRouteImport.update({
    id: '/account/sessions',
    path: '/account/sessions',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedSettingsAccountSecurityRoute =
  authenticatedSettingsAccountSecurityRouteImport.update({
    id: '/account/security',
    path: '/account/security',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedSettingsAccountProfileRoute =
  authenticatedSettingsAccountProfileRouteImport.update({
    id: '/account/profile',
    path: '/account/profile',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedSettingsAccountPreferencesRoute =
  authenticatedSettingsAccountPreferencesRouteImport.update({
    id: '/account/preferences',
    path: '/account/preferences',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedSettingsAccountNotificationsRoute =
  authenticatedSettingsAccountNotificationsRouteImport.update({
    id: '/account/notifications',
    path: '/account/notifications',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedOrgSlugWorkspaceRouteRoute =
  authenticatedOrgSlugWorkspaceRouteRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => authenticatedOrgSlugRouteRoute,
  } as any)
const authenticatedOrgSlugManageRouteRoute =
  authenticatedOrgSlugManageRouteRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => authenticatedOrgSlugRouteRoute,
  } as any)
const authenticatedOrgSlugConsoleRouteRoute =
  authenticatedOrgSlugConsoleRouteRouteImport.update({
    id: '/console',
    path: '/console',
    getParentRoute: () => authenticatedOrgSlugRouteRoute,
  } as any)
const authenticatedPlatformDashboardUsersIndexRoute =
  authenticatedPlatformDashboardUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => authenticatedPlatformDashboardRouteRoute,
  } as any)
const authenticatedPlatformDashboardSupportIndexRoute =
  authenticatedPlatformDashboardSupportIndexRouteImport.update({
    id: '/support/',
    path: '/support/',
    getParentRoute: () => authenticatedPlatformDashboardRouteRoute,
  } as any)
const authenticatedPlatformDashboardOwnersIndexRoute =
  authenticatedPlatformDashboardOwnersIndexRouteImport.update({
    id: '/owners/',
    path: '/owners/',
    getParentRoute: () => authenticatedPlatformDashboardRouteRoute,
  } as any)
const authenticatedPlatformDashboardOrganizationsIndexRoute =
  authenticatedPlatformDashboardOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => authenticatedPlatformDashboardRouteRoute,
  } as any)
const authenticatedPlatformDashboardAdminsIndexRoute =
  authenticatedPlatformDashboardAdminsIndexRouteImport.update({
    id: '/admins/',
    path: '/admins/',
    getParentRoute: () => authenticatedPlatformDashboardRouteRoute,
  } as any)
const authenticatedOrgSlugWorkspaceIndexRoute =
  authenticatedOrgSlugWorkspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedOrgSlugWorkspaceRouteRoute,
  } as any)
const authenticatedOrgSlugManageIndexRoute =
  authenticatedOrgSlugManageIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedOrgSlugManageRouteRoute,
  } as any)
const authenticatedOrgSlugConsoleIndexRoute =
  authenticatedOrgSlugConsoleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedOrgSlugConsoleRouteRoute,
  } as any)
const authenticatedPlatformDashboardOwnersOwnerIdRoute =
  authenticatedPlatformDashboardOwnersOwnerIdRouteImport.update({
    id: '/owners/$ownerId',
    path: '/owners/$ownerId',
    getParentRoute: () => authenticatedPlatformDashboardRouteRoute,
  } as any)
const authenticatedPlatformDashboardOrganizationsOrgIdRoute =
  authenticatedPlatformDashboardOrganizationsOrgIdRouteImport.update({
    id: '/organizations/$orgId',
    path: '/organizations/$orgId',
    getParentRoute: () => authenticatedPlatformDashboardRouteRoute,
  } as any)
const authenticatedOrgSlugConsoleModulesRouteRoute =
  authenticatedOrgSlugConsoleModulesRouteRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => authenticatedOrgSlugConsoleRouteRoute,
  } as any)
const authenticatedOrgSlugWorkspaceTeamsIndexRoute =
  authenticatedOrgSlugWorkspaceTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => authenticatedOrgSlugWorkspaceRouteRoute,
  } as any)
const authenticatedOrgSlugWorkspaceAttendanceIndexRoute =
  authenticatedOrgSlugWorkspaceAttendanceIndexRouteImport.update({
    id: '/attendance/',
    path: '/attendance/',
    getParentRoute: () => authenticatedOrgSlugWorkspaceRouteRoute,
  } as any)
const authenticatedOrgSlugConsoleTeamsIndexRoute =
  authenticatedOrgSlugConsoleTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => authenticatedOrgSlugConsoleRouteRoute,
  } as any)
const authenticatedOrgSlugConsoleRolesIndexRoute =
  authenticatedOrgSlugConsoleRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => authenticatedOrgSlugConsoleRouteRoute,
  } as any)
const authenticatedOrgSlugConsoleMembersIndexRoute =
  authenticatedOrgSlugConsoleMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => authenticatedOrgSlugConsoleRouteRoute,
  } as any)
const authenticatedOrgSlugWorkspaceAttendanceSettingsRoute =
  authenticatedOrgSlugWorkspaceAttendanceSettingsRouteImport.update({
    id: '/attendance/settings',
    path: '/attendance/settings',
    getParentRoute: () => authenticatedOrgSlugWorkspaceRouteRoute,
  } as any)
const authenticatedOrgSlugWorkspaceAttendanceAnalyticsRoute =
  authenticatedOrgSlugWorkspaceAttendanceAnalyticsRouteImport.update({
    id: '/attendance/analytics',
    path: '/attendance/analytics',
    getParentRoute: () => authenticatedOrgSlugWorkspaceRouteRoute,
  } as any)
const authenticatedOrgSlugConsoleMembersInvitationsRoute =
  authenticatedOrgSlugConsoleMembersInvitationsRouteImport.update({
    id: '/members/invitations',
    path: '/members/invitations',
    getParentRoute: () => authenticatedOrgSlugConsoleRouteRoute,
  } as any)
const authenticatedOrgSlugConsoleMembersMemberIdRoute =
  authenticatedOrgSlugConsoleMembersMemberIdRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => authenticatedOrgSlugConsoleRouteRoute,
  } as any)
const authenticatedOrgSlugWorkspaceCommunicationDmIndexRoute =
  authenticatedOrgSlugWorkspaceCommunicationDmIndexRouteImport.update({
    id: '/communication/dm/',
    path: '/communication/dm/',
    getParentRoute: () => authenticatedOrgSlugWorkspaceRouteRoute,
  } as any)
const authenticatedOrgSlugWorkspaceCommunicationChannelsIndexRoute =
  authenticatedOrgSlugWorkspaceCommunicationChannelsIndexRouteImport.update({
    id: '/communication/channels/',
    path: '/communication/channels/',
    getParentRoute: () => authenticatedOrgSlugWorkspaceRouteRoute,
  } as any)
const authenticatedOrgSlugConsoleModulesCommunicationIndexRoute =
  authenticatedOrgSlugConsoleModulesCommunicationIndexRouteImport.update({
    id: '/communication/',
    path: '/communication/',
    getParentRoute: () => authenticatedOrgSlugConsoleModulesRouteRoute,
  } as any)
const authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRoute =
  authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteImport.update(
    {
      id: '/communication/dm/$conversationId',
      path: '/communication/dm/$conversationId',
      getParentRoute: () => authenticatedOrgSlugWorkspaceRouteRoute,
    } as any,
  )
const authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRoute =
  authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteImport.update(
    {
      id: '/communication/channels/$channelId',
      path: '/communication/channels/$channelId',
      getParentRoute: () => authenticatedOrgSlugWorkspaceRouteRoute,
    } as any,
  )
const authenticatedOrgSlugWorkspaceCommunicationDmConversationIdIndexRoute =
  authenticatedOrgSlugWorkspaceCommunicationDmConversationIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRoute,
    } as any,
  )
const authenticatedOrgSlugWorkspaceCommunicationChannelsFilesIndexRoute =
  authenticatedOrgSlugWorkspaceCommunicationChannelsFilesIndexRouteImport.update(
    {
      id: '/communication/channels/files/',
      path: '/communication/channels/files/',
      getParentRoute: () => authenticatedOrgSlugWorkspaceRouteRoute,
    } as any,
  )
const authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdIndexRoute =
  authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/platform': typeof authenticatedPlatformRouteRouteWithChildren
  '/settings': typeof authenticatedSettingsRouteRouteWithChildren
  '/about': typeof publicAboutRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/contact': typeof publicContactRoute
  '/portfolio': typeof publicPortfolioRoute
  '/': typeof publicIndexRoute
  '/org/$slug': typeof authenticatedOrgSlugRouteRouteWithChildren
  '/platform/dashboard': typeof authenticatedPlatformDashboardRouteRouteWithChildren
  '/accept-invitation/$id': typeof authAcceptInvitationIdRoute
  '/org/new': typeof authenticatedOrgNewRoute
  '/about/awards-recognition': typeof publicAboutAwardsRecognitionRoute
  '/about/company-overview': typeof publicAboutCompanyOverviewRoute
  '/about/leadership-team': typeof publicAboutLeadershipTeamRoute
  '/about/life-at-workholo-labs': typeof publicAboutLifeAtWorkholoLabsRoute
  '/about/nasscom-membership': typeof publicAboutNasscomMembershipRoute
  '/about/our-journey': typeof publicAboutOurJourneyRoute
  '/about/vision-mission': typeof publicAboutVisionMissionRoute
  '/services/360-photography-services': typeof publicServices360PhotographyServicesRoute
  '/services/android-app-development': typeof publicServicesAndroidAppDevelopmentRoute
  '/services/app-maintenance-support': typeof publicServicesAppMaintenanceSupportRoute
  '/services/cross-platform-app-development': typeof publicServicesCrossPlatformAppDevelopmentRoute
  '/services/custom-cms-development': typeof publicServicesCustomCmsDevelopmentRoute
  '/services/custom-software-development': typeof publicServicesCustomSoftwareDevelopmentRoute
  '/services/enterprise-application-development': typeof publicServicesEnterpriseApplicationDevelopmentRoute
  '/services/flutter-app-development': typeof publicServicesFlutterAppDevelopmentRoute
  '/services/ios-app-development': typeof publicServicesIosAppDevelopmentRoute
  '/services/ipad-app-development': typeof publicServicesIpadAppDevelopmentRoute
  '/services/mobile-app-development': typeof publicServicesMobileAppDevelopmentRoute
  '/services/react-native-app-development': typeof publicServicesReactNativeAppDevelopmentRoute
  '/services/web-application-development': typeof publicServicesWebApplicationDevelopmentRoute
  '/org/$slug/console': typeof authenticatedOrgSlugConsoleRouteRouteWithChildren
  '/org/$slug/manage': typeof authenticatedOrgSlugManageRouteRouteWithChildren
  '/org/$slug/workspace': typeof authenticatedOrgSlugWorkspaceRouteRouteWithChildren
  '/settings/account/notifications': typeof authenticatedSettingsAccountNotificationsRoute
  '/settings/account/preferences': typeof authenticatedSettingsAccountPreferencesRoute
  '/settings/account/profile': typeof authenticatedSettingsAccountProfileRoute
  '/settings/account/security': typeof authenticatedSettingsAccountSecurityRoute
  '/settings/account/sessions': typeof authenticatedSettingsAccountSessionsRoute
  '/platform/dashboard/': typeof authenticatedPlatformDashboardIndexRoute
  '/org/$slug/console/modules': typeof authenticatedOrgSlugConsoleModulesRouteRouteWithChildren
  '/platform/dashboard/organizations/$orgId': typeof authenticatedPlatformDashboardOrganizationsOrgIdRoute
  '/platform/dashboard/owners/$ownerId': typeof authenticatedPlatformDashboardOwnersOwnerIdRoute
  '/org/$slug/console/': typeof authenticatedOrgSlugConsoleIndexRoute
  '/org/$slug/manage/': typeof authenticatedOrgSlugManageIndexRoute
  '/org/$slug/workspace/': typeof authenticatedOrgSlugWorkspaceIndexRoute
  '/platform/dashboard/admins/': typeof authenticatedPlatformDashboardAdminsIndexRoute
  '/platform/dashboard/organizations/': typeof authenticatedPlatformDashboardOrganizationsIndexRoute
  '/platform/dashboard/owners/': typeof authenticatedPlatformDashboardOwnersIndexRoute
  '/platform/dashboard/support/': typeof authenticatedPlatformDashboardSupportIndexRoute
  '/platform/dashboard/users/': typeof authenticatedPlatformDashboardUsersIndexRoute
  '/org/$slug/console/members/$memberId': typeof authenticatedOrgSlugConsoleMembersMemberIdRoute
  '/org/$slug/console/members/invitations': typeof authenticatedOrgSlugConsoleMembersInvitationsRoute
  '/org/$slug/workspace/attendance/analytics': typeof authenticatedOrgSlugWorkspaceAttendanceAnalyticsRoute
  '/org/$slug/workspace/attendance/settings': typeof authenticatedOrgSlugWorkspaceAttendanceSettingsRoute
  '/org/$slug/console/members/': typeof authenticatedOrgSlugConsoleMembersIndexRoute
  '/org/$slug/console/roles/': typeof authenticatedOrgSlugConsoleRolesIndexRoute
  '/org/$slug/console/teams/': typeof authenticatedOrgSlugConsoleTeamsIndexRoute
  '/org/$slug/workspace/attendance/': typeof authenticatedOrgSlugWorkspaceAttendanceIndexRoute
  '/org/$slug/workspace/teams/': typeof authenticatedOrgSlugWorkspaceTeamsIndexRoute
  '/org/$slug/workspace/communication/channels/$channelId': typeof authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteWithChildren
  '/org/$slug/workspace/communication/dm/$conversationId': typeof authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteWithChildren
  '/org/$slug/console/modules/communication/': typeof authenticatedOrgSlugConsoleModulesCommunicationIndexRoute
  '/org/$slug/workspace/communication/channels/': typeof authenticatedOrgSlugWorkspaceCommunicationChannelsIndexRoute
  '/org/$slug/workspace/communication/dm/': typeof authenticatedOrgSlugWorkspaceCommunicationDmIndexRoute
  '/org/$slug/workspace/communication/channels/$channelId/': typeof authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdIndexRoute
  '/org/$slug/workspace/communication/channels/files/': typeof authenticatedOrgSlugWorkspaceCommunicationChannelsFilesIndexRoute
  '/org/$slug/workspace/communication/dm/$conversationId/': typeof authenticatedOrgSlugWorkspaceCommunicationDmConversationIdIndexRoute
}
export interface FileRoutesByTo {
  '/platform': typeof authenticatedPlatformRouteRouteWithChildren
  '/settings': typeof authenticatedSettingsRouteRouteWithChildren
  '/about': typeof publicAboutRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/contact': typeof publicContactRoute
  '/portfolio': typeof publicPortfolioRoute
  '/': typeof publicIndexRoute
  '/org/$slug': typeof authenticatedOrgSlugRouteRouteWithChildren
  '/accept-invitation/$id': typeof authAcceptInvitationIdRoute
  '/org/new': typeof authenticatedOrgNewRoute
  '/about/awards-recognition': typeof publicAboutAwardsRecognitionRoute
  '/about/company-overview': typeof publicAboutCompanyOverviewRoute
  '/about/leadership-team': typeof publicAboutLeadershipTeamRoute
  '/about/life-at-workholo-labs': typeof publicAboutLifeAtWorkholoLabsRoute
  '/about/nasscom-membership': typeof publicAboutNasscomMembershipRoute
  '/about/our-journey': typeof publicAboutOurJourneyRoute
  '/about/vision-mission': typeof publicAboutVisionMissionRoute
  '/services/360-photography-services': typeof publicServices360PhotographyServicesRoute
  '/services/android-app-development': typeof publicServicesAndroidAppDevelopmentRoute
  '/services/app-maintenance-support': typeof publicServicesAppMaintenanceSupportRoute
  '/services/cross-platform-app-development': typeof publicServicesCrossPlatformAppDevelopmentRoute
  '/services/custom-cms-development': typeof publicServicesCustomCmsDevelopmentRoute
  '/services/custom-software-development': typeof publicServicesCustomSoftwareDevelopmentRoute
  '/services/enterprise-application-development': typeof publicServicesEnterpriseApplicationDevelopmentRoute
  '/services/flutter-app-development': typeof publicServicesFlutterAppDevelopmentRoute
  '/services/ios-app-development': typeof publicServicesIosAppDevelopmentRoute
  '/services/ipad-app-development': typeof publicServicesIpadAppDevelopmentRoute
  '/services/mobile-app-development': typeof publicServicesMobileAppDevelopmentRoute
  '/services/react-native-app-development': typeof publicServicesReactNativeAppDevelopmentRoute
  '/services/web-application-development': typeof publicServicesWebApplicationDevelopmentRoute
  '/settings/account/notifications': typeof authenticatedSettingsAccountNotificationsRoute
  '/settings/account/preferences': typeof authenticatedSettingsAccountPreferencesRoute
  '/settings/account/profile': typeof authenticatedSettingsAccountProfileRoute
  '/settings/account/security': typeof authenticatedSettingsAccountSecurityRoute
  '/settings/account/sessions': typeof authenticatedSettingsAccountSessionsRoute
  '/platform/dashboard': typeof authenticatedPlatformDashboardIndexRoute
  '/org/$slug/console/modules': typeof authenticatedOrgSlugConsoleModulesRouteRouteWithChildren
  '/platform/dashboard/organizations/$orgId': typeof authenticatedPlatformDashboardOrganizationsOrgIdRoute
  '/platform/dashboard/owners/$ownerId': typeof authenticatedPlatformDashboardOwnersOwnerIdRoute
  '/org/$slug/console': typeof authenticatedOrgSlugConsoleIndexRoute
  '/org/$slug/manage': typeof authenticatedOrgSlugManageIndexRoute
  '/org/$slug/workspace': typeof authenticatedOrgSlugWorkspaceIndexRoute
  '/platform/dashboard/admins': typeof authenticatedPlatformDashboardAdminsIndexRoute
  '/platform/dashboard/organizations': typeof authenticatedPlatformDashboardOrganizationsIndexRoute
  '/platform/dashboard/owners': typeof authenticatedPlatformDashboardOwnersIndexRoute
  '/platform/dashboard/support': typeof authenticatedPlatformDashboardSupportIndexRoute
  '/platform/dashboard/users': typeof authenticatedPlatformDashboardUsersIndexRoute
  '/org/$slug/console/members/$memberId': typeof authenticatedOrgSlugConsoleMembersMemberIdRoute
  '/org/$slug/console/members/invitations': typeof authenticatedOrgSlugConsoleMembersInvitationsRoute
  '/org/$slug/workspace/attendance/analytics': typeof authenticatedOrgSlugWorkspaceAttendanceAnalyticsRoute
  '/org/$slug/workspace/attendance/settings': typeof authenticatedOrgSlugWorkspaceAttendanceSettingsRoute
  '/org/$slug/console/members': typeof authenticatedOrgSlugConsoleMembersIndexRoute
  '/org/$slug/console/roles': typeof authenticatedOrgSlugConsoleRolesIndexRoute
  '/org/$slug/console/teams': typeof authenticatedOrgSlugConsoleTeamsIndexRoute
  '/org/$slug/workspace/attendance': typeof authenticatedOrgSlugWorkspaceAttendanceIndexRoute
  '/org/$slug/workspace/teams': typeof authenticatedOrgSlugWorkspaceTeamsIndexRoute
  '/org/$slug/console/modules/communication': typeof authenticatedOrgSlugConsoleModulesCommunicationIndexRoute
  '/org/$slug/workspace/communication/channels': typeof authenticatedOrgSlugWorkspaceCommunicationChannelsIndexRoute
  '/org/$slug/workspace/communication/dm': typeof authenticatedOrgSlugWorkspaceCommunicationDmIndexRoute
  '/org/$slug/workspace/communication/channels/$channelId': typeof authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdIndexRoute
  '/org/$slug/workspace/communication/channels/files': typeof authenticatedOrgSlugWorkspaceCommunicationChannelsFilesIndexRoute
  '/org/$slug/workspace/communication/dm/$conversationId': typeof authenticatedOrgSlugWorkspaceCommunicationDmConversationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(authenticated)/platform': typeof authenticatedPlatformRouteRouteWithChildren
  '/(authenticated)/settings': typeof authenticatedSettingsRouteRouteWithChildren
  '/(public)/about': typeof publicAboutRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(public)/contact': typeof publicContactRoute
  '/(public)/portfolio': typeof publicPortfolioRoute
  '/(public)/': typeof publicIndexRoute
  '/(authenticated)/org/$slug': typeof authenticatedOrgSlugRouteRouteWithChildren
  '/(authenticated)/platform/dashboard': typeof authenticatedPlatformDashboardRouteRouteWithChildren
  '/(auth)/accept-invitation/$id': typeof authAcceptInvitationIdRoute
  '/(authenticated)/org/new': typeof authenticatedOrgNewRoute
  '/(public)/about/awards-recognition': typeof publicAboutAwardsRecognitionRoute
  '/(public)/about/company-overview': typeof publicAboutCompanyOverviewRoute
  '/(public)/about/leadership-team': typeof publicAboutLeadershipTeamRoute
  '/(public)/about/life-at-workholo-labs': typeof publicAboutLifeAtWorkholoLabsRoute
  '/(public)/about/nasscom-membership': typeof publicAboutNasscomMembershipRoute
  '/(public)/about/our-journey': typeof publicAboutOurJourneyRoute
  '/(public)/about/vision-mission': typeof publicAboutVisionMissionRoute
  '/(public)/services/360-photography-services': typeof publicServices360PhotographyServicesRoute
  '/(public)/services/android-app-development': typeof publicServicesAndroidAppDevelopmentRoute
  '/(public)/services/app-maintenance-support': typeof publicServicesAppMaintenanceSupportRoute
  '/(public)/services/cross-platform-app-development': typeof publicServicesCrossPlatformAppDevelopmentRoute
  '/(public)/services/custom-cms-development': typeof publicServicesCustomCmsDevelopmentRoute
  '/(public)/services/custom-software-development': typeof publicServicesCustomSoftwareDevelopmentRoute
  '/(public)/services/enterprise-application-development': typeof publicServicesEnterpriseApplicationDevelopmentRoute
  '/(public)/services/flutter-app-development': typeof publicServicesFlutterAppDevelopmentRoute
  '/(public)/services/ios-app-development': typeof publicServicesIosAppDevelopmentRoute
  '/(public)/services/ipad-app-development': typeof publicServicesIpadAppDevelopmentRoute
  '/(public)/services/mobile-app-development': typeof publicServicesMobileAppDevelopmentRoute
  '/(public)/services/react-native-app-development': typeof publicServicesReactNativeAppDevelopmentRoute
  '/(public)/services/web-application-development': typeof publicServicesWebApplicationDevelopmentRoute
  '/(authenticated)/org/$slug/console': typeof authenticatedOrgSlugConsoleRouteRouteWithChildren
  '/(authenticated)/org/$slug/manage': typeof authenticatedOrgSlugManageRouteRouteWithChildren
  '/(authenticated)/org/$slug/workspace': typeof authenticatedOrgSlugWorkspaceRouteRouteWithChildren
  '/(authenticated)/settings/account/notifications': typeof authenticatedSettingsAccountNotificationsRoute
  '/(authenticated)/settings/account/preferences': typeof authenticatedSettingsAccountPreferencesRoute
  '/(authenticated)/settings/account/profile': typeof authenticatedSettingsAccountProfileRoute
  '/(authenticated)/settings/account/security': typeof authenticatedSettingsAccountSecurityRoute
  '/(authenticated)/settings/account/sessions': typeof authenticatedSettingsAccountSessionsRoute
  '/(authenticated)/platform/dashboard/': typeof authenticatedPlatformDashboardIndexRoute
  '/(authenticated)/org/$slug/console/modules': typeof authenticatedOrgSlugConsoleModulesRouteRouteWithChildren
  '/(authenticated)/platform/dashboard/organizations/$orgId': typeof authenticatedPlatformDashboardOrganizationsOrgIdRoute
  '/(authenticated)/platform/dashboard/owners/$ownerId': typeof authenticatedPlatformDashboardOwnersOwnerIdRoute
  '/(authenticated)/org/$slug/console/': typeof authenticatedOrgSlugConsoleIndexRoute
  '/(authenticated)/org/$slug/manage/': typeof authenticatedOrgSlugManageIndexRoute
  '/(authenticated)/org/$slug/workspace/': typeof authenticatedOrgSlugWorkspaceIndexRoute
  '/(authenticated)/platform/dashboard/admins/': typeof authenticatedPlatformDashboardAdminsIndexRoute
  '/(authenticated)/platform/dashboard/organizations/': typeof authenticatedPlatformDashboardOrganizationsIndexRoute
  '/(authenticated)/platform/dashboard/owners/': typeof authenticatedPlatformDashboardOwnersIndexRoute
  '/(authenticated)/platform/dashboard/support/': typeof authenticatedPlatformDashboardSupportIndexRoute
  '/(authenticated)/platform/dashboard/users/': typeof authenticatedPlatformDashboardUsersIndexRoute
  '/(authenticated)/org/$slug/console/members/$memberId': typeof authenticatedOrgSlugConsoleMembersMemberIdRoute
  '/(authenticated)/org/$slug/console/members/invitations': typeof authenticatedOrgSlugConsoleMembersInvitationsRoute
  '/(authenticated)/org/$slug/workspace/attendance/analytics': typeof authenticatedOrgSlugWorkspaceAttendanceAnalyticsRoute
  '/(authenticated)/org/$slug/workspace/attendance/settings': typeof authenticatedOrgSlugWorkspaceAttendanceSettingsRoute
  '/(authenticated)/org/$slug/console/members/': typeof authenticatedOrgSlugConsoleMembersIndexRoute
  '/(authenticated)/org/$slug/console/roles/': typeof authenticatedOrgSlugConsoleRolesIndexRoute
  '/(authenticated)/org/$slug/console/teams/': typeof authenticatedOrgSlugConsoleTeamsIndexRoute
  '/(authenticated)/org/$slug/workspace/attendance/': typeof authenticatedOrgSlugWorkspaceAttendanceIndexRoute
  '/(authenticated)/org/$slug/workspace/teams/': typeof authenticatedOrgSlugWorkspaceTeamsIndexRoute
  '/(authenticated)/org/$slug/workspace/communication/channels/$channelId': typeof authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteWithChildren
  '/(authenticated)/org/$slug/workspace/communication/dm/$conversationId': typeof authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteWithChildren
  '/(authenticated)/org/$slug/console/modules/communication/': typeof authenticatedOrgSlugConsoleModulesCommunicationIndexRoute
  '/(authenticated)/org/$slug/workspace/communication/channels/': typeof authenticatedOrgSlugWorkspaceCommunicationChannelsIndexRoute
  '/(authenticated)/org/$slug/workspace/communication/dm/': typeof authenticatedOrgSlugWorkspaceCommunicationDmIndexRoute
  '/(authenticated)/org/$slug/workspace/communication/channels/$channelId/': typeof authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdIndexRoute
  '/(authenticated)/org/$slug/workspace/communication/channels/files/': typeof authenticatedOrgSlugWorkspaceCommunicationChannelsFilesIndexRoute
  '/(authenticated)/org/$slug/workspace/communication/dm/$conversationId/': typeof authenticatedOrgSlugWorkspaceCommunicationDmConversationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/platform'
    | '/settings'
    | '/about'
    | '/login'
    | '/signup'
    | '/contact'
    | '/portfolio'
    | '/'
    | '/org/$slug'
    | '/platform/dashboard'
    | '/accept-invitation/$id'
    | '/org/new'
    | '/about/awards-recognition'
    | '/about/company-overview'
    | '/about/leadership-team'
    | '/about/life-at-workholo-labs'
    | '/about/nasscom-membership'
    | '/about/our-journey'
    | '/about/vision-mission'
    | '/services/360-photography-services'
    | '/services/android-app-development'
    | '/services/app-maintenance-support'
    | '/services/cross-platform-app-development'
    | '/services/custom-cms-development'
    | '/services/custom-software-development'
    | '/services/enterprise-application-development'
    | '/services/flutter-app-development'
    | '/services/ios-app-development'
    | '/services/ipad-app-development'
    | '/services/mobile-app-development'
    | '/services/react-native-app-development'
    | '/services/web-application-development'
    | '/org/$slug/console'
    | '/org/$slug/manage'
    | '/org/$slug/workspace'
    | '/settings/account/notifications'
    | '/settings/account/preferences'
    | '/settings/account/profile'
    | '/settings/account/security'
    | '/settings/account/sessions'
    | '/platform/dashboard/'
    | '/org/$slug/console/modules'
    | '/platform/dashboard/organizations/$orgId'
    | '/platform/dashboard/owners/$ownerId'
    | '/org/$slug/console/'
    | '/org/$slug/manage/'
    | '/org/$slug/workspace/'
    | '/platform/dashboard/admins/'
    | '/platform/dashboard/organizations/'
    | '/platform/dashboard/owners/'
    | '/platform/dashboard/support/'
    | '/platform/dashboard/users/'
    | '/org/$slug/console/members/$memberId'
    | '/org/$slug/console/members/invitations'
    | '/org/$slug/workspace/attendance/analytics'
    | '/org/$slug/workspace/attendance/settings'
    | '/org/$slug/console/members/'
    | '/org/$slug/console/roles/'
    | '/org/$slug/console/teams/'
    | '/org/$slug/workspace/attendance/'
    | '/org/$slug/workspace/teams/'
    | '/org/$slug/workspace/communication/channels/$channelId'
    | '/org/$slug/workspace/communication/dm/$conversationId'
    | '/org/$slug/console/modules/communication/'
    | '/org/$slug/workspace/communication/channels/'
    | '/org/$slug/workspace/communication/dm/'
    | '/org/$slug/workspace/communication/channels/$channelId/'
    | '/org/$slug/workspace/communication/channels/files/'
    | '/org/$slug/workspace/communication/dm/$conversationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/platform'
    | '/settings'
    | '/about'
    | '/login'
    | '/signup'
    | '/contact'
    | '/portfolio'
    | '/'
    | '/org/$slug'
    | '/accept-invitation/$id'
    | '/org/new'
    | '/about/awards-recognition'
    | '/about/company-overview'
    | '/about/leadership-team'
    | '/about/life-at-workholo-labs'
    | '/about/nasscom-membership'
    | '/about/our-journey'
    | '/about/vision-mission'
    | '/services/360-photography-services'
    | '/services/android-app-development'
    | '/services/app-maintenance-support'
    | '/services/cross-platform-app-development'
    | '/services/custom-cms-development'
    | '/services/custom-software-development'
    | '/services/enterprise-application-development'
    | '/services/flutter-app-development'
    | '/services/ios-app-development'
    | '/services/ipad-app-development'
    | '/services/mobile-app-development'
    | '/services/react-native-app-development'
    | '/services/web-application-development'
    | '/settings/account/notifications'
    | '/settings/account/preferences'
    | '/settings/account/profile'
    | '/settings/account/security'
    | '/settings/account/sessions'
    | '/platform/dashboard'
    | '/org/$slug/console/modules'
    | '/platform/dashboard/organizations/$orgId'
    | '/platform/dashboard/owners/$ownerId'
    | '/org/$slug/console'
    | '/org/$slug/manage'
    | '/org/$slug/workspace'
    | '/platform/dashboard/admins'
    | '/platform/dashboard/organizations'
    | '/platform/dashboard/owners'
    | '/platform/dashboard/support'
    | '/platform/dashboard/users'
    | '/org/$slug/console/members/$memberId'
    | '/org/$slug/console/members/invitations'
    | '/org/$slug/workspace/attendance/analytics'
    | '/org/$slug/workspace/attendance/settings'
    | '/org/$slug/console/members'
    | '/org/$slug/console/roles'
    | '/org/$slug/console/teams'
    | '/org/$slug/workspace/attendance'
    | '/org/$slug/workspace/teams'
    | '/org/$slug/console/modules/communication'
    | '/org/$slug/workspace/communication/channels'
    | '/org/$slug/workspace/communication/dm'
    | '/org/$slug/workspace/communication/channels/$channelId'
    | '/org/$slug/workspace/communication/channels/files'
    | '/org/$slug/workspace/communication/dm/$conversationId'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(public)'
    | '/(authenticated)/platform'
    | '/(authenticated)/settings'
    | '/(public)/about'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(public)/contact'
    | '/(public)/portfolio'
    | '/(public)/'
    | '/(authenticated)/org/$slug'
    | '/(authenticated)/platform/dashboard'
    | '/(auth)/accept-invitation/$id'
    | '/(authenticated)/org/new'
    | '/(public)/about/awards-recognition'
    | '/(public)/about/company-overview'
    | '/(public)/about/leadership-team'
    | '/(public)/about/life-at-workholo-labs'
    | '/(public)/about/nasscom-membership'
    | '/(public)/about/our-journey'
    | '/(public)/about/vision-mission'
    | '/(public)/services/360-photography-services'
    | '/(public)/services/android-app-development'
    | '/(public)/services/app-maintenance-support'
    | '/(public)/services/cross-platform-app-development'
    | '/(public)/services/custom-cms-development'
    | '/(public)/services/custom-software-development'
    | '/(public)/services/enterprise-application-development'
    | '/(public)/services/flutter-app-development'
    | '/(public)/services/ios-app-development'
    | '/(public)/services/ipad-app-development'
    | '/(public)/services/mobile-app-development'
    | '/(public)/services/react-native-app-development'
    | '/(public)/services/web-application-development'
    | '/(authenticated)/org/$slug/console'
    | '/(authenticated)/org/$slug/manage'
    | '/(authenticated)/org/$slug/workspace'
    | '/(authenticated)/settings/account/notifications'
    | '/(authenticated)/settings/account/preferences'
    | '/(authenticated)/settings/account/profile'
    | '/(authenticated)/settings/account/security'
    | '/(authenticated)/settings/account/sessions'
    | '/(authenticated)/platform/dashboard/'
    | '/(authenticated)/org/$slug/console/modules'
    | '/(authenticated)/platform/dashboard/organizations/$orgId'
    | '/(authenticated)/platform/dashboard/owners/$ownerId'
    | '/(authenticated)/org/$slug/console/'
    | '/(authenticated)/org/$slug/manage/'
    | '/(authenticated)/org/$slug/workspace/'
    | '/(authenticated)/platform/dashboard/admins/'
    | '/(authenticated)/platform/dashboard/organizations/'
    | '/(authenticated)/platform/dashboard/owners/'
    | '/(authenticated)/platform/dashboard/support/'
    | '/(authenticated)/platform/dashboard/users/'
    | '/(authenticated)/org/$slug/console/members/$memberId'
    | '/(authenticated)/org/$slug/console/members/invitations'
    | '/(authenticated)/org/$slug/workspace/attendance/analytics'
    | '/(authenticated)/org/$slug/workspace/attendance/settings'
    | '/(authenticated)/org/$slug/console/members/'
    | '/(authenticated)/org/$slug/console/roles/'
    | '/(authenticated)/org/$slug/console/teams/'
    | '/(authenticated)/org/$slug/workspace/attendance/'
    | '/(authenticated)/org/$slug/workspace/teams/'
    | '/(authenticated)/org/$slug/workspace/communication/channels/$channelId'
    | '/(authenticated)/org/$slug/workspace/communication/dm/$conversationId'
    | '/(authenticated)/org/$slug/console/modules/communication/'
    | '/(authenticated)/org/$slug/workspace/communication/channels/'
    | '/(authenticated)/org/$slug/workspace/communication/dm/'
    | '/(authenticated)/org/$slug/workspace/communication/channels/$channelId/'
    | '/(authenticated)/org/$slug/workspace/communication/channels/files/'
    | '/(authenticated)/org/$slug/workspace/communication/dm/$conversationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  authAcceptInvitationIdRoute: typeof authAcceptInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/portfolio': {
      id: '/(public)/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof publicPortfolioRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/contact': {
      id: '/(public)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof publicContactRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/about': {
      id: '/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutRouteRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(authenticated)/settings': {
      id: '/(authenticated)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof authenticatedSettingsRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/platform': {
      id: '/(authenticated)/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof authenticatedPlatformRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(public)/services/web-application-development': {
      id: '/(public)/services/web-application-development'
      path: '/services/web-application-development'
      fullPath: '/services/web-application-development'
      preLoaderRoute: typeof publicServicesWebApplicationDevelopmentRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/services/react-native-app-development': {
      id: '/(public)/services/react-native-app-development'
      path: '/services/react-native-app-development'
      fullPath: '/services/react-native-app-development'
      preLoaderRoute: typeof publicServicesReactNativeAppDevelopmentRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/services/mobile-app-development': {
      id: '/(public)/services/mobile-app-development'
      path: '/services/mobile-app-development'
      fullPath: '/services/mobile-app-development'
      preLoaderRoute: typeof publicServicesMobileAppDevelopmentRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/services/ipad-app-development': {
      id: '/(public)/services/ipad-app-development'
      path: '/services/ipad-app-development'
      fullPath: '/services/ipad-app-development'
      preLoaderRoute: typeof publicServicesIpadAppDevelopmentRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/services/ios-app-development': {
      id: '/(public)/services/ios-app-development'
      path: '/services/ios-app-development'
      fullPath: '/services/ios-app-development'
      preLoaderRoute: typeof publicServicesIosAppDevelopmentRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/services/flutter-app-development': {
      id: '/(public)/services/flutter-app-development'
      path: '/services/flutter-app-development'
      fullPath: '/services/flutter-app-development'
      preLoaderRoute: typeof publicServicesFlutterAppDevelopmentRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/services/enterprise-application-development': {
      id: '/(public)/services/enterprise-application-development'
      path: '/services/enterprise-application-development'
      fullPath: '/services/enterprise-application-development'
      preLoaderRoute: typeof publicServicesEnterpriseApplicationDevelopmentRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/services/custom-software-development': {
      id: '/(public)/services/custom-software-development'
      path: '/services/custom-software-development'
      fullPath: '/services/custom-software-development'
      preLoaderRoute: typeof publicServicesCustomSoftwareDevelopmentRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/services/custom-cms-development': {
      id: '/(public)/services/custom-cms-development'
      path: '/services/custom-cms-development'
      fullPath: '/services/custom-cms-development'
      preLoaderRoute: typeof publicServicesCustomCmsDevelopmentRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/services/cross-platform-app-development': {
      id: '/(public)/services/cross-platform-app-development'
      path: '/services/cross-platform-app-development'
      fullPath: '/services/cross-platform-app-development'
      preLoaderRoute: typeof publicServicesCrossPlatformAppDevelopmentRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/services/app-maintenance-support': {
      id: '/(public)/services/app-maintenance-support'
      path: '/services/app-maintenance-support'
      fullPath: '/services/app-maintenance-support'
      preLoaderRoute: typeof publicServicesAppMaintenanceSupportRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/services/android-app-development': {
      id: '/(public)/services/android-app-development'
      path: '/services/android-app-development'
      fullPath: '/services/android-app-development'
      preLoaderRoute: typeof publicServicesAndroidAppDevelopmentRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/services/360-photography-services': {
      id: '/(public)/services/360-photography-services'
      path: '/services/360-photography-services'
      fullPath: '/services/360-photography-services'
      preLoaderRoute: typeof publicServices360PhotographyServicesRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/about/vision-mission': {
      id: '/(public)/about/vision-mission'
      path: '/vision-mission'
      fullPath: '/about/vision-mission'
      preLoaderRoute: typeof publicAboutVisionMissionRouteImport
      parentRoute: typeof publicAboutRouteRoute
    }
    '/(public)/about/our-journey': {
      id: '/(public)/about/our-journey'
      path: '/our-journey'
      fullPath: '/about/our-journey'
      preLoaderRoute: typeof publicAboutOurJourneyRouteImport
      parentRoute: typeof publicAboutRouteRoute
    }
    '/(public)/about/nasscom-membership': {
      id: '/(public)/about/nasscom-membership'
      path: '/nasscom-membership'
      fullPath: '/about/nasscom-membership'
      preLoaderRoute: typeof publicAboutNasscomMembershipRouteImport
      parentRoute: typeof publicAboutRouteRoute
    }
    '/(public)/about/life-at-workholo-labs': {
      id: '/(public)/about/life-at-workholo-labs'
      path: '/life-at-workholo-labs'
      fullPath: '/about/life-at-workholo-labs'
      preLoaderRoute: typeof publicAboutLifeAtWorkholoLabsRouteImport
      parentRoute: typeof publicAboutRouteRoute
    }
    '/(public)/about/leadership-team': {
      id: '/(public)/about/leadership-team'
      path: '/leadership-team'
      fullPath: '/about/leadership-team'
      preLoaderRoute: typeof publicAboutLeadershipTeamRouteImport
      parentRoute: typeof publicAboutRouteRoute
    }
    '/(public)/about/company-overview': {
      id: '/(public)/about/company-overview'
      path: '/company-overview'
      fullPath: '/about/company-overview'
      preLoaderRoute: typeof publicAboutCompanyOverviewRouteImport
      parentRoute: typeof publicAboutRouteRoute
    }
    '/(public)/about/awards-recognition': {
      id: '/(public)/about/awards-recognition'
      path: '/awards-recognition'
      fullPath: '/about/awards-recognition'
      preLoaderRoute: typeof publicAboutAwardsRecognitionRouteImport
      parentRoute: typeof publicAboutRouteRoute
    }
    '/(authenticated)/org/new': {
      id: '/(authenticated)/org/new'
      path: '/org/new'
      fullPath: '/org/new'
      preLoaderRoute: typeof authenticatedOrgNewRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(auth)/accept-invitation/$id': {
      id: '/(auth)/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof authAcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/platform/dashboard': {
      id: '/(authenticated)/platform/dashboard'
      path: '/dashboard'
      fullPath: '/platform/dashboard'
      preLoaderRoute: typeof authenticatedPlatformDashboardRouteRouteImport
      parentRoute: typeof authenticatedPlatformRouteRoute
    }
    '/(authenticated)/org/$slug': {
      id: '/(authenticated)/org/$slug'
      path: '/org/$slug'
      fullPath: '/org/$slug'
      preLoaderRoute: typeof authenticatedOrgSlugRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/platform/dashboard/': {
      id: '/(authenticated)/platform/dashboard/'
      path: '/'
      fullPath: '/platform/dashboard/'
      preLoaderRoute: typeof authenticatedPlatformDashboardIndexRouteImport
      parentRoute: typeof authenticatedPlatformDashboardRouteRoute
    }
    '/(authenticated)/settings/account/sessions': {
      id: '/(authenticated)/settings/account/sessions'
      path: '/account/sessions'
      fullPath: '/settings/account/sessions'
      preLoaderRoute: typeof authenticatedSettingsAccountSessionsRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/settings/account/security': {
      id: '/(authenticated)/settings/account/security'
      path: '/account/security'
      fullPath: '/settings/account/security'
      preLoaderRoute: typeof authenticatedSettingsAccountSecurityRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/settings/account/profile': {
      id: '/(authenticated)/settings/account/profile'
      path: '/account/profile'
      fullPath: '/settings/account/profile'
      preLoaderRoute: typeof authenticatedSettingsAccountProfileRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/settings/account/preferences': {
      id: '/(authenticated)/settings/account/preferences'
      path: '/account/preferences'
      fullPath: '/settings/account/preferences'
      preLoaderRoute: typeof authenticatedSettingsAccountPreferencesRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/settings/account/notifications': {
      id: '/(authenticated)/settings/account/notifications'
      path: '/account/notifications'
      fullPath: '/settings/account/notifications'
      preLoaderRoute: typeof authenticatedSettingsAccountNotificationsRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/org/$slug/workspace': {
      id: '/(authenticated)/org/$slug/workspace'
      path: '/workspace'
      fullPath: '/org/$slug/workspace'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceRouteRouteImport
      parentRoute: typeof authenticatedOrgSlugRouteRoute
    }
    '/(authenticated)/org/$slug/manage': {
      id: '/(authenticated)/org/$slug/manage'
      path: '/manage'
      fullPath: '/org/$slug/manage'
      preLoaderRoute: typeof authenticatedOrgSlugManageRouteRouteImport
      parentRoute: typeof authenticatedOrgSlugRouteRoute
    }
    '/(authenticated)/org/$slug/console': {
      id: '/(authenticated)/org/$slug/console'
      path: '/console'
      fullPath: '/org/$slug/console'
      preLoaderRoute: typeof authenticatedOrgSlugConsoleRouteRouteImport
      parentRoute: typeof authenticatedOrgSlugRouteRoute
    }
    '/(authenticated)/platform/dashboard/users/': {
      id: '/(authenticated)/platform/dashboard/users/'
      path: '/users'
      fullPath: '/platform/dashboard/users/'
      preLoaderRoute: typeof authenticatedPlatformDashboardUsersIndexRouteImport
      parentRoute: typeof authenticatedPlatformDashboardRouteRoute
    }
    '/(authenticated)/platform/dashboard/support/': {
      id: '/(authenticated)/platform/dashboard/support/'
      path: '/support'
      fullPath: '/platform/dashboard/support/'
      preLoaderRoute: typeof authenticatedPlatformDashboardSupportIndexRouteImport
      parentRoute: typeof authenticatedPlatformDashboardRouteRoute
    }
    '/(authenticated)/platform/dashboard/owners/': {
      id: '/(authenticated)/platform/dashboard/owners/'
      path: '/owners'
      fullPath: '/platform/dashboard/owners/'
      preLoaderRoute: typeof authenticatedPlatformDashboardOwnersIndexRouteImport
      parentRoute: typeof authenticatedPlatformDashboardRouteRoute
    }
    '/(authenticated)/platform/dashboard/organizations/': {
      id: '/(authenticated)/platform/dashboard/organizations/'
      path: '/organizations'
      fullPath: '/platform/dashboard/organizations/'
      preLoaderRoute: typeof authenticatedPlatformDashboardOrganizationsIndexRouteImport
      parentRoute: typeof authenticatedPlatformDashboardRouteRoute
    }
    '/(authenticated)/platform/dashboard/admins/': {
      id: '/(authenticated)/platform/dashboard/admins/'
      path: '/admins'
      fullPath: '/platform/dashboard/admins/'
      preLoaderRoute: typeof authenticatedPlatformDashboardAdminsIndexRouteImport
      parentRoute: typeof authenticatedPlatformDashboardRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/': {
      id: '/(authenticated)/org/$slug/workspace/'
      path: '/'
      fullPath: '/org/$slug/workspace/'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceRouteRoute
    }
    '/(authenticated)/org/$slug/manage/': {
      id: '/(authenticated)/org/$slug/manage/'
      path: '/'
      fullPath: '/org/$slug/manage/'
      preLoaderRoute: typeof authenticatedOrgSlugManageIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugManageRouteRoute
    }
    '/(authenticated)/org/$slug/console/': {
      id: '/(authenticated)/org/$slug/console/'
      path: '/'
      fullPath: '/org/$slug/console/'
      preLoaderRoute: typeof authenticatedOrgSlugConsoleIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugConsoleRouteRoute
    }
    '/(authenticated)/platform/dashboard/owners/$ownerId': {
      id: '/(authenticated)/platform/dashboard/owners/$ownerId'
      path: '/owners/$ownerId'
      fullPath: '/platform/dashboard/owners/$ownerId'
      preLoaderRoute: typeof authenticatedPlatformDashboardOwnersOwnerIdRouteImport
      parentRoute: typeof authenticatedPlatformDashboardRouteRoute
    }
    '/(authenticated)/platform/dashboard/organizations/$orgId': {
      id: '/(authenticated)/platform/dashboard/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/platform/dashboard/organizations/$orgId'
      preLoaderRoute: typeof authenticatedPlatformDashboardOrganizationsOrgIdRouteImport
      parentRoute: typeof authenticatedPlatformDashboardRouteRoute
    }
    '/(authenticated)/org/$slug/console/modules': {
      id: '/(authenticated)/org/$slug/console/modules'
      path: '/modules'
      fullPath: '/org/$slug/console/modules'
      preLoaderRoute: typeof authenticatedOrgSlugConsoleModulesRouteRouteImport
      parentRoute: typeof authenticatedOrgSlugConsoleRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/teams/': {
      id: '/(authenticated)/org/$slug/workspace/teams/'
      path: '/teams'
      fullPath: '/org/$slug/workspace/teams/'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceTeamsIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/attendance/': {
      id: '/(authenticated)/org/$slug/workspace/attendance/'
      path: '/attendance'
      fullPath: '/org/$slug/workspace/attendance/'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceAttendanceIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceRouteRoute
    }
    '/(authenticated)/org/$slug/console/teams/': {
      id: '/(authenticated)/org/$slug/console/teams/'
      path: '/teams'
      fullPath: '/org/$slug/console/teams/'
      preLoaderRoute: typeof authenticatedOrgSlugConsoleTeamsIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugConsoleRouteRoute
    }
    '/(authenticated)/org/$slug/console/roles/': {
      id: '/(authenticated)/org/$slug/console/roles/'
      path: '/roles'
      fullPath: '/org/$slug/console/roles/'
      preLoaderRoute: typeof authenticatedOrgSlugConsoleRolesIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugConsoleRouteRoute
    }
    '/(authenticated)/org/$slug/console/members/': {
      id: '/(authenticated)/org/$slug/console/members/'
      path: '/members'
      fullPath: '/org/$slug/console/members/'
      preLoaderRoute: typeof authenticatedOrgSlugConsoleMembersIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugConsoleRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/attendance/settings': {
      id: '/(authenticated)/org/$slug/workspace/attendance/settings'
      path: '/attendance/settings'
      fullPath: '/org/$slug/workspace/attendance/settings'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceAttendanceSettingsRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/attendance/analytics': {
      id: '/(authenticated)/org/$slug/workspace/attendance/analytics'
      path: '/attendance/analytics'
      fullPath: '/org/$slug/workspace/attendance/analytics'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceAttendanceAnalyticsRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceRouteRoute
    }
    '/(authenticated)/org/$slug/console/members/invitations': {
      id: '/(authenticated)/org/$slug/console/members/invitations'
      path: '/members/invitations'
      fullPath: '/org/$slug/console/members/invitations'
      preLoaderRoute: typeof authenticatedOrgSlugConsoleMembersInvitationsRouteImport
      parentRoute: typeof authenticatedOrgSlugConsoleRouteRoute
    }
    '/(authenticated)/org/$slug/console/members/$memberId': {
      id: '/(authenticated)/org/$slug/console/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/org/$slug/console/members/$memberId'
      preLoaderRoute: typeof authenticatedOrgSlugConsoleMembersMemberIdRouteImport
      parentRoute: typeof authenticatedOrgSlugConsoleRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/communication/dm/': {
      id: '/(authenticated)/org/$slug/workspace/communication/dm/'
      path: '/communication/dm'
      fullPath: '/org/$slug/workspace/communication/dm/'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceCommunicationDmIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/communication/channels/': {
      id: '/(authenticated)/org/$slug/workspace/communication/channels/'
      path: '/communication/channels'
      fullPath: '/org/$slug/workspace/communication/channels/'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceCommunicationChannelsIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceRouteRoute
    }
    '/(authenticated)/org/$slug/console/modules/communication/': {
      id: '/(authenticated)/org/$slug/console/modules/communication/'
      path: '/communication'
      fullPath: '/org/$slug/console/modules/communication/'
      preLoaderRoute: typeof authenticatedOrgSlugConsoleModulesCommunicationIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugConsoleModulesRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/communication/dm/$conversationId': {
      id: '/(authenticated)/org/$slug/workspace/communication/dm/$conversationId'
      path: '/communication/dm/$conversationId'
      fullPath: '/org/$slug/workspace/communication/dm/$conversationId'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/communication/channels/$channelId': {
      id: '/(authenticated)/org/$slug/workspace/communication/channels/$channelId'
      path: '/communication/channels/$channelId'
      fullPath: '/org/$slug/workspace/communication/channels/$channelId'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/communication/dm/$conversationId/': {
      id: '/(authenticated)/org/$slug/workspace/communication/dm/$conversationId/'
      path: '/'
      fullPath: '/org/$slug/workspace/communication/dm/$conversationId/'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceCommunicationDmConversationIdIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/communication/channels/files/': {
      id: '/(authenticated)/org/$slug/workspace/communication/channels/files/'
      path: '/communication/channels/files'
      fullPath: '/org/$slug/workspace/communication/channels/files/'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceCommunicationChannelsFilesIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/communication/channels/$channelId/': {
      id: '/(authenticated)/org/$slug/workspace/communication/channels/$channelId/'
      path: '/'
      fullPath: '/org/$slug/workspace/communication/channels/$channelId/'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRoute
    }
  }
}

interface authenticatedPlatformDashboardRouteRouteChildren {
  authenticatedPlatformDashboardIndexRoute: typeof authenticatedPlatformDashboardIndexRoute
  authenticatedPlatformDashboardOrganizationsOrgIdRoute: typeof authenticatedPlatformDashboardOrganizationsOrgIdRoute
  authenticatedPlatformDashboardOwnersOwnerIdRoute: typeof authenticatedPlatformDashboardOwnersOwnerIdRoute
  authenticatedPlatformDashboardAdminsIndexRoute: typeof authenticatedPlatformDashboardAdminsIndexRoute
  authenticatedPlatformDashboardOrganizationsIndexRoute: typeof authenticatedPlatformDashboardOrganizationsIndexRoute
  authenticatedPlatformDashboardOwnersIndexRoute: typeof authenticatedPlatformDashboardOwnersIndexRoute
  authenticatedPlatformDashboardSupportIndexRoute: typeof authenticatedPlatformDashboardSupportIndexRoute
  authenticatedPlatformDashboardUsersIndexRoute: typeof authenticatedPlatformDashboardUsersIndexRoute
}

const authenticatedPlatformDashboardRouteRouteChildren: authenticatedPlatformDashboardRouteRouteChildren =
  {
    authenticatedPlatformDashboardIndexRoute:
      authenticatedPlatformDashboardIndexRoute,
    authenticatedPlatformDashboardOrganizationsOrgIdRoute:
      authenticatedPlatformDashboardOrganizationsOrgIdRoute,
    authenticatedPlatformDashboardOwnersOwnerIdRoute:
      authenticatedPlatformDashboardOwnersOwnerIdRoute,
    authenticatedPlatformDashboardAdminsIndexRoute:
      authenticatedPlatformDashboardAdminsIndexRoute,
    authenticatedPlatformDashboardOrganizationsIndexRoute:
      authenticatedPlatformDashboardOrganizationsIndexRoute,
    authenticatedPlatformDashboardOwnersIndexRoute:
      authenticatedPlatformDashboardOwnersIndexRoute,
    authenticatedPlatformDashboardSupportIndexRoute:
      authenticatedPlatformDashboardSupportIndexRoute,
    authenticatedPlatformDashboardUsersIndexRoute:
      authenticatedPlatformDashboardUsersIndexRoute,
  }

const authenticatedPlatformDashboardRouteRouteWithChildren =
  authenticatedPlatformDashboardRouteRoute._addFileChildren(
    authenticatedPlatformDashboardRouteRouteChildren,
  )

interface authenticatedPlatformRouteRouteChildren {
  authenticatedPlatformDashboardRouteRoute: typeof authenticatedPlatformDashboardRouteRouteWithChildren
}

const authenticatedPlatformRouteRouteChildren: authenticatedPlatformRouteRouteChildren =
  {
    authenticatedPlatformDashboardRouteRoute:
      authenticatedPlatformDashboardRouteRouteWithChildren,
  }

const authenticatedPlatformRouteRouteWithChildren =
  authenticatedPlatformRouteRoute._addFileChildren(
    authenticatedPlatformRouteRouteChildren,
  )

interface authenticatedSettingsRouteRouteChildren {
  authenticatedSettingsAccountNotificationsRoute: typeof authenticatedSettingsAccountNotificationsRoute
  authenticatedSettingsAccountPreferencesRoute: typeof authenticatedSettingsAccountPreferencesRoute
  authenticatedSettingsAccountProfileRoute: typeof authenticatedSettingsAccountProfileRoute
  authenticatedSettingsAccountSecurityRoute: typeof authenticatedSettingsAccountSecurityRoute
  authenticatedSettingsAccountSessionsRoute: typeof authenticatedSettingsAccountSessionsRoute
}

const authenticatedSettingsRouteRouteChildren: authenticatedSettingsRouteRouteChildren =
  {
    authenticatedSettingsAccountNotificationsRoute:
      authenticatedSettingsAccountNotificationsRoute,
    authenticatedSettingsAccountPreferencesRoute:
      authenticatedSettingsAccountPreferencesRoute,
    authenticatedSettingsAccountProfileRoute:
      authenticatedSettingsAccountProfileRoute,
    authenticatedSettingsAccountSecurityRoute:
      authenticatedSettingsAccountSecurityRoute,
    authenticatedSettingsAccountSessionsRoute:
      authenticatedSettingsAccountSessionsRoute,
  }

const authenticatedSettingsRouteRouteWithChildren =
  authenticatedSettingsRouteRoute._addFileChildren(
    authenticatedSettingsRouteRouteChildren,
  )

interface authenticatedOrgSlugConsoleModulesRouteRouteChildren {
  authenticatedOrgSlugConsoleModulesCommunicationIndexRoute: typeof authenticatedOrgSlugConsoleModulesCommunicationIndexRoute
}

const authenticatedOrgSlugConsoleModulesRouteRouteChildren: authenticatedOrgSlugConsoleModulesRouteRouteChildren =
  {
    authenticatedOrgSlugConsoleModulesCommunicationIndexRoute:
      authenticatedOrgSlugConsoleModulesCommunicationIndexRoute,
  }

const authenticatedOrgSlugConsoleModulesRouteRouteWithChildren =
  authenticatedOrgSlugConsoleModulesRouteRoute._addFileChildren(
    authenticatedOrgSlugConsoleModulesRouteRouteChildren,
  )

interface authenticatedOrgSlugConsoleRouteRouteChildren {
  authenticatedOrgSlugConsoleModulesRouteRoute: typeof authenticatedOrgSlugConsoleModulesRouteRouteWithChildren
  authenticatedOrgSlugConsoleIndexRoute: typeof authenticatedOrgSlugConsoleIndexRoute
  authenticatedOrgSlugConsoleMembersMemberIdRoute: typeof authenticatedOrgSlugConsoleMembersMemberIdRoute
  authenticatedOrgSlugConsoleMembersInvitationsRoute: typeof authenticatedOrgSlugConsoleMembersInvitationsRoute
  authenticatedOrgSlugConsoleMembersIndexRoute: typeof authenticatedOrgSlugConsoleMembersIndexRoute
  authenticatedOrgSlugConsoleRolesIndexRoute: typeof authenticatedOrgSlugConsoleRolesIndexRoute
  authenticatedOrgSlugConsoleTeamsIndexRoute: typeof authenticatedOrgSlugConsoleTeamsIndexRoute
}

const authenticatedOrgSlugConsoleRouteRouteChildren: authenticatedOrgSlugConsoleRouteRouteChildren =
  {
    authenticatedOrgSlugConsoleModulesRouteRoute:
      authenticatedOrgSlugConsoleModulesRouteRouteWithChildren,
    authenticatedOrgSlugConsoleIndexRoute:
      authenticatedOrgSlugConsoleIndexRoute,
    authenticatedOrgSlugConsoleMembersMemberIdRoute:
      authenticatedOrgSlugConsoleMembersMemberIdRoute,
    authenticatedOrgSlugConsoleMembersInvitationsRoute:
      authenticatedOrgSlugConsoleMembersInvitationsRoute,
    authenticatedOrgSlugConsoleMembersIndexRoute:
      authenticatedOrgSlugConsoleMembersIndexRoute,
    authenticatedOrgSlugConsoleRolesIndexRoute:
      authenticatedOrgSlugConsoleRolesIndexRoute,
    authenticatedOrgSlugConsoleTeamsIndexRoute:
      authenticatedOrgSlugConsoleTeamsIndexRoute,
  }

const authenticatedOrgSlugConsoleRouteRouteWithChildren =
  authenticatedOrgSlugConsoleRouteRoute._addFileChildren(
    authenticatedOrgSlugConsoleRouteRouteChildren,
  )

interface authenticatedOrgSlugManageRouteRouteChildren {
  authenticatedOrgSlugManageIndexRoute: typeof authenticatedOrgSlugManageIndexRoute
}

const authenticatedOrgSlugManageRouteRouteChildren: authenticatedOrgSlugManageRouteRouteChildren =
  {
    authenticatedOrgSlugManageIndexRoute: authenticatedOrgSlugManageIndexRoute,
  }

const authenticatedOrgSlugManageRouteRouteWithChildren =
  authenticatedOrgSlugManageRouteRoute._addFileChildren(
    authenticatedOrgSlugManageRouteRouteChildren,
  )

interface authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteChildren {
  authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdIndexRoute: typeof authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdIndexRoute
}

const authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteChildren: authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteChildren =
  {
    authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdIndexRoute:
      authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdIndexRoute,
  }

const authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteWithChildren =
  authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRoute._addFileChildren(
    authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteChildren,
  )

interface authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteChildren {
  authenticatedOrgSlugWorkspaceCommunicationDmConversationIdIndexRoute: typeof authenticatedOrgSlugWorkspaceCommunicationDmConversationIdIndexRoute
}

const authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteChildren: authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteChildren =
  {
    authenticatedOrgSlugWorkspaceCommunicationDmConversationIdIndexRoute:
      authenticatedOrgSlugWorkspaceCommunicationDmConversationIdIndexRoute,
  }

const authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteWithChildren =
  authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRoute._addFileChildren(
    authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteChildren,
  )

interface authenticatedOrgSlugWorkspaceRouteRouteChildren {
  authenticatedOrgSlugWorkspaceIndexRoute: typeof authenticatedOrgSlugWorkspaceIndexRoute
  authenticatedOrgSlugWorkspaceAttendanceAnalyticsRoute: typeof authenticatedOrgSlugWorkspaceAttendanceAnalyticsRoute
  authenticatedOrgSlugWorkspaceAttendanceSettingsRoute: typeof authenticatedOrgSlugWorkspaceAttendanceSettingsRoute
  authenticatedOrgSlugWorkspaceAttendanceIndexRoute: typeof authenticatedOrgSlugWorkspaceAttendanceIndexRoute
  authenticatedOrgSlugWorkspaceTeamsIndexRoute: typeof authenticatedOrgSlugWorkspaceTeamsIndexRoute
  authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRoute: typeof authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteWithChildren
  authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRoute: typeof authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteWithChildren
  authenticatedOrgSlugWorkspaceCommunicationChannelsIndexRoute: typeof authenticatedOrgSlugWorkspaceCommunicationChannelsIndexRoute
  authenticatedOrgSlugWorkspaceCommunicationDmIndexRoute: typeof authenticatedOrgSlugWorkspaceCommunicationDmIndexRoute
  authenticatedOrgSlugWorkspaceCommunicationChannelsFilesIndexRoute: typeof authenticatedOrgSlugWorkspaceCommunicationChannelsFilesIndexRoute
}

const authenticatedOrgSlugWorkspaceRouteRouteChildren: authenticatedOrgSlugWorkspaceRouteRouteChildren =
  {
    authenticatedOrgSlugWorkspaceIndexRoute:
      authenticatedOrgSlugWorkspaceIndexRoute,
    authenticatedOrgSlugWorkspaceAttendanceAnalyticsRoute:
      authenticatedOrgSlugWorkspaceAttendanceAnalyticsRoute,
    authenticatedOrgSlugWorkspaceAttendanceSettingsRoute:
      authenticatedOrgSlugWorkspaceAttendanceSettingsRoute,
    authenticatedOrgSlugWorkspaceAttendanceIndexRoute:
      authenticatedOrgSlugWorkspaceAttendanceIndexRoute,
    authenticatedOrgSlugWorkspaceTeamsIndexRoute:
      authenticatedOrgSlugWorkspaceTeamsIndexRoute,
    authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRoute:
      authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteWithChildren,
    authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRoute:
      authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteWithChildren,
    authenticatedOrgSlugWorkspaceCommunicationChannelsIndexRoute:
      authenticatedOrgSlugWorkspaceCommunicationChannelsIndexRoute,
    authenticatedOrgSlugWorkspaceCommunicationDmIndexRoute:
      authenticatedOrgSlugWorkspaceCommunicationDmIndexRoute,
    authenticatedOrgSlugWorkspaceCommunicationChannelsFilesIndexRoute:
      authenticatedOrgSlugWorkspaceCommunicationChannelsFilesIndexRoute,
  }

const authenticatedOrgSlugWorkspaceRouteRouteWithChildren =
  authenticatedOrgSlugWorkspaceRouteRoute._addFileChildren(
    authenticatedOrgSlugWorkspaceRouteRouteChildren,
  )

interface authenticatedOrgSlugRouteRouteChildren {
  authenticatedOrgSlugConsoleRouteRoute: typeof authenticatedOrgSlugConsoleRouteRouteWithChildren
  authenticatedOrgSlugManageRouteRoute: typeof authenticatedOrgSlugManageRouteRouteWithChildren
  authenticatedOrgSlugWorkspaceRouteRoute: typeof authenticatedOrgSlugWorkspaceRouteRouteWithChildren
}

const authenticatedOrgSlugRouteRouteChildren: authenticatedOrgSlugRouteRouteChildren =
  {
    authenticatedOrgSlugConsoleRouteRoute:
      authenticatedOrgSlugConsoleRouteRouteWithChildren,
    authenticatedOrgSlugManageRouteRoute:
      authenticatedOrgSlugManageRouteRouteWithChildren,
    authenticatedOrgSlugWorkspaceRouteRoute:
      authenticatedOrgSlugWorkspaceRouteRouteWithChildren,
  }

const authenticatedOrgSlugRouteRouteWithChildren =
  authenticatedOrgSlugRouteRoute._addFileChildren(
    authenticatedOrgSlugRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedPlatformRouteRoute: typeof authenticatedPlatformRouteRouteWithChildren
  authenticatedSettingsRouteRoute: typeof authenticatedSettingsRouteRouteWithChildren
  authenticatedOrgSlugRouteRoute: typeof authenticatedOrgSlugRouteRouteWithChildren
  authenticatedOrgNewRoute: typeof authenticatedOrgNewRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedPlatformRouteRoute: authenticatedPlatformRouteRouteWithChildren,
  authenticatedSettingsRouteRoute: authenticatedSettingsRouteRouteWithChildren,
  authenticatedOrgSlugRouteRoute: authenticatedOrgSlugRouteRouteWithChildren,
  authenticatedOrgNewRoute: authenticatedOrgNewRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface publicAboutRouteRouteChildren {
  publicAboutAwardsRecognitionRoute: typeof publicAboutAwardsRecognitionRoute
  publicAboutCompanyOverviewRoute: typeof publicAboutCompanyOverviewRoute
  publicAboutLeadershipTeamRoute: typeof publicAboutLeadershipTeamRoute
  publicAboutLifeAtWorkholoLabsRoute: typeof publicAboutLifeAtWorkholoLabsRoute
  publicAboutNasscomMembershipRoute: typeof publicAboutNasscomMembershipRoute
  publicAboutOurJourneyRoute: typeof publicAboutOurJourneyRoute
  publicAboutVisionMissionRoute: typeof publicAboutVisionMissionRoute
}

const publicAboutRouteRouteChildren: publicAboutRouteRouteChildren = {
  publicAboutAwardsRecognitionRoute: publicAboutAwardsRecognitionRoute,
  publicAboutCompanyOverviewRoute: publicAboutCompanyOverviewRoute,
  publicAboutLeadershipTeamRoute: publicAboutLeadershipTeamRoute,
  publicAboutLifeAtWorkholoLabsRoute: publicAboutLifeAtWorkholoLabsRoute,
  publicAboutNasscomMembershipRoute: publicAboutNasscomMembershipRoute,
  publicAboutOurJourneyRoute: publicAboutOurJourneyRoute,
  publicAboutVisionMissionRoute: publicAboutVisionMissionRoute,
}

const publicAboutRouteRouteWithChildren =
  publicAboutRouteRoute._addFileChildren(publicAboutRouteRouteChildren)

interface publicRouteRouteChildren {
  publicAboutRouteRoute: typeof publicAboutRouteRouteWithChildren
  publicContactRoute: typeof publicContactRoute
  publicPortfolioRoute: typeof publicPortfolioRoute
  publicIndexRoute: typeof publicIndexRoute
  publicServices360PhotographyServicesRoute: typeof publicServices360PhotographyServicesRoute
  publicServicesAndroidAppDevelopmentRoute: typeof publicServicesAndroidAppDevelopmentRoute
  publicServicesAppMaintenanceSupportRoute: typeof publicServicesAppMaintenanceSupportRoute
  publicServicesCrossPlatformAppDevelopmentRoute: typeof publicServicesCrossPlatformAppDevelopmentRoute
  publicServicesCustomCmsDevelopmentRoute: typeof publicServicesCustomCmsDevelopmentRoute
  publicServicesCustomSoftwareDevelopmentRoute: typeof publicServicesCustomSoftwareDevelopmentRoute
  publicServicesEnterpriseApplicationDevelopmentRoute: typeof publicServicesEnterpriseApplicationDevelopmentRoute
  publicServicesFlutterAppDevelopmentRoute: typeof publicServicesFlutterAppDevelopmentRoute
  publicServicesIosAppDevelopmentRoute: typeof publicServicesIosAppDevelopmentRoute
  publicServicesIpadAppDevelopmentRoute: typeof publicServicesIpadAppDevelopmentRoute
  publicServicesMobileAppDevelopmentRoute: typeof publicServicesMobileAppDevelopmentRoute
  publicServicesReactNativeAppDevelopmentRoute: typeof publicServicesReactNativeAppDevelopmentRoute
  publicServicesWebApplicationDevelopmentRoute: typeof publicServicesWebApplicationDevelopmentRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicAboutRouteRoute: publicAboutRouteRouteWithChildren,
  publicContactRoute: publicContactRoute,
  publicPortfolioRoute: publicPortfolioRoute,
  publicIndexRoute: publicIndexRoute,
  publicServices360PhotographyServicesRoute:
    publicServices360PhotographyServicesRoute,
  publicServicesAndroidAppDevelopmentRoute:
    publicServicesAndroidAppDevelopmentRoute,
  publicServicesAppMaintenanceSupportRoute:
    publicServicesAppMaintenanceSupportRoute,
  publicServicesCrossPlatformAppDevelopmentRoute:
    publicServicesCrossPlatformAppDevelopmentRoute,
  publicServicesCustomCmsDevelopmentRoute:
    publicServicesCustomCmsDevelopmentRoute,
  publicServicesCustomSoftwareDevelopmentRoute:
    publicServicesCustomSoftwareDevelopmentRoute,
  publicServicesEnterpriseApplicationDevelopmentRoute:
    publicServicesEnterpriseApplicationDevelopmentRoute,
  publicServicesFlutterAppDevelopmentRoute:
    publicServicesFlutterAppDevelopmentRoute,
  publicServicesIosAppDevelopmentRoute: publicServicesIosAppDevelopmentRoute,
  publicServicesIpadAppDevelopmentRoute: publicServicesIpadAppDevelopmentRoute,
  publicServicesMobileAppDevelopmentRoute:
    publicServicesMobileAppDevelopmentRoute,
  publicServicesReactNativeAppDevelopmentRoute:
    publicServicesReactNativeAppDevelopmentRoute,
  publicServicesWebApplicationDevelopmentRoute:
    publicServicesWebApplicationDevelopmentRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  authAcceptInvitationIdRoute: authAcceptInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
