/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authenticatedSettingsRouteRouteImport } from './routes/(authenticated)/settings/route'
import { Route as authenticatedOrgNewRouteImport } from './routes/(authenticated)/org/new'
import { Route as authAcceptInvitationIdRouteImport } from './routes/(auth)/accept-invitation.$id'
import { Route as authenticatedOrgSlugRouteRouteImport } from './routes/(authenticated)/org/$slug/route'
import { Route as authenticatedOrgSlugIndexRouteImport } from './routes/(authenticated)/org/$slug/index'
import { Route as authenticatedSettingsAccountSessionsRouteImport } from './routes/(authenticated)/settings/account/sessions'
import { Route as authenticatedSettingsAccountSecurityRouteImport } from './routes/(authenticated)/settings/account/security'
import { Route as authenticatedSettingsAccountProfileRouteImport } from './routes/(authenticated)/settings/account/profile'
import { Route as authenticatedSettingsAccountPreferencesRouteImport } from './routes/(authenticated)/settings/account/preferences'
import { Route as authenticatedSettingsAccountNotificationsRouteImport } from './routes/(authenticated)/settings/account/notifications'
import { Route as authenticatedOrgSlugDashboardRouteRouteImport } from './routes/(authenticated)/org/$slug/dashboard/route'
import { Route as authenticatedOrgSlugManageIndexRouteImport } from './routes/(authenticated)/org/$slug/manage/index'
import { Route as authenticatedOrgSlugDashboardIndexRouteImport } from './routes/(authenticated)/org/$slug/dashboard/index'
import { Route as authenticatedOrgSlugDashboardTeamsIndexRouteImport } from './routes/(authenticated)/org/$slug/dashboard/teams/index'
import { Route as authenticatedOrgSlugDashboardMembersIndexRouteImport } from './routes/(authenticated)/org/$slug/dashboard/members/index'
import { Route as authenticatedOrgSlugDashboardAttendanceIndexRouteImport } from './routes/(authenticated)/org/$slug/dashboard/attendance/index'
import { Route as authenticatedOrgSlugmodulesAttendanceIndexRouteImport } from './routes/(authenticated)/org/$slug/(modules)/attendance/index'
import { Route as authenticatedOrgSlugDashboardAttendanceAnalyticsRouteImport } from './routes/(authenticated)/org/$slug/dashboard/attendance/analytics'
import { Route as authenticatedOrgSlugDashboardCommunicationChannelsIndexRouteImport } from './routes/(authenticated)/org/$slug/dashboard/communication/channels/index'
import { Route as authenticatedOrgSlugmodulesCommunicationChannelsIndexRouteImport } from './routes/(authenticated)/org/$slug/(modules)/communication/channels/index'
import { Route as authenticatedOrgSlugmodulesCommunicationChannelsIdRouteRouteImport } from './routes/(authenticated)/org/$slug/(modules)/communication/channels/$id/route'
import { Route as authenticatedOrgSlugmodulesCommunicationChannelsIdIndexRouteImport } from './routes/(authenticated)/org/$slug/(modules)/communication/channels/$id/index'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedSettingsRouteRoute =
  authenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedOrgNewRoute = authenticatedOrgNewRouteImport.update({
  id: '/org/new',
  path: '/org/new',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authAcceptInvitationIdRoute = authAcceptInvitationIdRouteImport.update({
  id: '/(auth)/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedOrgSlugRouteRoute =
  authenticatedOrgSlugRouteRouteImport.update({
    id: '/org/$slug',
    path: '/org/$slug',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedOrgSlugIndexRoute =
  authenticatedOrgSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedOrgSlugRouteRoute,
  } as any)
const authenticatedSettingsAccountSessionsRoute =
  authenticatedSettingsAccountSessionsRouteImport.update({
    id: '/account/sessions',
    path: '/account/sessions',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedSettingsAccountSecurityRoute =
  authenticatedSettingsAccountSecurityRouteImport.update({
    id: '/account/security',
    path: '/account/security',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedSettingsAccountProfileRoute =
  authenticatedSettingsAccountProfileRouteImport.update({
    id: '/account/profile',
    path: '/account/profile',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedSettingsAccountPreferencesRoute =
  authenticatedSettingsAccountPreferencesRouteImport.update({
    id: '/account/preferences',
    path: '/account/preferences',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedSettingsAccountNotificationsRoute =
  authenticatedSettingsAccountNotificationsRouteImport.update({
    id: '/account/notifications',
    path: '/account/notifications',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedOrgSlugDashboardRouteRoute =
  authenticatedOrgSlugDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedOrgSlugRouteRoute,
  } as any)
const authenticatedOrgSlugManageIndexRoute =
  authenticatedOrgSlugManageIndexRouteImport.update({
    id: '/manage/',
    path: '/manage/',
    getParentRoute: () => authenticatedOrgSlugRouteRoute,
  } as any)
const authenticatedOrgSlugDashboardIndexRoute =
  authenticatedOrgSlugDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedOrgSlugDashboardRouteRoute,
  } as any)
const authenticatedOrgSlugDashboardTeamsIndexRoute =
  authenticatedOrgSlugDashboardTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => authenticatedOrgSlugDashboardRouteRoute,
  } as any)
const authenticatedOrgSlugDashboardMembersIndexRoute =
  authenticatedOrgSlugDashboardMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => authenticatedOrgSlugDashboardRouteRoute,
  } as any)
const authenticatedOrgSlugDashboardAttendanceIndexRoute =
  authenticatedOrgSlugDashboardAttendanceIndexRouteImport.update({
    id: '/attendance/',
    path: '/attendance/',
    getParentRoute: () => authenticatedOrgSlugDashboardRouteRoute,
  } as any)
const authenticatedOrgSlugmodulesAttendanceIndexRoute =
  authenticatedOrgSlugmodulesAttendanceIndexRouteImport.update({
    id: '/(modules)/attendance/',
    path: '/attendance/',
    getParentRoute: () => authenticatedOrgSlugRouteRoute,
  } as any)
const authenticatedOrgSlugDashboardAttendanceAnalyticsRoute =
  authenticatedOrgSlugDashboardAttendanceAnalyticsRouteImport.update({
    id: '/attendance/analytics',
    path: '/attendance/analytics',
    getParentRoute: () => authenticatedOrgSlugDashboardRouteRoute,
  } as any)
const authenticatedOrgSlugDashboardCommunicationChannelsIndexRoute =
  authenticatedOrgSlugDashboardCommunicationChannelsIndexRouteImport.update({
    id: '/communication/channels/',
    path: '/communication/channels/',
    getParentRoute: () => authenticatedOrgSlugDashboardRouteRoute,
  } as any)
const authenticatedOrgSlugmodulesCommunicationChannelsIndexRoute =
  authenticatedOrgSlugmodulesCommunicationChannelsIndexRouteImport.update({
    id: '/(modules)/communication/channels/',
    path: '/communication/channels/',
    getParentRoute: () => authenticatedOrgSlugRouteRoute,
  } as any)
const authenticatedOrgSlugmodulesCommunicationChannelsIdRouteRoute =
  authenticatedOrgSlugmodulesCommunicationChannelsIdRouteRouteImport.update({
    id: '/(modules)/communication/channels/$id',
    path: '/communication/channels/$id',
    getParentRoute: () => authenticatedOrgSlugRouteRoute,
  } as any)
const authenticatedOrgSlugmodulesCommunicationChannelsIdIndexRoute =
  authenticatedOrgSlugmodulesCommunicationChannelsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      authenticatedOrgSlugmodulesCommunicationChannelsIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof authenticatedSettingsRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/': typeof publicIndexRoute
  '/org/$slug': typeof authenticatedOrgSlugRouteRouteWithChildren
  '/accept-invitation/$id': typeof authAcceptInvitationIdRoute
  '/org/new': typeof authenticatedOrgNewRoute
  '/org/$slug/dashboard': typeof authenticatedOrgSlugDashboardRouteRouteWithChildren
  '/settings/account/notifications': typeof authenticatedSettingsAccountNotificationsRoute
  '/settings/account/preferences': typeof authenticatedSettingsAccountPreferencesRoute
  '/settings/account/profile': typeof authenticatedSettingsAccountProfileRoute
  '/settings/account/security': typeof authenticatedSettingsAccountSecurityRoute
  '/settings/account/sessions': typeof authenticatedSettingsAccountSessionsRoute
  '/org/$slug/': typeof authenticatedOrgSlugIndexRoute
  '/org/$slug/dashboard/': typeof authenticatedOrgSlugDashboardIndexRoute
  '/org/$slug/manage/': typeof authenticatedOrgSlugManageIndexRoute
  '/org/$slug/dashboard/attendance/analytics': typeof authenticatedOrgSlugDashboardAttendanceAnalyticsRoute
  '/org/$slug/attendance/': typeof authenticatedOrgSlugmodulesAttendanceIndexRoute
  '/org/$slug/dashboard/attendance/': typeof authenticatedOrgSlugDashboardAttendanceIndexRoute
  '/org/$slug/dashboard/members/': typeof authenticatedOrgSlugDashboardMembersIndexRoute
  '/org/$slug/dashboard/teams/': typeof authenticatedOrgSlugDashboardTeamsIndexRoute
  '/org/$slug/communication/channels/$id': typeof authenticatedOrgSlugmodulesCommunicationChannelsIdRouteRouteWithChildren
  '/org/$slug/communication/channels/': typeof authenticatedOrgSlugmodulesCommunicationChannelsIndexRoute
  '/org/$slug/dashboard/communication/channels/': typeof authenticatedOrgSlugDashboardCommunicationChannelsIndexRoute
  '/org/$slug/communication/channels/$id/': typeof authenticatedOrgSlugmodulesCommunicationChannelsIdIndexRoute
}
export interface FileRoutesByTo {
  '/settings': typeof authenticatedSettingsRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/': typeof publicIndexRoute
  '/accept-invitation/$id': typeof authAcceptInvitationIdRoute
  '/org/new': typeof authenticatedOrgNewRoute
  '/settings/account/notifications': typeof authenticatedSettingsAccountNotificationsRoute
  '/settings/account/preferences': typeof authenticatedSettingsAccountPreferencesRoute
  '/settings/account/profile': typeof authenticatedSettingsAccountProfileRoute
  '/settings/account/security': typeof authenticatedSettingsAccountSecurityRoute
  '/settings/account/sessions': typeof authenticatedSettingsAccountSessionsRoute
  '/org/$slug': typeof authenticatedOrgSlugIndexRoute
  '/org/$slug/dashboard': typeof authenticatedOrgSlugDashboardIndexRoute
  '/org/$slug/manage': typeof authenticatedOrgSlugManageIndexRoute
  '/org/$slug/dashboard/attendance/analytics': typeof authenticatedOrgSlugDashboardAttendanceAnalyticsRoute
  '/org/$slug/attendance': typeof authenticatedOrgSlugmodulesAttendanceIndexRoute
  '/org/$slug/dashboard/attendance': typeof authenticatedOrgSlugDashboardAttendanceIndexRoute
  '/org/$slug/dashboard/members': typeof authenticatedOrgSlugDashboardMembersIndexRoute
  '/org/$slug/dashboard/teams': typeof authenticatedOrgSlugDashboardTeamsIndexRoute
  '/org/$slug/communication/channels': typeof authenticatedOrgSlugmodulesCommunicationChannelsIndexRoute
  '/org/$slug/dashboard/communication/channels': typeof authenticatedOrgSlugDashboardCommunicationChannelsIndexRoute
  '/org/$slug/communication/channels/$id': typeof authenticatedOrgSlugmodulesCommunicationChannelsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(authenticated)/settings': typeof authenticatedSettingsRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(public)/': typeof publicIndexRoute
  '/(authenticated)/org/$slug': typeof authenticatedOrgSlugRouteRouteWithChildren
  '/(auth)/accept-invitation/$id': typeof authAcceptInvitationIdRoute
  '/(authenticated)/org/new': typeof authenticatedOrgNewRoute
  '/(authenticated)/org/$slug/dashboard': typeof authenticatedOrgSlugDashboardRouteRouteWithChildren
  '/(authenticated)/settings/account/notifications': typeof authenticatedSettingsAccountNotificationsRoute
  '/(authenticated)/settings/account/preferences': typeof authenticatedSettingsAccountPreferencesRoute
  '/(authenticated)/settings/account/profile': typeof authenticatedSettingsAccountProfileRoute
  '/(authenticated)/settings/account/security': typeof authenticatedSettingsAccountSecurityRoute
  '/(authenticated)/settings/account/sessions': typeof authenticatedSettingsAccountSessionsRoute
  '/(authenticated)/org/$slug/': typeof authenticatedOrgSlugIndexRoute
  '/(authenticated)/org/$slug/dashboard/': typeof authenticatedOrgSlugDashboardIndexRoute
  '/(authenticated)/org/$slug/manage/': typeof authenticatedOrgSlugManageIndexRoute
  '/(authenticated)/org/$slug/dashboard/attendance/analytics': typeof authenticatedOrgSlugDashboardAttendanceAnalyticsRoute
  '/(authenticated)/org/$slug/(modules)/attendance/': typeof authenticatedOrgSlugmodulesAttendanceIndexRoute
  '/(authenticated)/org/$slug/dashboard/attendance/': typeof authenticatedOrgSlugDashboardAttendanceIndexRoute
  '/(authenticated)/org/$slug/dashboard/members/': typeof authenticatedOrgSlugDashboardMembersIndexRoute
  '/(authenticated)/org/$slug/dashboard/teams/': typeof authenticatedOrgSlugDashboardTeamsIndexRoute
  '/(authenticated)/org/$slug/(modules)/communication/channels/$id': typeof authenticatedOrgSlugmodulesCommunicationChannelsIdRouteRouteWithChildren
  '/(authenticated)/org/$slug/(modules)/communication/channels/': typeof authenticatedOrgSlugmodulesCommunicationChannelsIndexRoute
  '/(authenticated)/org/$slug/dashboard/communication/channels/': typeof authenticatedOrgSlugDashboardCommunicationChannelsIndexRoute
  '/(authenticated)/org/$slug/(modules)/communication/channels/$id/': typeof authenticatedOrgSlugmodulesCommunicationChannelsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/login'
    | '/signup'
    | '/'
    | '/org/$slug'
    | '/accept-invitation/$id'
    | '/org/new'
    | '/org/$slug/dashboard'
    | '/settings/account/notifications'
    | '/settings/account/preferences'
    | '/settings/account/profile'
    | '/settings/account/security'
    | '/settings/account/sessions'
    | '/org/$slug/'
    | '/org/$slug/dashboard/'
    | '/org/$slug/manage/'
    | '/org/$slug/dashboard/attendance/analytics'
    | '/org/$slug/attendance/'
    | '/org/$slug/dashboard/attendance/'
    | '/org/$slug/dashboard/members/'
    | '/org/$slug/dashboard/teams/'
    | '/org/$slug/communication/channels/$id'
    | '/org/$slug/communication/channels/'
    | '/org/$slug/dashboard/communication/channels/'
    | '/org/$slug/communication/channels/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/login'
    | '/signup'
    | '/'
    | '/accept-invitation/$id'
    | '/org/new'
    | '/settings/account/notifications'
    | '/settings/account/preferences'
    | '/settings/account/profile'
    | '/settings/account/security'
    | '/settings/account/sessions'
    | '/org/$slug'
    | '/org/$slug/dashboard'
    | '/org/$slug/manage'
    | '/org/$slug/dashboard/attendance/analytics'
    | '/org/$slug/attendance'
    | '/org/$slug/dashboard/attendance'
    | '/org/$slug/dashboard/members'
    | '/org/$slug/dashboard/teams'
    | '/org/$slug/communication/channels'
    | '/org/$slug/dashboard/communication/channels'
    | '/org/$slug/communication/channels/$id'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(public)'
    | '/(authenticated)/settings'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(public)/'
    | '/(authenticated)/org/$slug'
    | '/(auth)/accept-invitation/$id'
    | '/(authenticated)/org/new'
    | '/(authenticated)/org/$slug/dashboard'
    | '/(authenticated)/settings/account/notifications'
    | '/(authenticated)/settings/account/preferences'
    | '/(authenticated)/settings/account/profile'
    | '/(authenticated)/settings/account/security'
    | '/(authenticated)/settings/account/sessions'
    | '/(authenticated)/org/$slug/'
    | '/(authenticated)/org/$slug/dashboard/'
    | '/(authenticated)/org/$slug/manage/'
    | '/(authenticated)/org/$slug/dashboard/attendance/analytics'
    | '/(authenticated)/org/$slug/(modules)/attendance/'
    | '/(authenticated)/org/$slug/dashboard/attendance/'
    | '/(authenticated)/org/$slug/dashboard/members/'
    | '/(authenticated)/org/$slug/dashboard/teams/'
    | '/(authenticated)/org/$slug/(modules)/communication/channels/$id'
    | '/(authenticated)/org/$slug/(modules)/communication/channels/'
    | '/(authenticated)/org/$slug/dashboard/communication/channels/'
    | '/(authenticated)/org/$slug/(modules)/communication/channels/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  authAcceptInvitationIdRoute: typeof authAcceptInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/settings': {
      id: '/(authenticated)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof authenticatedSettingsRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/org/new': {
      id: '/(authenticated)/org/new'
      path: '/org/new'
      fullPath: '/org/new'
      preLoaderRoute: typeof authenticatedOrgNewRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(auth)/accept-invitation/$id': {
      id: '/(auth)/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof authAcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/org/$slug': {
      id: '/(authenticated)/org/$slug'
      path: '/org/$slug'
      fullPath: '/org/$slug'
      preLoaderRoute: typeof authenticatedOrgSlugRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/org/$slug/': {
      id: '/(authenticated)/org/$slug/'
      path: '/'
      fullPath: '/org/$slug/'
      preLoaderRoute: typeof authenticatedOrgSlugIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugRouteRoute
    }
    '/(authenticated)/settings/account/sessions': {
      id: '/(authenticated)/settings/account/sessions'
      path: '/account/sessions'
      fullPath: '/settings/account/sessions'
      preLoaderRoute: typeof authenticatedSettingsAccountSessionsRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/settings/account/security': {
      id: '/(authenticated)/settings/account/security'
      path: '/account/security'
      fullPath: '/settings/account/security'
      preLoaderRoute: typeof authenticatedSettingsAccountSecurityRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/settings/account/profile': {
      id: '/(authenticated)/settings/account/profile'
      path: '/account/profile'
      fullPath: '/settings/account/profile'
      preLoaderRoute: typeof authenticatedSettingsAccountProfileRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/settings/account/preferences': {
      id: '/(authenticated)/settings/account/preferences'
      path: '/account/preferences'
      fullPath: '/settings/account/preferences'
      preLoaderRoute: typeof authenticatedSettingsAccountPreferencesRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/settings/account/notifications': {
      id: '/(authenticated)/settings/account/notifications'
      path: '/account/notifications'
      fullPath: '/settings/account/notifications'
      preLoaderRoute: typeof authenticatedSettingsAccountNotificationsRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/org/$slug/dashboard': {
      id: '/(authenticated)/org/$slug/dashboard'
      path: '/dashboard'
      fullPath: '/org/$slug/dashboard'
      preLoaderRoute: typeof authenticatedOrgSlugDashboardRouteRouteImport
      parentRoute: typeof authenticatedOrgSlugRouteRoute
    }
    '/(authenticated)/org/$slug/manage/': {
      id: '/(authenticated)/org/$slug/manage/'
      path: '/manage'
      fullPath: '/org/$slug/manage/'
      preLoaderRoute: typeof authenticatedOrgSlugManageIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugRouteRoute
    }
    '/(authenticated)/org/$slug/dashboard/': {
      id: '/(authenticated)/org/$slug/dashboard/'
      path: '/'
      fullPath: '/org/$slug/dashboard/'
      preLoaderRoute: typeof authenticatedOrgSlugDashboardIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugDashboardRouteRoute
    }
    '/(authenticated)/org/$slug/dashboard/teams/': {
      id: '/(authenticated)/org/$slug/dashboard/teams/'
      path: '/teams'
      fullPath: '/org/$slug/dashboard/teams/'
      preLoaderRoute: typeof authenticatedOrgSlugDashboardTeamsIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugDashboardRouteRoute
    }
    '/(authenticated)/org/$slug/dashboard/members/': {
      id: '/(authenticated)/org/$slug/dashboard/members/'
      path: '/members'
      fullPath: '/org/$slug/dashboard/members/'
      preLoaderRoute: typeof authenticatedOrgSlugDashboardMembersIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugDashboardRouteRoute
    }
    '/(authenticated)/org/$slug/dashboard/attendance/': {
      id: '/(authenticated)/org/$slug/dashboard/attendance/'
      path: '/attendance'
      fullPath: '/org/$slug/dashboard/attendance/'
      preLoaderRoute: typeof authenticatedOrgSlugDashboardAttendanceIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugDashboardRouteRoute
    }
    '/(authenticated)/org/$slug/(modules)/attendance/': {
      id: '/(authenticated)/org/$slug/(modules)/attendance/'
      path: '/attendance'
      fullPath: '/org/$slug/attendance/'
      preLoaderRoute: typeof authenticatedOrgSlugmodulesAttendanceIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugRouteRoute
    }
    '/(authenticated)/org/$slug/dashboard/attendance/analytics': {
      id: '/(authenticated)/org/$slug/dashboard/attendance/analytics'
      path: '/attendance/analytics'
      fullPath: '/org/$slug/dashboard/attendance/analytics'
      preLoaderRoute: typeof authenticatedOrgSlugDashboardAttendanceAnalyticsRouteImport
      parentRoute: typeof authenticatedOrgSlugDashboardRouteRoute
    }
    '/(authenticated)/org/$slug/dashboard/communication/channels/': {
      id: '/(authenticated)/org/$slug/dashboard/communication/channels/'
      path: '/communication/channels'
      fullPath: '/org/$slug/dashboard/communication/channels/'
      preLoaderRoute: typeof authenticatedOrgSlugDashboardCommunicationChannelsIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugDashboardRouteRoute
    }
    '/(authenticated)/org/$slug/(modules)/communication/channels/': {
      id: '/(authenticated)/org/$slug/(modules)/communication/channels/'
      path: '/communication/channels'
      fullPath: '/org/$slug/communication/channels/'
      preLoaderRoute: typeof authenticatedOrgSlugmodulesCommunicationChannelsIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugRouteRoute
    }
    '/(authenticated)/org/$slug/(modules)/communication/channels/$id': {
      id: '/(authenticated)/org/$slug/(modules)/communication/channels/$id'
      path: '/communication/channels/$id'
      fullPath: '/org/$slug/communication/channels/$id'
      preLoaderRoute: typeof authenticatedOrgSlugmodulesCommunicationChannelsIdRouteRouteImport
      parentRoute: typeof authenticatedOrgSlugRouteRoute
    }
    '/(authenticated)/org/$slug/(modules)/communication/channels/$id/': {
      id: '/(authenticated)/org/$slug/(modules)/communication/channels/$id/'
      path: '/'
      fullPath: '/org/$slug/communication/channels/$id/'
      preLoaderRoute: typeof authenticatedOrgSlugmodulesCommunicationChannelsIdIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugmodulesCommunicationChannelsIdRouteRoute
    }
  }
}

interface authenticatedSettingsRouteRouteChildren {
  authenticatedSettingsAccountNotificationsRoute: typeof authenticatedSettingsAccountNotificationsRoute
  authenticatedSettingsAccountPreferencesRoute: typeof authenticatedSettingsAccountPreferencesRoute
  authenticatedSettingsAccountProfileRoute: typeof authenticatedSettingsAccountProfileRoute
  authenticatedSettingsAccountSecurityRoute: typeof authenticatedSettingsAccountSecurityRoute
  authenticatedSettingsAccountSessionsRoute: typeof authenticatedSettingsAccountSessionsRoute
}

const authenticatedSettingsRouteRouteChildren: authenticatedSettingsRouteRouteChildren =
  {
    authenticatedSettingsAccountNotificationsRoute:
      authenticatedSettingsAccountNotificationsRoute,
    authenticatedSettingsAccountPreferencesRoute:
      authenticatedSettingsAccountPreferencesRoute,
    authenticatedSettingsAccountProfileRoute:
      authenticatedSettingsAccountProfileRoute,
    authenticatedSettingsAccountSecurityRoute:
      authenticatedSettingsAccountSecurityRoute,
    authenticatedSettingsAccountSessionsRoute:
      authenticatedSettingsAccountSessionsRoute,
  }

const authenticatedSettingsRouteRouteWithChildren =
  authenticatedSettingsRouteRoute._addFileChildren(
    authenticatedSettingsRouteRouteChildren,
  )

interface authenticatedOrgSlugDashboardRouteRouteChildren {
  authenticatedOrgSlugDashboardIndexRoute: typeof authenticatedOrgSlugDashboardIndexRoute
  authenticatedOrgSlugDashboardAttendanceAnalyticsRoute: typeof authenticatedOrgSlugDashboardAttendanceAnalyticsRoute
  authenticatedOrgSlugDashboardAttendanceIndexRoute: typeof authenticatedOrgSlugDashboardAttendanceIndexRoute
  authenticatedOrgSlugDashboardMembersIndexRoute: typeof authenticatedOrgSlugDashboardMembersIndexRoute
  authenticatedOrgSlugDashboardTeamsIndexRoute: typeof authenticatedOrgSlugDashboardTeamsIndexRoute
  authenticatedOrgSlugDashboardCommunicationChannelsIndexRoute: typeof authenticatedOrgSlugDashboardCommunicationChannelsIndexRoute
}

const authenticatedOrgSlugDashboardRouteRouteChildren: authenticatedOrgSlugDashboardRouteRouteChildren =
  {
    authenticatedOrgSlugDashboardIndexRoute:
      authenticatedOrgSlugDashboardIndexRoute,
    authenticatedOrgSlugDashboardAttendanceAnalyticsRoute:
      authenticatedOrgSlugDashboardAttendanceAnalyticsRoute,
    authenticatedOrgSlugDashboardAttendanceIndexRoute:
      authenticatedOrgSlugDashboardAttendanceIndexRoute,
    authenticatedOrgSlugDashboardMembersIndexRoute:
      authenticatedOrgSlugDashboardMembersIndexRoute,
    authenticatedOrgSlugDashboardTeamsIndexRoute:
      authenticatedOrgSlugDashboardTeamsIndexRoute,
    authenticatedOrgSlugDashboardCommunicationChannelsIndexRoute:
      authenticatedOrgSlugDashboardCommunicationChannelsIndexRoute,
  }

const authenticatedOrgSlugDashboardRouteRouteWithChildren =
  authenticatedOrgSlugDashboardRouteRoute._addFileChildren(
    authenticatedOrgSlugDashboardRouteRouteChildren,
  )

interface authenticatedOrgSlugmodulesCommunicationChannelsIdRouteRouteChildren {
  authenticatedOrgSlugmodulesCommunicationChannelsIdIndexRoute: typeof authenticatedOrgSlugmodulesCommunicationChannelsIdIndexRoute
}

const authenticatedOrgSlugmodulesCommunicationChannelsIdRouteRouteChildren: authenticatedOrgSlugmodulesCommunicationChannelsIdRouteRouteChildren =
  {
    authenticatedOrgSlugmodulesCommunicationChannelsIdIndexRoute:
      authenticatedOrgSlugmodulesCommunicationChannelsIdIndexRoute,
  }

const authenticatedOrgSlugmodulesCommunicationChannelsIdRouteRouteWithChildren =
  authenticatedOrgSlugmodulesCommunicationChannelsIdRouteRoute._addFileChildren(
    authenticatedOrgSlugmodulesCommunicationChannelsIdRouteRouteChildren,
  )

interface authenticatedOrgSlugRouteRouteChildren {
  authenticatedOrgSlugDashboardRouteRoute: typeof authenticatedOrgSlugDashboardRouteRouteWithChildren
  authenticatedOrgSlugIndexRoute: typeof authenticatedOrgSlugIndexRoute
  authenticatedOrgSlugManageIndexRoute: typeof authenticatedOrgSlugManageIndexRoute
  authenticatedOrgSlugmodulesAttendanceIndexRoute: typeof authenticatedOrgSlugmodulesAttendanceIndexRoute
  authenticatedOrgSlugmodulesCommunicationChannelsIdRouteRoute: typeof authenticatedOrgSlugmodulesCommunicationChannelsIdRouteRouteWithChildren
  authenticatedOrgSlugmodulesCommunicationChannelsIndexRoute: typeof authenticatedOrgSlugmodulesCommunicationChannelsIndexRoute
}

const authenticatedOrgSlugRouteRouteChildren: authenticatedOrgSlugRouteRouteChildren =
  {
    authenticatedOrgSlugDashboardRouteRoute:
      authenticatedOrgSlugDashboardRouteRouteWithChildren,
    authenticatedOrgSlugIndexRoute: authenticatedOrgSlugIndexRoute,
    authenticatedOrgSlugManageIndexRoute: authenticatedOrgSlugManageIndexRoute,
    authenticatedOrgSlugmodulesAttendanceIndexRoute:
      authenticatedOrgSlugmodulesAttendanceIndexRoute,
    authenticatedOrgSlugmodulesCommunicationChannelsIdRouteRoute:
      authenticatedOrgSlugmodulesCommunicationChannelsIdRouteRouteWithChildren,
    authenticatedOrgSlugmodulesCommunicationChannelsIndexRoute:
      authenticatedOrgSlugmodulesCommunicationChannelsIndexRoute,
  }

const authenticatedOrgSlugRouteRouteWithChildren =
  authenticatedOrgSlugRouteRoute._addFileChildren(
    authenticatedOrgSlugRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedSettingsRouteRoute: typeof authenticatedSettingsRouteRouteWithChildren
  authenticatedOrgSlugRouteRoute: typeof authenticatedOrgSlugRouteRouteWithChildren
  authenticatedOrgNewRoute: typeof authenticatedOrgNewRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedSettingsRouteRoute: authenticatedSettingsRouteRouteWithChildren,
  authenticatedOrgSlugRouteRoute: authenticatedOrgSlugRouteRouteWithChildren,
  authenticatedOrgNewRoute: authenticatedOrgNewRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  authAcceptInvitationIdRoute: authAcceptInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
