/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authenticatedSettingsRouteRouteImport } from './routes/(authenticated)/settings/route'
import { Route as authenticatedOrgNewRouteImport } from './routes/(authenticated)/org/new'
import { Route as authAcceptInvitationIdRouteImport } from './routes/(auth)/accept-invitation.$id'
import { Route as authenticatedOrgSlugRouteRouteImport } from './routes/(authenticated)/org/$slug/route'
import { Route as authenticatedSettingsAccountSessionsRouteImport } from './routes/(authenticated)/settings/account/sessions'
import { Route as authenticatedSettingsAccountSecurityRouteImport } from './routes/(authenticated)/settings/account/security'
import { Route as authenticatedSettingsAccountProfileRouteImport } from './routes/(authenticated)/settings/account/profile'
import { Route as authenticatedSettingsAccountPreferencesRouteImport } from './routes/(authenticated)/settings/account/preferences'
import { Route as authenticatedSettingsAccountNotificationsRouteImport } from './routes/(authenticated)/settings/account/notifications'
import { Route as authenticatedOrgSlugWorkspaceRouteRouteImport } from './routes/(authenticated)/org/$slug/workspace/route'
import { Route as authenticatedOrgSlugManageRouteRouteImport } from './routes/(authenticated)/org/$slug/manage/route'
import { Route as authenticatedOrgSlugConsoleRouteRouteImport } from './routes/(authenticated)/org/$slug/console/route'
import { Route as authenticatedOrgSlugWorkspaceIndexRouteImport } from './routes/(authenticated)/org/$slug/workspace/index'
import { Route as authenticatedOrgSlugManageIndexRouteImport } from './routes/(authenticated)/org/$slug/manage/index'
import { Route as authenticatedOrgSlugConsoleIndexRouteImport } from './routes/(authenticated)/org/$slug/console/index'
import { Route as authenticatedOrgSlugConsoleModulesRouteRouteImport } from './routes/(authenticated)/org/$slug/console/modules/route'
import { Route as authenticatedOrgSlugWorkspaceTeamsIndexRouteImport } from './routes/(authenticated)/org/$slug/workspace/teams/index'
import { Route as authenticatedOrgSlugWorkspaceAttendanceIndexRouteImport } from './routes/(authenticated)/org/$slug/workspace/attendance/index'
import { Route as authenticatedOrgSlugConsoleTeamsIndexRouteImport } from './routes/(authenticated)/org/$slug/console/teams/index'
import { Route as authenticatedOrgSlugConsoleMembersIndexRouteImport } from './routes/(authenticated)/org/$slug/console/members/index'
import { Route as authenticatedOrgSlugWorkspaceAttendanceSettingsRouteImport } from './routes/(authenticated)/org/$slug/workspace/attendance/settings'
import { Route as authenticatedOrgSlugWorkspaceAttendanceAnalyticsRouteImport } from './routes/(authenticated)/org/$slug/workspace/attendance/analytics'
import { Route as authenticatedOrgSlugConsoleMembersInvitationsRouteImport } from './routes/(authenticated)/org/$slug/console/members/invitations'
import { Route as authenticatedOrgSlugConsoleMembersMemberIdRouteImport } from './routes/(authenticated)/org/$slug/console/members/$memberId'
import { Route as authenticatedOrgSlugWorkspaceCommunicationDmIndexRouteImport } from './routes/(authenticated)/org/$slug/workspace/communication/dm/index'
import { Route as authenticatedOrgSlugWorkspaceCommunicationChannelsIndexRouteImport } from './routes/(authenticated)/org/$slug/workspace/communication/channels/index'
import { Route as authenticatedOrgSlugConsoleModulesCommunicationIndexRouteImport } from './routes/(authenticated)/org/$slug/console/modules/communication/index'
import { Route as authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteImport } from './routes/(authenticated)/org/$slug/workspace/communication/dm/$conversationId/route'
import { Route as authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteImport } from './routes/(authenticated)/org/$slug/workspace/communication/channels/$channelId/route'
import { Route as authenticatedOrgSlugWorkspaceCommunicationDmConversationIdIndexRouteImport } from './routes/(authenticated)/org/$slug/workspace/communication/dm/$conversationId/index'
import { Route as authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdIndexRouteImport } from './routes/(authenticated)/org/$slug/workspace/communication/channels/$channelId/index'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedSettingsRouteRoute =
  authenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedOrgNewRoute = authenticatedOrgNewRouteImport.update({
  id: '/org/new',
  path: '/org/new',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authAcceptInvitationIdRoute = authAcceptInvitationIdRouteImport.update({
  id: '/(auth)/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedOrgSlugRouteRoute =
  authenticatedOrgSlugRouteRouteImport.update({
    id: '/org/$slug',
    path: '/org/$slug',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedSettingsAccountSessionsRoute =
  authenticatedSettingsAccountSessionsRouteImport.update({
    id: '/account/sessions',
    path: '/account/sessions',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedSettingsAccountSecurityRoute =
  authenticatedSettingsAccountSecurityRouteImport.update({
    id: '/account/security',
    path: '/account/security',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedSettingsAccountProfileRoute =
  authenticatedSettingsAccountProfileRouteImport.update({
    id: '/account/profile',
    path: '/account/profile',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedSettingsAccountPreferencesRoute =
  authenticatedSettingsAccountPreferencesRouteImport.update({
    id: '/account/preferences',
    path: '/account/preferences',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedSettingsAccountNotificationsRoute =
  authenticatedSettingsAccountNotificationsRouteImport.update({
    id: '/account/notifications',
    path: '/account/notifications',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedOrgSlugWorkspaceRouteRoute =
  authenticatedOrgSlugWorkspaceRouteRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => authenticatedOrgSlugRouteRoute,
  } as any)
const authenticatedOrgSlugManageRouteRoute =
  authenticatedOrgSlugManageRouteRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => authenticatedOrgSlugRouteRoute,
  } as any)
const authenticatedOrgSlugConsoleRouteRoute =
  authenticatedOrgSlugConsoleRouteRouteImport.update({
    id: '/console',
    path: '/console',
    getParentRoute: () => authenticatedOrgSlugRouteRoute,
  } as any)
const authenticatedOrgSlugWorkspaceIndexRoute =
  authenticatedOrgSlugWorkspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedOrgSlugWorkspaceRouteRoute,
  } as any)
const authenticatedOrgSlugManageIndexRoute =
  authenticatedOrgSlugManageIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedOrgSlugManageRouteRoute,
  } as any)
const authenticatedOrgSlugConsoleIndexRoute =
  authenticatedOrgSlugConsoleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedOrgSlugConsoleRouteRoute,
  } as any)
const authenticatedOrgSlugConsoleModulesRouteRoute =
  authenticatedOrgSlugConsoleModulesRouteRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => authenticatedOrgSlugConsoleRouteRoute,
  } as any)
const authenticatedOrgSlugWorkspaceTeamsIndexRoute =
  authenticatedOrgSlugWorkspaceTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => authenticatedOrgSlugWorkspaceRouteRoute,
  } as any)
const authenticatedOrgSlugWorkspaceAttendanceIndexRoute =
  authenticatedOrgSlugWorkspaceAttendanceIndexRouteImport.update({
    id: '/attendance/',
    path: '/attendance/',
    getParentRoute: () => authenticatedOrgSlugWorkspaceRouteRoute,
  } as any)
const authenticatedOrgSlugConsoleTeamsIndexRoute =
  authenticatedOrgSlugConsoleTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => authenticatedOrgSlugConsoleRouteRoute,
  } as any)
const authenticatedOrgSlugConsoleMembersIndexRoute =
  authenticatedOrgSlugConsoleMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => authenticatedOrgSlugConsoleRouteRoute,
  } as any)
const authenticatedOrgSlugWorkspaceAttendanceSettingsRoute =
  authenticatedOrgSlugWorkspaceAttendanceSettingsRouteImport.update({
    id: '/attendance/settings',
    path: '/attendance/settings',
    getParentRoute: () => authenticatedOrgSlugWorkspaceRouteRoute,
  } as any)
const authenticatedOrgSlugWorkspaceAttendanceAnalyticsRoute =
  authenticatedOrgSlugWorkspaceAttendanceAnalyticsRouteImport.update({
    id: '/attendance/analytics',
    path: '/attendance/analytics',
    getParentRoute: () => authenticatedOrgSlugWorkspaceRouteRoute,
  } as any)
const authenticatedOrgSlugConsoleMembersInvitationsRoute =
  authenticatedOrgSlugConsoleMembersInvitationsRouteImport.update({
    id: '/members/invitations',
    path: '/members/invitations',
    getParentRoute: () => authenticatedOrgSlugConsoleRouteRoute,
  } as any)
const authenticatedOrgSlugConsoleMembersMemberIdRoute =
  authenticatedOrgSlugConsoleMembersMemberIdRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => authenticatedOrgSlugConsoleRouteRoute,
  } as any)
const authenticatedOrgSlugWorkspaceCommunicationDmIndexRoute =
  authenticatedOrgSlugWorkspaceCommunicationDmIndexRouteImport.update({
    id: '/communication/dm/',
    path: '/communication/dm/',
    getParentRoute: () => authenticatedOrgSlugWorkspaceRouteRoute,
  } as any)
const authenticatedOrgSlugWorkspaceCommunicationChannelsIndexRoute =
  authenticatedOrgSlugWorkspaceCommunicationChannelsIndexRouteImport.update({
    id: '/communication/channels/',
    path: '/communication/channels/',
    getParentRoute: () => authenticatedOrgSlugWorkspaceRouteRoute,
  } as any)
const authenticatedOrgSlugConsoleModulesCommunicationIndexRoute =
  authenticatedOrgSlugConsoleModulesCommunicationIndexRouteImport.update({
    id: '/communication/',
    path: '/communication/',
    getParentRoute: () => authenticatedOrgSlugConsoleModulesRouteRoute,
  } as any)
const authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRoute =
  authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteImport.update(
    {
      id: '/communication/dm/$conversationId',
      path: '/communication/dm/$conversationId',
      getParentRoute: () => authenticatedOrgSlugWorkspaceRouteRoute,
    } as any,
  )
const authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRoute =
  authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteImport.update(
    {
      id: '/communication/channels/$channelId',
      path: '/communication/channels/$channelId',
      getParentRoute: () => authenticatedOrgSlugWorkspaceRouteRoute,
    } as any,
  )
const authenticatedOrgSlugWorkspaceCommunicationDmConversationIdIndexRoute =
  authenticatedOrgSlugWorkspaceCommunicationDmConversationIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRoute,
    } as any,
  )
const authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdIndexRoute =
  authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/settings': typeof authenticatedSettingsRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/': typeof publicIndexRoute
  '/org/$slug': typeof authenticatedOrgSlugRouteRouteWithChildren
  '/accept-invitation/$id': typeof authAcceptInvitationIdRoute
  '/org/new': typeof authenticatedOrgNewRoute
  '/org/$slug/console': typeof authenticatedOrgSlugConsoleRouteRouteWithChildren
  '/org/$slug/manage': typeof authenticatedOrgSlugManageRouteRouteWithChildren
  '/org/$slug/workspace': typeof authenticatedOrgSlugWorkspaceRouteRouteWithChildren
  '/settings/account/notifications': typeof authenticatedSettingsAccountNotificationsRoute
  '/settings/account/preferences': typeof authenticatedSettingsAccountPreferencesRoute
  '/settings/account/profile': typeof authenticatedSettingsAccountProfileRoute
  '/settings/account/security': typeof authenticatedSettingsAccountSecurityRoute
  '/settings/account/sessions': typeof authenticatedSettingsAccountSessionsRoute
  '/org/$slug/console/modules': typeof authenticatedOrgSlugConsoleModulesRouteRouteWithChildren
  '/org/$slug/console/': typeof authenticatedOrgSlugConsoleIndexRoute
  '/org/$slug/manage/': typeof authenticatedOrgSlugManageIndexRoute
  '/org/$slug/workspace/': typeof authenticatedOrgSlugWorkspaceIndexRoute
  '/org/$slug/console/members/$memberId': typeof authenticatedOrgSlugConsoleMembersMemberIdRoute
  '/org/$slug/console/members/invitations': typeof authenticatedOrgSlugConsoleMembersInvitationsRoute
  '/org/$slug/workspace/attendance/analytics': typeof authenticatedOrgSlugWorkspaceAttendanceAnalyticsRoute
  '/org/$slug/workspace/attendance/settings': typeof authenticatedOrgSlugWorkspaceAttendanceSettingsRoute
  '/org/$slug/console/members/': typeof authenticatedOrgSlugConsoleMembersIndexRoute
  '/org/$slug/console/teams/': typeof authenticatedOrgSlugConsoleTeamsIndexRoute
  '/org/$slug/workspace/attendance/': typeof authenticatedOrgSlugWorkspaceAttendanceIndexRoute
  '/org/$slug/workspace/teams/': typeof authenticatedOrgSlugWorkspaceTeamsIndexRoute
  '/org/$slug/workspace/communication/channels/$channelId': typeof authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteWithChildren
  '/org/$slug/workspace/communication/dm/$conversationId': typeof authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteWithChildren
  '/org/$slug/console/modules/communication/': typeof authenticatedOrgSlugConsoleModulesCommunicationIndexRoute
  '/org/$slug/workspace/communication/channels/': typeof authenticatedOrgSlugWorkspaceCommunicationChannelsIndexRoute
  '/org/$slug/workspace/communication/dm/': typeof authenticatedOrgSlugWorkspaceCommunicationDmIndexRoute
  '/org/$slug/workspace/communication/channels/$channelId/': typeof authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdIndexRoute
  '/org/$slug/workspace/communication/dm/$conversationId/': typeof authenticatedOrgSlugWorkspaceCommunicationDmConversationIdIndexRoute
}
export interface FileRoutesByTo {
  '/settings': typeof authenticatedSettingsRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/': typeof publicIndexRoute
  '/org/$slug': typeof authenticatedOrgSlugRouteRouteWithChildren
  '/accept-invitation/$id': typeof authAcceptInvitationIdRoute
  '/org/new': typeof authenticatedOrgNewRoute
  '/settings/account/notifications': typeof authenticatedSettingsAccountNotificationsRoute
  '/settings/account/preferences': typeof authenticatedSettingsAccountPreferencesRoute
  '/settings/account/profile': typeof authenticatedSettingsAccountProfileRoute
  '/settings/account/security': typeof authenticatedSettingsAccountSecurityRoute
  '/settings/account/sessions': typeof authenticatedSettingsAccountSessionsRoute
  '/org/$slug/console/modules': typeof authenticatedOrgSlugConsoleModulesRouteRouteWithChildren
  '/org/$slug/console': typeof authenticatedOrgSlugConsoleIndexRoute
  '/org/$slug/manage': typeof authenticatedOrgSlugManageIndexRoute
  '/org/$slug/workspace': typeof authenticatedOrgSlugWorkspaceIndexRoute
  '/org/$slug/console/members/$memberId': typeof authenticatedOrgSlugConsoleMembersMemberIdRoute
  '/org/$slug/console/members/invitations': typeof authenticatedOrgSlugConsoleMembersInvitationsRoute
  '/org/$slug/workspace/attendance/analytics': typeof authenticatedOrgSlugWorkspaceAttendanceAnalyticsRoute
  '/org/$slug/workspace/attendance/settings': typeof authenticatedOrgSlugWorkspaceAttendanceSettingsRoute
  '/org/$slug/console/members': typeof authenticatedOrgSlugConsoleMembersIndexRoute
  '/org/$slug/console/teams': typeof authenticatedOrgSlugConsoleTeamsIndexRoute
  '/org/$slug/workspace/attendance': typeof authenticatedOrgSlugWorkspaceAttendanceIndexRoute
  '/org/$slug/workspace/teams': typeof authenticatedOrgSlugWorkspaceTeamsIndexRoute
  '/org/$slug/console/modules/communication': typeof authenticatedOrgSlugConsoleModulesCommunicationIndexRoute
  '/org/$slug/workspace/communication/channels': typeof authenticatedOrgSlugWorkspaceCommunicationChannelsIndexRoute
  '/org/$slug/workspace/communication/dm': typeof authenticatedOrgSlugWorkspaceCommunicationDmIndexRoute
  '/org/$slug/workspace/communication/channels/$channelId': typeof authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdIndexRoute
  '/org/$slug/workspace/communication/dm/$conversationId': typeof authenticatedOrgSlugWorkspaceCommunicationDmConversationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(authenticated)/settings': typeof authenticatedSettingsRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(public)/': typeof publicIndexRoute
  '/(authenticated)/org/$slug': typeof authenticatedOrgSlugRouteRouteWithChildren
  '/(auth)/accept-invitation/$id': typeof authAcceptInvitationIdRoute
  '/(authenticated)/org/new': typeof authenticatedOrgNewRoute
  '/(authenticated)/org/$slug/console': typeof authenticatedOrgSlugConsoleRouteRouteWithChildren
  '/(authenticated)/org/$slug/manage': typeof authenticatedOrgSlugManageRouteRouteWithChildren
  '/(authenticated)/org/$slug/workspace': typeof authenticatedOrgSlugWorkspaceRouteRouteWithChildren
  '/(authenticated)/settings/account/notifications': typeof authenticatedSettingsAccountNotificationsRoute
  '/(authenticated)/settings/account/preferences': typeof authenticatedSettingsAccountPreferencesRoute
  '/(authenticated)/settings/account/profile': typeof authenticatedSettingsAccountProfileRoute
  '/(authenticated)/settings/account/security': typeof authenticatedSettingsAccountSecurityRoute
  '/(authenticated)/settings/account/sessions': typeof authenticatedSettingsAccountSessionsRoute
  '/(authenticated)/org/$slug/console/modules': typeof authenticatedOrgSlugConsoleModulesRouteRouteWithChildren
  '/(authenticated)/org/$slug/console/': typeof authenticatedOrgSlugConsoleIndexRoute
  '/(authenticated)/org/$slug/manage/': typeof authenticatedOrgSlugManageIndexRoute
  '/(authenticated)/org/$slug/workspace/': typeof authenticatedOrgSlugWorkspaceIndexRoute
  '/(authenticated)/org/$slug/console/members/$memberId': typeof authenticatedOrgSlugConsoleMembersMemberIdRoute
  '/(authenticated)/org/$slug/console/members/invitations': typeof authenticatedOrgSlugConsoleMembersInvitationsRoute
  '/(authenticated)/org/$slug/workspace/attendance/analytics': typeof authenticatedOrgSlugWorkspaceAttendanceAnalyticsRoute
  '/(authenticated)/org/$slug/workspace/attendance/settings': typeof authenticatedOrgSlugWorkspaceAttendanceSettingsRoute
  '/(authenticated)/org/$slug/console/members/': typeof authenticatedOrgSlugConsoleMembersIndexRoute
  '/(authenticated)/org/$slug/console/teams/': typeof authenticatedOrgSlugConsoleTeamsIndexRoute
  '/(authenticated)/org/$slug/workspace/attendance/': typeof authenticatedOrgSlugWorkspaceAttendanceIndexRoute
  '/(authenticated)/org/$slug/workspace/teams/': typeof authenticatedOrgSlugWorkspaceTeamsIndexRoute
  '/(authenticated)/org/$slug/workspace/communication/channels/$channelId': typeof authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteWithChildren
  '/(authenticated)/org/$slug/workspace/communication/dm/$conversationId': typeof authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteWithChildren
  '/(authenticated)/org/$slug/console/modules/communication/': typeof authenticatedOrgSlugConsoleModulesCommunicationIndexRoute
  '/(authenticated)/org/$slug/workspace/communication/channels/': typeof authenticatedOrgSlugWorkspaceCommunicationChannelsIndexRoute
  '/(authenticated)/org/$slug/workspace/communication/dm/': typeof authenticatedOrgSlugWorkspaceCommunicationDmIndexRoute
  '/(authenticated)/org/$slug/workspace/communication/channels/$channelId/': typeof authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdIndexRoute
  '/(authenticated)/org/$slug/workspace/communication/dm/$conversationId/': typeof authenticatedOrgSlugWorkspaceCommunicationDmConversationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/login'
    | '/signup'
    | '/'
    | '/org/$slug'
    | '/accept-invitation/$id'
    | '/org/new'
    | '/org/$slug/console'
    | '/org/$slug/manage'
    | '/org/$slug/workspace'
    | '/settings/account/notifications'
    | '/settings/account/preferences'
    | '/settings/account/profile'
    | '/settings/account/security'
    | '/settings/account/sessions'
    | '/org/$slug/console/modules'
    | '/org/$slug/console/'
    | '/org/$slug/manage/'
    | '/org/$slug/workspace/'
    | '/org/$slug/console/members/$memberId'
    | '/org/$slug/console/members/invitations'
    | '/org/$slug/workspace/attendance/analytics'
    | '/org/$slug/workspace/attendance/settings'
    | '/org/$slug/console/members/'
    | '/org/$slug/console/teams/'
    | '/org/$slug/workspace/attendance/'
    | '/org/$slug/workspace/teams/'
    | '/org/$slug/workspace/communication/channels/$channelId'
    | '/org/$slug/workspace/communication/dm/$conversationId'
    | '/org/$slug/console/modules/communication/'
    | '/org/$slug/workspace/communication/channels/'
    | '/org/$slug/workspace/communication/dm/'
    | '/org/$slug/workspace/communication/channels/$channelId/'
    | '/org/$slug/workspace/communication/dm/$conversationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/login'
    | '/signup'
    | '/'
    | '/org/$slug'
    | '/accept-invitation/$id'
    | '/org/new'
    | '/settings/account/notifications'
    | '/settings/account/preferences'
    | '/settings/account/profile'
    | '/settings/account/security'
    | '/settings/account/sessions'
    | '/org/$slug/console/modules'
    | '/org/$slug/console'
    | '/org/$slug/manage'
    | '/org/$slug/workspace'
    | '/org/$slug/console/members/$memberId'
    | '/org/$slug/console/members/invitations'
    | '/org/$slug/workspace/attendance/analytics'
    | '/org/$slug/workspace/attendance/settings'
    | '/org/$slug/console/members'
    | '/org/$slug/console/teams'
    | '/org/$slug/workspace/attendance'
    | '/org/$slug/workspace/teams'
    | '/org/$slug/console/modules/communication'
    | '/org/$slug/workspace/communication/channels'
    | '/org/$slug/workspace/communication/dm'
    | '/org/$slug/workspace/communication/channels/$channelId'
    | '/org/$slug/workspace/communication/dm/$conversationId'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(public)'
    | '/(authenticated)/settings'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(public)/'
    | '/(authenticated)/org/$slug'
    | '/(auth)/accept-invitation/$id'
    | '/(authenticated)/org/new'
    | '/(authenticated)/org/$slug/console'
    | '/(authenticated)/org/$slug/manage'
    | '/(authenticated)/org/$slug/workspace'
    | '/(authenticated)/settings/account/notifications'
    | '/(authenticated)/settings/account/preferences'
    | '/(authenticated)/settings/account/profile'
    | '/(authenticated)/settings/account/security'
    | '/(authenticated)/settings/account/sessions'
    | '/(authenticated)/org/$slug/console/modules'
    | '/(authenticated)/org/$slug/console/'
    | '/(authenticated)/org/$slug/manage/'
    | '/(authenticated)/org/$slug/workspace/'
    | '/(authenticated)/org/$slug/console/members/$memberId'
    | '/(authenticated)/org/$slug/console/members/invitations'
    | '/(authenticated)/org/$slug/workspace/attendance/analytics'
    | '/(authenticated)/org/$slug/workspace/attendance/settings'
    | '/(authenticated)/org/$slug/console/members/'
    | '/(authenticated)/org/$slug/console/teams/'
    | '/(authenticated)/org/$slug/workspace/attendance/'
    | '/(authenticated)/org/$slug/workspace/teams/'
    | '/(authenticated)/org/$slug/workspace/communication/channels/$channelId'
    | '/(authenticated)/org/$slug/workspace/communication/dm/$conversationId'
    | '/(authenticated)/org/$slug/console/modules/communication/'
    | '/(authenticated)/org/$slug/workspace/communication/channels/'
    | '/(authenticated)/org/$slug/workspace/communication/dm/'
    | '/(authenticated)/org/$slug/workspace/communication/channels/$channelId/'
    | '/(authenticated)/org/$slug/workspace/communication/dm/$conversationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  authAcceptInvitationIdRoute: typeof authAcceptInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/settings': {
      id: '/(authenticated)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof authenticatedSettingsRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/org/new': {
      id: '/(authenticated)/org/new'
      path: '/org/new'
      fullPath: '/org/new'
      preLoaderRoute: typeof authenticatedOrgNewRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(auth)/accept-invitation/$id': {
      id: '/(auth)/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof authAcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/org/$slug': {
      id: '/(authenticated)/org/$slug'
      path: '/org/$slug'
      fullPath: '/org/$slug'
      preLoaderRoute: typeof authenticatedOrgSlugRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/settings/account/sessions': {
      id: '/(authenticated)/settings/account/sessions'
      path: '/account/sessions'
      fullPath: '/settings/account/sessions'
      preLoaderRoute: typeof authenticatedSettingsAccountSessionsRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/settings/account/security': {
      id: '/(authenticated)/settings/account/security'
      path: '/account/security'
      fullPath: '/settings/account/security'
      preLoaderRoute: typeof authenticatedSettingsAccountSecurityRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/settings/account/profile': {
      id: '/(authenticated)/settings/account/profile'
      path: '/account/profile'
      fullPath: '/settings/account/profile'
      preLoaderRoute: typeof authenticatedSettingsAccountProfileRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/settings/account/preferences': {
      id: '/(authenticated)/settings/account/preferences'
      path: '/account/preferences'
      fullPath: '/settings/account/preferences'
      preLoaderRoute: typeof authenticatedSettingsAccountPreferencesRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/settings/account/notifications': {
      id: '/(authenticated)/settings/account/notifications'
      path: '/account/notifications'
      fullPath: '/settings/account/notifications'
      preLoaderRoute: typeof authenticatedSettingsAccountNotificationsRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/org/$slug/workspace': {
      id: '/(authenticated)/org/$slug/workspace'
      path: '/workspace'
      fullPath: '/org/$slug/workspace'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceRouteRouteImport
      parentRoute: typeof authenticatedOrgSlugRouteRoute
    }
    '/(authenticated)/org/$slug/manage': {
      id: '/(authenticated)/org/$slug/manage'
      path: '/manage'
      fullPath: '/org/$slug/manage'
      preLoaderRoute: typeof authenticatedOrgSlugManageRouteRouteImport
      parentRoute: typeof authenticatedOrgSlugRouteRoute
    }
    '/(authenticated)/org/$slug/console': {
      id: '/(authenticated)/org/$slug/console'
      path: '/console'
      fullPath: '/org/$slug/console'
      preLoaderRoute: typeof authenticatedOrgSlugConsoleRouteRouteImport
      parentRoute: typeof authenticatedOrgSlugRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/': {
      id: '/(authenticated)/org/$slug/workspace/'
      path: '/'
      fullPath: '/org/$slug/workspace/'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceRouteRoute
    }
    '/(authenticated)/org/$slug/manage/': {
      id: '/(authenticated)/org/$slug/manage/'
      path: '/'
      fullPath: '/org/$slug/manage/'
      preLoaderRoute: typeof authenticatedOrgSlugManageIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugManageRouteRoute
    }
    '/(authenticated)/org/$slug/console/': {
      id: '/(authenticated)/org/$slug/console/'
      path: '/'
      fullPath: '/org/$slug/console/'
      preLoaderRoute: typeof authenticatedOrgSlugConsoleIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugConsoleRouteRoute
    }
    '/(authenticated)/org/$slug/console/modules': {
      id: '/(authenticated)/org/$slug/console/modules'
      path: '/modules'
      fullPath: '/org/$slug/console/modules'
      preLoaderRoute: typeof authenticatedOrgSlugConsoleModulesRouteRouteImport
      parentRoute: typeof authenticatedOrgSlugConsoleRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/teams/': {
      id: '/(authenticated)/org/$slug/workspace/teams/'
      path: '/teams'
      fullPath: '/org/$slug/workspace/teams/'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceTeamsIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/attendance/': {
      id: '/(authenticated)/org/$slug/workspace/attendance/'
      path: '/attendance'
      fullPath: '/org/$slug/workspace/attendance/'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceAttendanceIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceRouteRoute
    }
    '/(authenticated)/org/$slug/console/teams/': {
      id: '/(authenticated)/org/$slug/console/teams/'
      path: '/teams'
      fullPath: '/org/$slug/console/teams/'
      preLoaderRoute: typeof authenticatedOrgSlugConsoleTeamsIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugConsoleRouteRoute
    }
    '/(authenticated)/org/$slug/console/members/': {
      id: '/(authenticated)/org/$slug/console/members/'
      path: '/members'
      fullPath: '/org/$slug/console/members/'
      preLoaderRoute: typeof authenticatedOrgSlugConsoleMembersIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugConsoleRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/attendance/settings': {
      id: '/(authenticated)/org/$slug/workspace/attendance/settings'
      path: '/attendance/settings'
      fullPath: '/org/$slug/workspace/attendance/settings'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceAttendanceSettingsRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/attendance/analytics': {
      id: '/(authenticated)/org/$slug/workspace/attendance/analytics'
      path: '/attendance/analytics'
      fullPath: '/org/$slug/workspace/attendance/analytics'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceAttendanceAnalyticsRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceRouteRoute
    }
    '/(authenticated)/org/$slug/console/members/invitations': {
      id: '/(authenticated)/org/$slug/console/members/invitations'
      path: '/members/invitations'
      fullPath: '/org/$slug/console/members/invitations'
      preLoaderRoute: typeof authenticatedOrgSlugConsoleMembersInvitationsRouteImport
      parentRoute: typeof authenticatedOrgSlugConsoleRouteRoute
    }
    '/(authenticated)/org/$slug/console/members/$memberId': {
      id: '/(authenticated)/org/$slug/console/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/org/$slug/console/members/$memberId'
      preLoaderRoute: typeof authenticatedOrgSlugConsoleMembersMemberIdRouteImport
      parentRoute: typeof authenticatedOrgSlugConsoleRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/communication/dm/': {
      id: '/(authenticated)/org/$slug/workspace/communication/dm/'
      path: '/communication/dm'
      fullPath: '/org/$slug/workspace/communication/dm/'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceCommunicationDmIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/communication/channels/': {
      id: '/(authenticated)/org/$slug/workspace/communication/channels/'
      path: '/communication/channels'
      fullPath: '/org/$slug/workspace/communication/channels/'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceCommunicationChannelsIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceRouteRoute
    }
    '/(authenticated)/org/$slug/console/modules/communication/': {
      id: '/(authenticated)/org/$slug/console/modules/communication/'
      path: '/communication'
      fullPath: '/org/$slug/console/modules/communication/'
      preLoaderRoute: typeof authenticatedOrgSlugConsoleModulesCommunicationIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugConsoleModulesRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/communication/dm/$conversationId': {
      id: '/(authenticated)/org/$slug/workspace/communication/dm/$conversationId'
      path: '/communication/dm/$conversationId'
      fullPath: '/org/$slug/workspace/communication/dm/$conversationId'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/communication/channels/$channelId': {
      id: '/(authenticated)/org/$slug/workspace/communication/channels/$channelId'
      path: '/communication/channels/$channelId'
      fullPath: '/org/$slug/workspace/communication/channels/$channelId'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/communication/dm/$conversationId/': {
      id: '/(authenticated)/org/$slug/workspace/communication/dm/$conversationId/'
      path: '/'
      fullPath: '/org/$slug/workspace/communication/dm/$conversationId/'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceCommunicationDmConversationIdIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRoute
    }
    '/(authenticated)/org/$slug/workspace/communication/channels/$channelId/': {
      id: '/(authenticated)/org/$slug/workspace/communication/channels/$channelId/'
      path: '/'
      fullPath: '/org/$slug/workspace/communication/channels/$channelId/'
      preLoaderRoute: typeof authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdIndexRouteImport
      parentRoute: typeof authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRoute
    }
  }
}

interface authenticatedSettingsRouteRouteChildren {
  authenticatedSettingsAccountNotificationsRoute: typeof authenticatedSettingsAccountNotificationsRoute
  authenticatedSettingsAccountPreferencesRoute: typeof authenticatedSettingsAccountPreferencesRoute
  authenticatedSettingsAccountProfileRoute: typeof authenticatedSettingsAccountProfileRoute
  authenticatedSettingsAccountSecurityRoute: typeof authenticatedSettingsAccountSecurityRoute
  authenticatedSettingsAccountSessionsRoute: typeof authenticatedSettingsAccountSessionsRoute
}

const authenticatedSettingsRouteRouteChildren: authenticatedSettingsRouteRouteChildren =
  {
    authenticatedSettingsAccountNotificationsRoute:
      authenticatedSettingsAccountNotificationsRoute,
    authenticatedSettingsAccountPreferencesRoute:
      authenticatedSettingsAccountPreferencesRoute,
    authenticatedSettingsAccountProfileRoute:
      authenticatedSettingsAccountProfileRoute,
    authenticatedSettingsAccountSecurityRoute:
      authenticatedSettingsAccountSecurityRoute,
    authenticatedSettingsAccountSessionsRoute:
      authenticatedSettingsAccountSessionsRoute,
  }

const authenticatedSettingsRouteRouteWithChildren =
  authenticatedSettingsRouteRoute._addFileChildren(
    authenticatedSettingsRouteRouteChildren,
  )

interface authenticatedOrgSlugConsoleModulesRouteRouteChildren {
  authenticatedOrgSlugConsoleModulesCommunicationIndexRoute: typeof authenticatedOrgSlugConsoleModulesCommunicationIndexRoute
}

const authenticatedOrgSlugConsoleModulesRouteRouteChildren: authenticatedOrgSlugConsoleModulesRouteRouteChildren =
  {
    authenticatedOrgSlugConsoleModulesCommunicationIndexRoute:
      authenticatedOrgSlugConsoleModulesCommunicationIndexRoute,
  }

const authenticatedOrgSlugConsoleModulesRouteRouteWithChildren =
  authenticatedOrgSlugConsoleModulesRouteRoute._addFileChildren(
    authenticatedOrgSlugConsoleModulesRouteRouteChildren,
  )

interface authenticatedOrgSlugConsoleRouteRouteChildren {
  authenticatedOrgSlugConsoleModulesRouteRoute: typeof authenticatedOrgSlugConsoleModulesRouteRouteWithChildren
  authenticatedOrgSlugConsoleIndexRoute: typeof authenticatedOrgSlugConsoleIndexRoute
  authenticatedOrgSlugConsoleMembersMemberIdRoute: typeof authenticatedOrgSlugConsoleMembersMemberIdRoute
  authenticatedOrgSlugConsoleMembersInvitationsRoute: typeof authenticatedOrgSlugConsoleMembersInvitationsRoute
  authenticatedOrgSlugConsoleMembersIndexRoute: typeof authenticatedOrgSlugConsoleMembersIndexRoute
  authenticatedOrgSlugConsoleTeamsIndexRoute: typeof authenticatedOrgSlugConsoleTeamsIndexRoute
}

const authenticatedOrgSlugConsoleRouteRouteChildren: authenticatedOrgSlugConsoleRouteRouteChildren =
  {
    authenticatedOrgSlugConsoleModulesRouteRoute:
      authenticatedOrgSlugConsoleModulesRouteRouteWithChildren,
    authenticatedOrgSlugConsoleIndexRoute:
      authenticatedOrgSlugConsoleIndexRoute,
    authenticatedOrgSlugConsoleMembersMemberIdRoute:
      authenticatedOrgSlugConsoleMembersMemberIdRoute,
    authenticatedOrgSlugConsoleMembersInvitationsRoute:
      authenticatedOrgSlugConsoleMembersInvitationsRoute,
    authenticatedOrgSlugConsoleMembersIndexRoute:
      authenticatedOrgSlugConsoleMembersIndexRoute,
    authenticatedOrgSlugConsoleTeamsIndexRoute:
      authenticatedOrgSlugConsoleTeamsIndexRoute,
  }

const authenticatedOrgSlugConsoleRouteRouteWithChildren =
  authenticatedOrgSlugConsoleRouteRoute._addFileChildren(
    authenticatedOrgSlugConsoleRouteRouteChildren,
  )

interface authenticatedOrgSlugManageRouteRouteChildren {
  authenticatedOrgSlugManageIndexRoute: typeof authenticatedOrgSlugManageIndexRoute
}

const authenticatedOrgSlugManageRouteRouteChildren: authenticatedOrgSlugManageRouteRouteChildren =
  {
    authenticatedOrgSlugManageIndexRoute: authenticatedOrgSlugManageIndexRoute,
  }

const authenticatedOrgSlugManageRouteRouteWithChildren =
  authenticatedOrgSlugManageRouteRoute._addFileChildren(
    authenticatedOrgSlugManageRouteRouteChildren,
  )

interface authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteChildren {
  authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdIndexRoute: typeof authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdIndexRoute
}

const authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteChildren: authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteChildren =
  {
    authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdIndexRoute:
      authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdIndexRoute,
  }

const authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteWithChildren =
  authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRoute._addFileChildren(
    authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteChildren,
  )

interface authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteChildren {
  authenticatedOrgSlugWorkspaceCommunicationDmConversationIdIndexRoute: typeof authenticatedOrgSlugWorkspaceCommunicationDmConversationIdIndexRoute
}

const authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteChildren: authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteChildren =
  {
    authenticatedOrgSlugWorkspaceCommunicationDmConversationIdIndexRoute:
      authenticatedOrgSlugWorkspaceCommunicationDmConversationIdIndexRoute,
  }

const authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteWithChildren =
  authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRoute._addFileChildren(
    authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteChildren,
  )

interface authenticatedOrgSlugWorkspaceRouteRouteChildren {
  authenticatedOrgSlugWorkspaceIndexRoute: typeof authenticatedOrgSlugWorkspaceIndexRoute
  authenticatedOrgSlugWorkspaceAttendanceAnalyticsRoute: typeof authenticatedOrgSlugWorkspaceAttendanceAnalyticsRoute
  authenticatedOrgSlugWorkspaceAttendanceSettingsRoute: typeof authenticatedOrgSlugWorkspaceAttendanceSettingsRoute
  authenticatedOrgSlugWorkspaceAttendanceIndexRoute: typeof authenticatedOrgSlugWorkspaceAttendanceIndexRoute
  authenticatedOrgSlugWorkspaceTeamsIndexRoute: typeof authenticatedOrgSlugWorkspaceTeamsIndexRoute
  authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRoute: typeof authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteWithChildren
  authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRoute: typeof authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteWithChildren
  authenticatedOrgSlugWorkspaceCommunicationChannelsIndexRoute: typeof authenticatedOrgSlugWorkspaceCommunicationChannelsIndexRoute
  authenticatedOrgSlugWorkspaceCommunicationDmIndexRoute: typeof authenticatedOrgSlugWorkspaceCommunicationDmIndexRoute
}

const authenticatedOrgSlugWorkspaceRouteRouteChildren: authenticatedOrgSlugWorkspaceRouteRouteChildren =
  {
    authenticatedOrgSlugWorkspaceIndexRoute:
      authenticatedOrgSlugWorkspaceIndexRoute,
    authenticatedOrgSlugWorkspaceAttendanceAnalyticsRoute:
      authenticatedOrgSlugWorkspaceAttendanceAnalyticsRoute,
    authenticatedOrgSlugWorkspaceAttendanceSettingsRoute:
      authenticatedOrgSlugWorkspaceAttendanceSettingsRoute,
    authenticatedOrgSlugWorkspaceAttendanceIndexRoute:
      authenticatedOrgSlugWorkspaceAttendanceIndexRoute,
    authenticatedOrgSlugWorkspaceTeamsIndexRoute:
      authenticatedOrgSlugWorkspaceTeamsIndexRoute,
    authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRoute:
      authenticatedOrgSlugWorkspaceCommunicationChannelsChannelIdRouteRouteWithChildren,
    authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRoute:
      authenticatedOrgSlugWorkspaceCommunicationDmConversationIdRouteRouteWithChildren,
    authenticatedOrgSlugWorkspaceCommunicationChannelsIndexRoute:
      authenticatedOrgSlugWorkspaceCommunicationChannelsIndexRoute,
    authenticatedOrgSlugWorkspaceCommunicationDmIndexRoute:
      authenticatedOrgSlugWorkspaceCommunicationDmIndexRoute,
  }

const authenticatedOrgSlugWorkspaceRouteRouteWithChildren =
  authenticatedOrgSlugWorkspaceRouteRoute._addFileChildren(
    authenticatedOrgSlugWorkspaceRouteRouteChildren,
  )

interface authenticatedOrgSlugRouteRouteChildren {
  authenticatedOrgSlugConsoleRouteRoute: typeof authenticatedOrgSlugConsoleRouteRouteWithChildren
  authenticatedOrgSlugManageRouteRoute: typeof authenticatedOrgSlugManageRouteRouteWithChildren
  authenticatedOrgSlugWorkspaceRouteRoute: typeof authenticatedOrgSlugWorkspaceRouteRouteWithChildren
}

const authenticatedOrgSlugRouteRouteChildren: authenticatedOrgSlugRouteRouteChildren =
  {
    authenticatedOrgSlugConsoleRouteRoute:
      authenticatedOrgSlugConsoleRouteRouteWithChildren,
    authenticatedOrgSlugManageRouteRoute:
      authenticatedOrgSlugManageRouteRouteWithChildren,
    authenticatedOrgSlugWorkspaceRouteRoute:
      authenticatedOrgSlugWorkspaceRouteRouteWithChildren,
  }

const authenticatedOrgSlugRouteRouteWithChildren =
  authenticatedOrgSlugRouteRoute._addFileChildren(
    authenticatedOrgSlugRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedSettingsRouteRoute: typeof authenticatedSettingsRouteRouteWithChildren
  authenticatedOrgSlugRouteRoute: typeof authenticatedOrgSlugRouteRouteWithChildren
  authenticatedOrgNewRoute: typeof authenticatedOrgNewRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedSettingsRouteRoute: authenticatedSettingsRouteRouteWithChildren,
  authenticatedOrgSlugRouteRoute: authenticatedOrgSlugRouteRouteWithChildren,
  authenticatedOrgNewRoute: authenticatedOrgNewRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  authAcceptInvitationIdRoute: authAcceptInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
