blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/yash91989201/work-holo/discussions
    about: Ask questions, share ideas, or start a conversation about work-holo.
