blank_issues_enabled: true
contact_links:
  - name: 📖 Documentation
    url: https://github.com/yash91989201/work-holo/tree/main/apps/docs
    about: Check the project documentation before opening an issue
