port: 7880

rtc:
  tcp_port: 7881
  udp_port: 7882
  use_external_ip: false

keys:
  devkey: 4ad6bb4633288be276a7c5d491e980a4b3bd7957871510bc

room:
  empty_timeout: 300
  max_participants: 25

logging:
  level: info
  json: false
