// AUTO-GENERATED FILE. DO NOT EDIT.
// Run `bun run generate:types` to refresh
import type { z } from "zod";

import type { AddBreakDurationInput } from "./schemas/attendance";
import type { AddBreakDurationOutput } from "./schemas/attendance";
import type { AddMemberInput } from "./schemas/team";
import type { AddMemberOutput } from "./schemas/team";
import type { AddReactionInput } from "./schemas/message";
import type { AddReactionOutput } from "./schemas/message";
import type { ArchiveChannelInput } from "./schemas/channel";
import type { AttachmentInput } from "./schemas/message";
import type { AttachmentOutput } from "./schemas/attachment";
import type { AttachmentTypeSchema } from "./schemas/attachment";
import type { AttachmentWithChannelOutput } from "./schemas/attachment";
import type { AttachmentWithMessageOutput } from "./schemas/attachment";
import type { AttachmentsListOutput } from "./schemas/attachment";
import type { AttachmentsWithChannelListOutput } from "./schemas/attachment";
import type { AttachmentsWithMessageListOutput } from "./schemas/attachment";
import type { AttendanceAnalyticsInput } from "./schemas/attendance";
import type { AttendanceAnalyticsOutput } from "./schemas/attendance";
import type { AttendanceRecordWithUserSchema } from "./schemas/admin-attendance";
import type { AttendanceSelectSchema } from "./schemas/admin-attendance";
import type { ChannelJoinRequestInput } from "./schemas/channel";
import type { ChannelJoinRequestOutput } from "./schemas/channel";
import type { ChannelMemberOutput } from "./schemas/channel";
import type { ChannelMembersListOutput } from "./schemas/channel";
import type { ChannelOutput } from "./schemas/channel";
import type { ChannelWithCreatorOutput } from "./schemas/channel";
import type { ChannelWithStatsOutput } from "./schemas/channel";
import type { ChannelsListOutput } from "./schemas/channel";
import type { CreateAnnouncementNotificationInput } from "./schemas/notification";
import type { CreateAttachmentInput } from "./schemas/attachment";
import type { CreateBulkAttachmentsInput } from "./schemas/attachment";
import type { CreateBulkNotificationsInput } from "./schemas/notification";
import type { CreateChannelInput } from "./schemas/channel";
import type { CreateChannelInviteNotificationInput } from "./schemas/notification";
import type { CreateChannelOutput } from "./schemas/channel";
import type { CreateMessageInput } from "./schemas/message";
import type { CreateMessageOutput } from "./schemas/message";
import type { CreateNotificationInput } from "./schemas/notification";
import type { CreateSystemNotificationInput } from "./schemas/notification";
import type { DeleteAttachmentInput } from "./schemas/attachment";
import type { DeleteAttachmentOutput } from "./schemas/attachment";
import type { DeleteChannelInput } from "./schemas/channel";
import type { DeleteMessageInput } from "./schemas/message";
import type { DeleteMessageOutput } from "./schemas/message";
import type { DeleteNotificationInput } from "./schemas/notification";
import type { DeletechannelOutput } from "./schemas/channel";
import type { DismissNotificationInput } from "./schemas/notification";
import type { EndBlockInput } from "./schemas/work-block";
import type { EndBlockOutput } from "./schemas/work-block";
import type { FeatureSchema } from "./schemas/module";
import type { GetActiveBlockInput } from "./schemas/work-block";
import type { GetActiveBlockOutput } from "./schemas/work-block";
import type { GetAttachmentInput } from "./schemas/attachment";
import type { GetAttendanceDetailInput } from "./schemas/admin-attendance";
import type { GetAttendanceDetailOutput } from "./schemas/admin-attendance";
import type { GetAttendanceStatsInput } from "./schemas/admin-attendance";
import type { GetAttendanceStatsOutput } from "./schemas/admin-attendance";
import type { GetChannelAttachmentsInput } from "./schemas/attachment";
import type { GetChannelInput } from "./schemas/channel";
import type { GetChannelMessagesInput } from "./schemas/message";
import type { GetChannelMessagesOutput } from "./schemas/message";
import type { GetChannelOutput } from "./schemas/channel";
import type { GetChannelsInput } from "./schemas/channel";
import type { GetDirectMessagesInput } from "./schemas/message";
import type { GetMenionUsersInput } from "./schemas/message";
import type { GetMenionUsersOutput } from "./schemas/message";
import type { GetMessageAttachmentsInput } from "./schemas/attachment";
import type { GetMessageInput } from "./schemas/message";
import type { GetMessageOutput } from "./schemas/message";
import type { GetMultipleMessageAttachmentsInput } from "./schemas/attachment";
import type { GetNotificationsInput } from "./schemas/notification";
import type { GetOrgPresenceInput } from "./schemas/presence";
import type { GetOrgPresenceOutput } from "./schemas/presence";
import type { GetPinnedMessagesInput } from "./schemas/message";
import type { GetPinnedMessagesOutput } from "./schemas/message";
import type { GetRecentAttachmentsInput } from "./schemas/attachment";
import type { GetStorageStatsInput } from "./schemas/attachment";
import type { GetThreadMessagesInput } from "./schemas/message";
import type { GetTodayInput } from "./schemas/attendance";
import type { GetTodayOutput } from "./schemas/attendance";
import type { GetUnreadCountInput } from "./schemas/message";
import type { GetUserAttachmentsInput } from "./schemas/attachment";
import type { HeartbeatInput } from "./schemas/presence";
import type { HeartbeatOutput } from "./schemas/presence";
import type { InvitationSelectSchema } from "./schemas/admin-invitation";
import type { IsChannelMemberInput } from "./schemas/channel";
import type { IsChannelMemberOutput } from "./schemas/channel";
import type { JoinChannelInput } from "./schemas/channel";
import type { LeaveChannelInput } from "./schemas/channel";
import type { ListAttendanceRecordsInput } from "./schemas/admin-attendance";
import type { ListAttendanceRecordsOutput } from "./schemas/admin-attendance";
import type { ListBlocksInput } from "./schemas/work-block";
import type { ListBlocksOutput } from "./schemas/work-block";
import type { ListChannelMembersInput } from "./schemas/channel";
import type { ListChannelMembersOutput } from "./schemas/channel";
import type { ListChannelsInput } from "./schemas/channel";
import type { ListChannelsOutput } from "./schemas/channel";
import type { ListInvitationsInput } from "./schemas/admin-invitation";
import type { ListInvitationsOutput } from "./schemas/admin-invitation";
import type { ListJoinRequestInput } from "./schemas/channel";
import type { ListJoinRequestOutput } from "./schemas/channel";
import type { ListMembersInput } from "./schemas/admin-member";
import type { ListMembersOutput } from "./schemas/admin-member";
import type { ListTeamsInput } from "./schemas/team";
import type { ListTeamsOutput } from "./schemas/team";
import type { ManualStatusSchema } from "./schemas/presence";
import type { MarkAllMentionsSeenInput } from "./schemas/message";
import type { MarkAllMentionsSeenOutput } from "./schemas/message";
import type { MarkAllNotificationsAsReadInput } from "./schemas/notification";
import type { MarkAllNotificationsAsReadOutput } from "./schemas/notification";
import type { MarkMentionSeenInput } from "./schemas/message";
import type { MarkMentionSeenOutput } from "./schemas/message";
import type { MarkMessageAsReadInput } from "./schemas/message";
import type { MarkMultipleAsReadInput } from "./schemas/notification";
import type { MarkNotificationAsReadInput } from "./schemas/notification";
import type { MarkNotificationAsReadOutput } from "./schemas/notification";
import type { MemberAttendanceStatusOutput } from "./schemas/attendance";
import type { MemberPunchInInput } from "./schemas/attendance";
import type { MemberPunchInOutput } from "./schemas/attendance";
import type { MemberPunchOutInput } from "./schemas/attendance";
import type { MemberPunchOutOutput } from "./schemas/attendance";
import type { MemberSelectSchema } from "./schemas/admin-member";
import type { MemberWithUserSchema } from "./schemas/admin-member";
import type { MessageAttachmentOutput } from "./schemas/message";
import type { MessageOutput } from "./schemas/message";
import type { MessageTypeSchema } from "./schemas/message";
import type { MessageWithSenderSchema } from "./schemas/message";
import type { MessagesListOutput } from "./schemas/message";
import type { ModifyChannelMembersInput } from "./schemas/channel";
import type { ModuleSchema } from "./schemas/module";
import type { NotificationOutput } from "./schemas/notification";
import type { NotificationStatusSchema } from "./schemas/notification";
import type { NotificationTypeSchema } from "./schemas/notification";
import type { NotificationsListOutput } from "./schemas/notification";
import type { PinMessageInput } from "./schemas/message";
import type { PinMessageOutput } from "./schemas/message";
import type { PresenceDataSchema } from "./schemas/presence";
import type { PresenceStatusSchema } from "./schemas/presence";
import type { ReactionOutput } from "./schemas/message";
import type { RecentAttachmentOutput } from "./schemas/attachment";
import type { RecentAttachmentsListOutput } from "./schemas/attachment";
import type { RemoveChannelMemberInput } from "./schemas/channel";
import type { RemoveMemberInput } from "./schemas/team";
import type { RemoveMemberOutput } from "./schemas/team";
import type { RemovePushSubscriptionInput } from "./schemas/push-subscription";
import type { RemoveReactionInput } from "./schemas/message";
import type { RemoveReactionOutput } from "./schemas/message";
import type { RoleSchema } from "./schemas/module";
import type { SavePushSubscriptionInput } from "./schemas/push-subscription";
import type { SearchAttachmentsInput } from "./schemas/attachment";
import type { SearchMessageOutput } from "./schemas/message";
import type { SearchMessagesInput } from "./schemas/message";
import type { SearchMessagesListOutput } from "./schemas/message";
import type { SearchUsersInput } from "./schemas/message";
import type { SearchUsersOutput } from "./schemas/message";
import type { SetManualStatusInput } from "./schemas/presence";
import type { SetManualStatusOutput } from "./schemas/presence";
import type { StartBlockInput } from "./schemas/work-block";
import type { StartBlockOutput } from "./schemas/work-block";
import type { StorageStatsOutput } from "./schemas/attachment";
import type { SuccessOutput } from "./schemas/channel";
import type { ThreadMessageOutput } from "./schemas/message";
import type { UnPinMessageInput } from "./schemas/message";
import type { UnPinMessageOutput } from "./schemas/message";
import type { UnreadCountOutput } from "./schemas/message";
import type { UpdateAttachmentInput } from "./schemas/attachment";
import type { UpdateChannelInput } from "./schemas/channel";
import type { UpdateChannelMemberInput } from "./schemas/channel";
import type { UpdateMessageInput } from "./schemas/message";
import type { UpdateMessageOutput } from "./schemas/message";
import type { UserSelectSchema } from "./schemas/admin-member";

export type AddBreakDurationInputType = z.infer<typeof AddBreakDurationInput>;
export type AddBreakDurationOutputType = z.infer<typeof AddBreakDurationOutput>;
export type AddMemberInputType = z.infer<typeof AddMemberInput>;
export type AddMemberOutputType = z.infer<typeof AddMemberOutput>;
export type AddReactionInputType = z.infer<typeof AddReactionInput>;
export type AddReactionOutputType = z.infer<typeof AddReactionOutput>;
export type ArchiveChannelInputType = z.infer<typeof ArchiveChannelInput>;
export type AttachmentInputType = z.infer<typeof AttachmentInput>;
export type AttachmentOutputType = z.infer<typeof AttachmentOutput>;
export type AttachmentTypeType = z.infer<typeof AttachmentTypeSchema>;
export type AttachmentWithChannelOutputType = z.infer<typeof AttachmentWithChannelOutput>;
export type AttachmentWithMessageOutputType = z.infer<typeof AttachmentWithMessageOutput>;
export type AttachmentsListOutputType = z.infer<typeof AttachmentsListOutput>;
export type AttachmentsWithChannelListOutputType = z.infer<typeof AttachmentsWithChannelListOutput>;
export type AttachmentsWithMessageListOutputType = z.infer<typeof AttachmentsWithMessageListOutput>;
export type AttendanceAnalyticsInputType = z.infer<typeof AttendanceAnalyticsInput>;
export type AttendanceAnalyticsOutputType = z.infer<typeof AttendanceAnalyticsOutput>;
export type AttendanceRecordWithUserType = z.infer<typeof AttendanceRecordWithUserSchema>;
export type AttendanceSelectType = z.infer<typeof AttendanceSelectSchema>;
export type ChannelJoinRequestInputType = z.infer<typeof ChannelJoinRequestInput>;
export type ChannelJoinRequestOutputType = z.infer<typeof ChannelJoinRequestOutput>;
export type ChannelMemberOutputType = z.infer<typeof ChannelMemberOutput>;
export type ChannelMembersListOutputType = z.infer<typeof ChannelMembersListOutput>;
export type ChannelOutputType = z.infer<typeof ChannelOutput>;
export type ChannelWithCreatorOutputType = z.infer<typeof ChannelWithCreatorOutput>;
export type ChannelWithStatsOutputType = z.infer<typeof ChannelWithStatsOutput>;
export type ChannelsListOutputType = z.infer<typeof ChannelsListOutput>;
export type CreateAnnouncementNotificationInputType = z.infer<typeof CreateAnnouncementNotificationInput>;
export type CreateAttachmentInputType = z.infer<typeof CreateAttachmentInput>;
export type CreateBulkAttachmentsInputType = z.infer<typeof CreateBulkAttachmentsInput>;
export type CreateBulkNotificationsInputType = z.infer<typeof CreateBulkNotificationsInput>;
export type CreateChannelInputType = z.infer<typeof CreateChannelInput>;
export type CreateChannelInviteNotificationInputType = z.infer<typeof CreateChannelInviteNotificationInput>;
export type CreateChannelOutputType = z.infer<typeof CreateChannelOutput>;
export type CreateMessageInputType = z.infer<typeof CreateMessageInput>;
export type CreateMessageOutputType = z.infer<typeof CreateMessageOutput>;
export type CreateNotificationInputType = z.infer<typeof CreateNotificationInput>;
export type CreateSystemNotificationInputType = z.infer<typeof CreateSystemNotificationInput>;
export type DeleteAttachmentInputType = z.infer<typeof DeleteAttachmentInput>;
export type DeleteAttachmentOutputType = z.infer<typeof DeleteAttachmentOutput>;
export type DeleteChannelInputType = z.infer<typeof DeleteChannelInput>;
export type DeleteMessageInputType = z.infer<typeof DeleteMessageInput>;
export type DeleteMessageOutputType = z.infer<typeof DeleteMessageOutput>;
export type DeleteNotificationInputType = z.infer<typeof DeleteNotificationInput>;
export type DeletechannelOutputType = z.infer<typeof DeletechannelOutput>;
export type DismissNotificationInputType = z.infer<typeof DismissNotificationInput>;
export type EndBlockInputType = z.infer<typeof EndBlockInput>;
export type EndBlockOutputType = z.infer<typeof EndBlockOutput>;
export type FeatureType = z.infer<typeof FeatureSchema>;
export type GetActiveBlockInputType = z.infer<typeof GetActiveBlockInput>;
export type GetActiveBlockOutputType = z.infer<typeof GetActiveBlockOutput>;
export type GetAttachmentInputType = z.infer<typeof GetAttachmentInput>;
export type GetAttendanceDetailInputType = z.infer<typeof GetAttendanceDetailInput>;
export type GetAttendanceDetailOutputType = z.infer<typeof GetAttendanceDetailOutput>;
export type GetAttendanceStatsInputType = z.infer<typeof GetAttendanceStatsInput>;
export type GetAttendanceStatsOutputType = z.infer<typeof GetAttendanceStatsOutput>;
export type GetChannelAttachmentsInputType = z.infer<typeof GetChannelAttachmentsInput>;
export type GetChannelInputType = z.infer<typeof GetChannelInput>;
export type GetChannelMessagesInputType = z.infer<typeof GetChannelMessagesInput>;
export type GetChannelMessagesOutputType = z.infer<typeof GetChannelMessagesOutput>;
export type GetChannelOutputType = z.infer<typeof GetChannelOutput>;
export type GetChannelsInputType = z.infer<typeof GetChannelsInput>;
export type GetDirectMessagesInputType = z.infer<typeof GetDirectMessagesInput>;
export type GetMenionUsersInputType = z.infer<typeof GetMenionUsersInput>;
export type GetMenionUsersOutputType = z.infer<typeof GetMenionUsersOutput>;
export type GetMessageAttachmentsInputType = z.infer<typeof GetMessageAttachmentsInput>;
export type GetMessageInputType = z.infer<typeof GetMessageInput>;
export type GetMessageOutputType = z.infer<typeof GetMessageOutput>;
export type GetMultipleMessageAttachmentsInputType = z.infer<typeof GetMultipleMessageAttachmentsInput>;
export type GetNotificationsInputType = z.infer<typeof GetNotificationsInput>;
export type GetOrgPresenceInputType = z.infer<typeof GetOrgPresenceInput>;
export type GetOrgPresenceOutputType = z.infer<typeof GetOrgPresenceOutput>;
export type GetPinnedMessagesInputType = z.infer<typeof GetPinnedMessagesInput>;
export type GetPinnedMessagesOutputType = z.infer<typeof GetPinnedMessagesOutput>;
export type GetRecentAttachmentsInputType = z.infer<typeof GetRecentAttachmentsInput>;
export type GetStorageStatsInputType = z.infer<typeof GetStorageStatsInput>;
export type GetThreadMessagesInputType = z.infer<typeof GetThreadMessagesInput>;
export type GetTodayInputType = z.infer<typeof GetTodayInput>;
export type GetTodayOutputType = z.infer<typeof GetTodayOutput>;
export type GetUnreadCountInputType = z.infer<typeof GetUnreadCountInput>;
export type GetUserAttachmentsInputType = z.infer<typeof GetUserAttachmentsInput>;
export type HeartbeatInputType = z.infer<typeof HeartbeatInput>;
export type HeartbeatOutputType = z.infer<typeof HeartbeatOutput>;
export type InvitationSelectType = z.infer<typeof InvitationSelectSchema>;
export type IsChannelMemberInputType = z.infer<typeof IsChannelMemberInput>;
export type IsChannelMemberOutputType = z.infer<typeof IsChannelMemberOutput>;
export type JoinChannelInputType = z.infer<typeof JoinChannelInput>;
export type LeaveChannelInputType = z.infer<typeof LeaveChannelInput>;
export type ListAttendanceRecordsInputType = z.infer<typeof ListAttendanceRecordsInput>;
export type ListAttendanceRecordsOutputType = z.infer<typeof ListAttendanceRecordsOutput>;
export type ListBlocksInputType = z.infer<typeof ListBlocksInput>;
export type ListBlocksOutputType = z.infer<typeof ListBlocksOutput>;
export type ListChannelMembersInputType = z.infer<typeof ListChannelMembersInput>;
export type ListChannelMembersOutputType = z.infer<typeof ListChannelMembersOutput>;
export type ListChannelsInputType = z.infer<typeof ListChannelsInput>;
export type ListChannelsOutputType = z.infer<typeof ListChannelsOutput>;
export type ListInvitationsInputType = z.infer<typeof ListInvitationsInput>;
export type ListInvitationsOutputType = z.infer<typeof ListInvitationsOutput>;
export type ListJoinRequestInputType = z.infer<typeof ListJoinRequestInput>;
export type ListJoinRequestOutputType = z.infer<typeof ListJoinRequestOutput>;
export type ListMembersInputType = z.infer<typeof ListMembersInput>;
export type ListMembersOutputType = z.infer<typeof ListMembersOutput>;
export type ListTeamsInputType = z.infer<typeof ListTeamsInput>;
export type ListTeamsOutputType = z.infer<typeof ListTeamsOutput>;
export type ManualStatusType = z.infer<typeof ManualStatusSchema>;
export type MarkAllMentionsSeenInputType = z.infer<typeof MarkAllMentionsSeenInput>;
export type MarkAllMentionsSeenOutputType = z.infer<typeof MarkAllMentionsSeenOutput>;
export type MarkAllNotificationsAsReadInputType = z.infer<typeof MarkAllNotificationsAsReadInput>;
export type MarkAllNotificationsAsReadOutputType = z.infer<typeof MarkAllNotificationsAsReadOutput>;
export type MarkMentionSeenInputType = z.infer<typeof MarkMentionSeenInput>;
export type MarkMentionSeenOutputType = z.infer<typeof MarkMentionSeenOutput>;
export type MarkMessageAsReadInputType = z.infer<typeof MarkMessageAsReadInput>;
export type MarkMultipleAsReadInputType = z.infer<typeof MarkMultipleAsReadInput>;
export type MarkNotificationAsReadInputType = z.infer<typeof MarkNotificationAsReadInput>;
export type MarkNotificationAsReadOutputType = z.infer<typeof MarkNotificationAsReadOutput>;
export type MemberAttendanceStatusOutputType = z.infer<typeof MemberAttendanceStatusOutput>;
export type MemberPunchInInputType = z.infer<typeof MemberPunchInInput>;
export type MemberPunchInOutputType = z.infer<typeof MemberPunchInOutput>;
export type MemberPunchOutInputType = z.infer<typeof MemberPunchOutInput>;
export type MemberPunchOutOutputType = z.infer<typeof MemberPunchOutOutput>;
export type MemberSelectType = z.infer<typeof MemberSelectSchema>;
export type MemberWithUserType = z.infer<typeof MemberWithUserSchema>;
export type MessageAttachmentOutputType = z.infer<typeof MessageAttachmentOutput>;
export type MessageOutputType = z.infer<typeof MessageOutput>;
export type MessageTypeType = z.infer<typeof MessageTypeSchema>;
export type MessageWithSenderType = z.infer<typeof MessageWithSenderSchema>;
export type MessagesListOutputType = z.infer<typeof MessagesListOutput>;
export type ModifyChannelMembersInputType = z.infer<typeof ModifyChannelMembersInput>;
export type ModuleType = z.infer<typeof ModuleSchema>;
export type NotificationOutputType = z.infer<typeof NotificationOutput>;
export type NotificationStatusType = z.infer<typeof NotificationStatusSchema>;
export type NotificationTypeType = z.infer<typeof NotificationTypeSchema>;
export type NotificationsListOutputType = z.infer<typeof NotificationsListOutput>;
export type PinMessageInputType = z.infer<typeof PinMessageInput>;
export type PinMessageOutputType = z.infer<typeof PinMessageOutput>;
export type PresenceDataType = z.infer<typeof PresenceDataSchema>;
export type PresenceStatusType = z.infer<typeof PresenceStatusSchema>;
export type ReactionOutputType = z.infer<typeof ReactionOutput>;
export type RecentAttachmentOutputType = z.infer<typeof RecentAttachmentOutput>;
export type RecentAttachmentsListOutputType = z.infer<typeof RecentAttachmentsListOutput>;
export type RemoveChannelMemberInputType = z.infer<typeof RemoveChannelMemberInput>;
export type RemoveMemberInputType = z.infer<typeof RemoveMemberInput>;
export type RemoveMemberOutputType = z.infer<typeof RemoveMemberOutput>;
export type RemovePushSubscriptionInputType = z.infer<typeof RemovePushSubscriptionInput>;
export type RemoveReactionInputType = z.infer<typeof RemoveReactionInput>;
export type RemoveReactionOutputType = z.infer<typeof RemoveReactionOutput>;
export type RoleType = z.infer<typeof RoleSchema>;
export type SavePushSubscriptionInputType = z.infer<typeof SavePushSubscriptionInput>;
export type SearchAttachmentsInputType = z.infer<typeof SearchAttachmentsInput>;
export type SearchMessageOutputType = z.infer<typeof SearchMessageOutput>;
export type SearchMessagesInputType = z.infer<typeof SearchMessagesInput>;
export type SearchMessagesListOutputType = z.infer<typeof SearchMessagesListOutput>;
export type SearchUsersInputType = z.infer<typeof SearchUsersInput>;
export type SearchUsersOutputType = z.infer<typeof SearchUsersOutput>;
export type SetManualStatusInputType = z.infer<typeof SetManualStatusInput>;
export type SetManualStatusOutputType = z.infer<typeof SetManualStatusOutput>;
export type StartBlockInputType = z.infer<typeof StartBlockInput>;
export type StartBlockOutputType = z.infer<typeof StartBlockOutput>;
export type StorageStatsOutputType = z.infer<typeof StorageStatsOutput>;
export type SuccessOutputType = z.infer<typeof SuccessOutput>;
export type ThreadMessageOutputType = z.infer<typeof ThreadMessageOutput>;
export type UnPinMessageInputType = z.infer<typeof UnPinMessageInput>;
export type UnPinMessageOutputType = z.infer<typeof UnPinMessageOutput>;
export type UnreadCountOutputType = z.infer<typeof UnreadCountOutput>;
export type UpdateAttachmentInputType = z.infer<typeof UpdateAttachmentInput>;
export type UpdateChannelInputType = z.infer<typeof UpdateChannelInput>;
export type UpdateChannelMemberInputType = z.infer<typeof UpdateChannelMemberInput>;
export type UpdateMessageInputType = z.infer<typeof UpdateMessageInput>;
export type UpdateMessageOutputType = z.infer<typeof UpdateMessageOutput>;
export type UserSelectType = z.infer<typeof UserSelectSchema>;
