// @generated by scripts/generate-permission-code.ts - DO NOT EDIT

import type { PermissionAction } from "../types";
import { createActionTerminal } from "./shared";

export type AttendanceDSL = {
  record: {
    create: PermissionAction;
    delete: PermissionAction;
    list: PermissionAction;
    read: PermissionAction;
    update: PermissionAction;
  };
};

export function Attendance(): AttendanceDSL {
  const t = (key: string) => createActionTerminal(key);

  return {
    record: {
      create: t("attendance.record.create"),
      delete: t("attendance.record.delete"),
      list: t("attendance.record.list"),
      read: t("attendance.record.read"),
      update: t("attendance.record.update"),
    },
  };
}
