// @generated by scripts/generate-permission-code.ts - DO NOT EDIT

import type { PermissionAction } from "../types";
import { createActionTerminal, createScopedActionTerminal } from "./shared";

/** DSL object providing attendance permission action builders, optionally team-scoped. */
export type AttendanceDSL = {
  record: {
    create: PermissionAction;
    delete: PermissionAction;
    list: PermissionAction;
    read: PermissionAction;
    update: PermissionAction;
  };
};

/**
 * Creates attendance permission descriptor builders, optionally scoped to a team.
 * @param teamId Optional team ID for team-scoped permissions; if omitted, permissions are org-level
 * @returns DSL object with permission action builders
 */
export function Attendance(teamId?: string): AttendanceDSL {
  const t = (key: string) =>
    teamId
      ? createScopedActionTerminal("team", teamId, key)
      : createActionTerminal(key);

  return {
    record: {
      create: t("attendance.record.create"),
      delete: t("attendance.record.delete"),
      list: t("attendance.record.list"),
      read: t("attendance.record.read"),
      update: t("attendance.record.update"),
    },
  };
}
