// @generated by scripts/generate-permission-code.ts - DO NOT EDIT

import type { PermissionAction } from "../types";
import { createActionTerminal } from "./shared";

export type ChannelDSL = {
  create: PermissionAction;
  delete: PermissionAction;
  list: PermissionAction;
  member: {
    add: PermissionAction;
    list: PermissionAction;
    read: PermissionAction;
    remove: PermissionAction;
  };
  message: {
    create: PermissionAction;
    delete: PermissionAction;
    list: PermissionAction;
    mention: {
      channel: PermissionAction;
      user: PermissionAction;
    };
    pin: PermissionAction;
    react: PermissionAction;
    read: PermissionAction;
    reader: {
      list: PermissionAction;
    };
    reply: PermissionAction;
    update: PermissionAction;
  };
  read: PermissionAction;
  update: PermissionAction;
};

export function Channel(): ChannelDSL {
  const t = (key: string) => createActionTerminal(key);

  return {
    create: t("channel.create"),
    delete: t("channel.delete"),
    list: t("channel.list"),
    member: {
      add: t("channel.member.add"),
      list: t("channel.member.list"),
      read: t("channel.member.read"),
      remove: t("channel.member.remove"),
    },
    message: {
      create: t("channel.message.create"),
      delete: t("channel.message.delete"),
      list: t("channel.message.list"),
      mention: {
        channel: t("channel.message.mention.channel"),
        user: t("channel.message.mention.user"),
      },
      pin: t("channel.message.pin"),
      react: t("channel.message.react"),
      read: t("channel.message.read"),
      reader: {
        list: t("channel.message.reader.list"),
      },
      reply: t("channel.message.reply"),
      update: t("channel.message.update"),
    },
    read: t("channel.read"),
    update: t("channel.update"),
  };
}
