// @generated by scripts/generate-permission-code.ts - DO NOT EDIT

export const permissionKey = {
  attendance: {
    record: {
      create: "attendance.record.create",
      delete: "attendance.record.delete",
      list: "attendance.record.list",
      read: "attendance.record.read",
      update: "attendance.record.update",
    },
  },
  channel: {
    create: "channel.create",
    delete: "channel.delete",
    list: "channel.list",
    member: {
      add: "channel.member.add",
      list: "channel.member.list",
      read: "channel.member.read",
      remove: "channel.member.remove",
    },
    message: {
      create: "channel.message.create",
      delete: "channel.message.delete",
      list: "channel.message.list",
      mention: {
        channel: "channel.message.mention.channel",
        user: "channel.message.mention.user",
      },
      pin: "channel.message.pin",
      react: "channel.message.react",
      read: "channel.message.read",
      reader: {
        list: "channel.message.reader.list",
      },
      reply: "channel.message.reply",
      update: "channel.message.update",
    },
    read: "channel.read",
    update: "channel.update",
  },
  org: {
    active: {
      read: "org.active.read",
      switch: "org.active.switch",
    },
    create: "org.create",
    delete: "org.delete",
    invite: {
      create: "org.invite.create",
      delete: "org.invite.delete",
      list: "org.invite.list",
      read: "org.invite.read",
      resend: "org.invite.resend",
      update: "org.invite.update",
    },
    list: "org.list",
    read: "org.read",
    role: {
      assign: "org.role.assign",
      create: "org.role.create",
      delete: "org.role.delete",
      list: "org.role.list",
      read: "org.role.read",
      remove: "org.role.remove",
      update: "org.role.update",
    },
    update: "org.update",
  },
  team: {
    create: "team.create",
    delete: "team.delete",
    list: "team.list",
    member: {
      add: "team.member.add",
      list: "team.member.list",
      read: "team.member.read",
      remove: "team.member.remove",
    },
    module: {
      access: "team.module.access",
      disable: "team.module.disable",
      enable: "team.module.enable",
    },
    read: "team.read",
    role: {
      assign: "team.role.assign",
      create: "team.role.create",
      delete: "team.role.delete",
      list: "team.role.list",
      read: "team.role.read",
      remove: "team.role.remove",
      update: "team.role.update",
    },
    update: "team.update",
  },
} as const;

type LeafValues<T> = T extends string
  ? T
  : { [K in keyof T]: LeafValues<T[K]> }[keyof T];

export type PermissionKeyFromDSL = LeafValues<typeof permissionKey>;

export type PermissionKeys = typeof permissionKey;

type AndExpression = { _type: "and"; operands: PermissionExpression[] };
type OrExpression = { _type: "or"; operands: PermissionExpression[] };
type NotExpression = { _type: "not"; operand: PermissionExpression };

export type PermissionExpression =
  | PermissionKeyFromDSL
  | AndExpression
  | OrExpression
  | NotExpression;

export function and(...operands: PermissionExpression[]): AndExpression {
  return { _type: "and", operands };
}

export function or(...operands: PermissionExpression[]): OrExpression {
  return { _type: "or", operands };
}

export function not(operand: PermissionExpression): NotExpression {
  return { _type: "not", operand };
}

export type PermissionSelector = (
  p: PermissionKeys,
  ops: { and: typeof and; or: typeof or; not: typeof not }
) => PermissionExpression;

export type PermissionInput = PermissionKeyFromDSL | PermissionSelector;

export function resolvePermission(
  input: PermissionInput
): PermissionExpression {
  if (typeof input === "function") {
    return input(permissionKey, { and, or, not });
  }
  return input;
}

export function evaluateExpression(
  expr: PermissionExpression,
  permissions: Record<string, boolean>
): boolean {
  if (typeof expr === "string") {
    return permissions[expr] ?? false;
  }

  switch (expr._type) {
    case "and":
      return expr.operands.every((operand) =>
        evaluateExpression(operand, permissions)
      );
    case "or":
      return expr.operands.some((operand) =>
        evaluateExpression(operand, permissions)
      );
    case "not":
      return !evaluateExpression(expr.operand, permissions);
    default:
      return false;
  }
}
