// @generated by scripts/generate-permission-code.ts - DO NOT EDIT

import type { PermissionAction } from "../types";
import { createScopedActionTerminal } from "./shared";

export type OrgDSL = {
  active: {
    read: PermissionAction;
    switch: PermissionAction;
  };
  create: PermissionAction;
  delete: PermissionAction;
  invite: {
    create: PermissionAction;
    delete: PermissionAction;
    list: PermissionAction;
    read: PermissionAction;
    resend: PermissionAction;
    update: PermissionAction;
  };
  list: PermissionAction;
  read: PermissionAction;
  role: {
    assign: PermissionAction;
    create: PermissionAction;
    delete: PermissionAction;
    list: PermissionAction;
    read: PermissionAction;
    remove: PermissionAction;
    update: PermissionAction;
  };
  update: PermissionAction;
};

export function Org(orgId: string): OrgDSL {
  const t = (key: string) => createScopedActionTerminal("org", orgId, key);

  return {
    active: {
      read: t("org.active.read"),
      switch: t("org.active.switch"),
    },
    create: t("org.create"),
    delete: t("org.delete"),
    invite: {
      create: t("org.invite.create"),
      delete: t("org.invite.delete"),
      list: t("org.invite.list"),
      read: t("org.invite.read"),
      resend: t("org.invite.resend"),
      update: t("org.invite.update"),
    },
    list: t("org.list"),
    read: t("org.read"),
    role: {
      assign: t("org.role.assign"),
      create: t("org.role.create"),
      delete: t("org.role.delete"),
      list: t("org.role.list"),
      read: t("org.role.read"),
      remove: t("org.role.remove"),
      update: t("org.role.update"),
    },
    update: t("org.update"),
  };
}
