// @generated by scripts/generate-permission-code.ts - DO NOT EDIT

import type { PermissionAction } from "../types";
import { createScopedActionTerminal } from "./shared";

export type TeamDSL = {
  create: PermissionAction;
  delete: PermissionAction;
  list: PermissionAction;
  member: {
    add: PermissionAction;
    list: PermissionAction;
    read: PermissionAction;
    remove: PermissionAction;
  };
  module: {
    access: PermissionAction;
    disable: PermissionAction;
    enable: PermissionAction;
  };
  read: PermissionAction;
  role: {
    assign: PermissionAction;
    create: PermissionAction;
    delete: PermissionAction;
    list: PermissionAction;
    read: PermissionAction;
    remove: PermissionAction;
    update: PermissionAction;
  };
  update: PermissionAction;
};

export function Team(teamId: string): TeamDSL {
  const t = (key: string) => createScopedActionTerminal("team", teamId, key);

  return {
    create: t("team.create"),
    delete: t("team.delete"),
    list: t("team.list"),
    member: {
      add: t("team.member.add"),
      list: t("team.member.list"),
      read: t("team.member.read"),
      remove: t("team.member.remove"),
    },
    module: {
      access: t("team.module.access"),
      disable: t("team.module.disable"),
      enable: t("team.module.enable"),
    },
    read: t("team.read"),
    role: {
      assign: t("team.role.assign"),
      create: t("team.role.create"),
      delete: t("team.role.delete"),
      list: t("team.role.list"),
      read: t("team.role.read"),
      remove: t("team.role.remove"),
      update: t("team.role.update"),
    },
    update: t("team.update"),
  };
}
