import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { PERMISSIONS } from "../src/lib/vocabulary";

type TreeNode = {
  children: Map<string, TreeNode>;
  permissionKey?: string;
};

const IDENTIFIER_REGEX = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/;

const ROOT_DIR = resolve(import.meta.dir, "..");
const DSL_DIR = resolve(ROOT_DIR, "src/lib/dsl");

const FILE_HEADER =
  "// @generated by scripts/generate-permission-code.ts - DO NOT EDIT\n";

const capitalize = (value: string): string =>
  value.length === 0
    ? value
    : `${value[0]?.toUpperCase() ?? ""}${value.slice(1)}`;

const createNode = (): TreeNode => ({
  children: new Map<string, TreeNode>(),
});

const addPath = (
  root: TreeNode,
  segments: string[],
  permissionKey: string
): void => {
  let current = root;

  for (const segment of segments) {
    if (!current.children.has(segment)) {
      current.children.set(segment, createNode());
    }

    const next = current.children.get(segment);
    if (!next) {
      throw new Error(`Failed to create tree node for segment: ${segment}`);
    }

    current = next;
  }

  current.permissionKey = permissionKey;
};

const sortedEntries = (node: TreeNode): [string, TreeNode][] =>
  [...node.children.entries()].sort(([left], [right]) =>
    left.localeCompare(right)
  );

const toIdentifier = (segment: string): string =>
  segment
    .split(/[^a-zA-Z0-9]/g)
    .filter(Boolean)
    .map((part, index) => {
      if (index === 0) return part;
      return capitalize(part);
    })
    .join("");

const renderLiteralTree = (
  node: TreeNode,
  indent: string,
  path: string[] = []
): string[] => {
  const lines: string[] = [];

  for (const [segment, child] of sortedEntries(node)) {
    const key = IDENTIFIER_REGEX.test(segment)
      ? segment
      : JSON.stringify(segment);
    const nextPath = [...path, segment];

    if (child.permissionKey) {
      lines.push(`${indent}${key}: ${JSON.stringify(child.permissionKey)},`);
      continue;
    }

    lines.push(`${indent}${key}: {`);
    lines.push(...renderLiteralTree(child, `${indent}  `, nextPath));
    lines.push(`${indent}},`);
  }

  return lines;
};

const renderDslType = (node: TreeNode, indent: string): string[] => {
  const lines: string[] = [];

  for (const [segment, child] of sortedEntries(node)) {
    const key = IDENTIFIER_REGEX.test(segment)
      ? segment
      : JSON.stringify(segment);

    if (child.permissionKey) {
      lines.push(`${indent}${key}: PermissionAction;`);
      continue;
    }

    lines.push(`${indent}${key}: {`);
    lines.push(...renderDslType(child, `${indent}  `));
    lines.push(`${indent}};`);
  }

  return lines;
};

const renderDslReturn = (node: TreeNode, indent: string): string[] => {
  const lines: string[] = [];

  for (const [segment, child] of sortedEntries(node)) {
    const key = IDENTIFIER_REGEX.test(segment)
      ? segment
      : JSON.stringify(segment);

    if (child.permissionKey) {
      lines.push(`${indent}${key}: t(${JSON.stringify(child.permissionKey)}),`);
      continue;
    }

    lines.push(`${indent}${key}: {`);
    lines.push(...renderDslReturn(child, `${indent}  `));
    lines.push(`${indent}},`);
  }

  return lines;
};

const buildPermissionTree = (keys: string[]): TreeNode => {
  const root = createNode();

  for (const key of keys) {
    const segments = key.split(".");
    addPath(root, segments, key);
  }

  return root;
};

const generateKeysFile = (permissionKeys: string[]): string => {
  const root = buildPermissionTree(permissionKeys);
  const literalLines = renderLiteralTree(root, "  ");

  return `${FILE_HEADER}
export const permissionKey = {
${literalLines.join("\n")}
} as const;

type LeafValues<T> = T extends string
  ? T
  : { [K in keyof T]: LeafValues<T[K]> }[keyof T];

export type PermissionKeyFromDSL = LeafValues<typeof permissionKey>;

export type PermissionKeys = typeof permissionKey;

type AndExpression = { _type: "and"; operands: PermissionExpression[] };
type OrExpression = { _type: "or"; operands: PermissionExpression[] };
type NotExpression = { _type: "not"; operand: PermissionExpression };

export type PermissionExpression =
  | PermissionKeyFromDSL
  | AndExpression
  | OrExpression
  | NotExpression;

export function and(...operands: PermissionExpression[]): AndExpression {
  return { _type: "and", operands };
}

export function or(...operands: PermissionExpression[]): OrExpression {
  return { _type: "or", operands };
}

export function not(operand: PermissionExpression): NotExpression {
  return { _type: "not", operand };
}

export type PermissionSelector = (
  p: PermissionKeys,
  ops: { and: typeof and; or: typeof or; not: typeof not }
) => PermissionExpression;

export type PermissionInput = PermissionKeyFromDSL | PermissionSelector;

export function resolvePermission(
  input: PermissionInput
): PermissionExpression {
  if (typeof input === "function") {
    return input(permissionKey, { and, or, not });
  }
  return input;
}

export function evaluateExpression(
  expr: PermissionExpression,
  permissions: Record<string, boolean>
): boolean {
  if (typeof expr === "string") {
    return permissions[expr] ?? false;
  }

  switch (expr._type) {
    case "and":
      return expr.operands.every((operand) =>
        evaluateExpression(operand, permissions)
      );
    case "or":
      return expr.operands.some((operand) =>
        evaluateExpression(operand, permissions)
      );
    case "not":
      return !evaluateExpression(expr.operand, permissions);
    default:
      return false;
  }
}
`;
};

const generateDslFile = (
  resource: string,
  permissionKeys: string[],
  scoped: boolean
): string => {
  const root = createNode();

  for (const key of permissionKeys) {
    const segments = key.split(".");
    const withoutResource = segments.slice(1);
    addPath(root, withoutResource, key);
  }

  const resourceName = capitalize(resource);
  const typeName = `${resourceName}DSL`;
  const typeLines = renderDslType(root, "  ");
  const returnLines = renderDslReturn(root, "    ");

  const terminalFactory = scoped
    ? `const t = (key: string) => createScopedActionTerminal("${resource}", ${toIdentifier(resource)}Id, key);`
    : "const t = (key: string) => createActionTerminal(key);";

  const functionSignature = scoped
    ? `export function ${resourceName}(${toIdentifier(resource)}Id: string): ${typeName} {`
    : `export function ${resourceName}(): ${typeName} {`;

  const sharedImport = scoped
    ? 'import { createScopedActionTerminal } from "./shared";'
    : 'import { createActionTerminal } from "./shared";';

  return `${FILE_HEADER}
import type { PermissionAction } from "../types";
${sharedImport}

export type ${typeName} = {
${typeLines.join("\n")}
};

${functionSignature}
  ${terminalFactory}

  return {
${returnLines.join("\n")}
  };
}
`;
};

const main = async (): Promise<void> => {
  const permissionKeys = [
    ...new Set(PERMISSIONS.map((permission) => permission.key)),
  ].sort((left, right) => left.localeCompare(right));

  const byResource = new Map<string, string[]>();
  for (const key of permissionKeys) {
    const resource = key.split(".")[0];
    if (!resource) continue;

    if (!byResource.has(resource)) {
      byResource.set(resource, []);
    }

    const existing = byResource.get(resource);
    if (!existing) continue;
    existing.push(key);
  }

  await mkdir(DSL_DIR, { recursive: true });
  await writeFile(
    resolve(DSL_DIR, "keys.ts"),
    generateKeysFile(permissionKeys)
  );

  for (const [resource, keys] of byResource) {
    const scoped = resource === "org" || resource === "team";
    await writeFile(
      resolve(DSL_DIR, `${resource}.ts`),
      generateDslFile(resource, keys, scoped)
    );
  }
};

await main();
